const { generateCashierReportData } = require('../src/printData');

let rest_details = {
  _id: { $oid: '629f1445c204870048f0b9e7' },
  id: '54de918896774f82bc8a921a25b24d79',
  name: 'Deep Cafe',
  nameid: 'deepcafe',
  logo: '',
  state: '',
  phone: '1234567089',
  dial_code: '++91',
  email: 'altaf.hussain@easyeat.ai',
  pin_code: '122001',
  country: 'Malaysia',
  address: 'KGF Tower, Sector-28',
  location: { lat: 3.07588585009742, lon: 101.587342520213 },
  is_dummy_outlet: false,
  printer: '192.168.29.201:9100',
  city: 'Gurgaon',
  discount: [0, 0, 0],
  restaurant_certificates: [],
  account_details: [],
  tax_details: [],
  fee: [],
  preparation_time: [],
  geo_location: { type: 'Point', coordinates: [101.587342520213, 3.07588585009742] },
  next_open_epoch: 0,
  base_roundoff: 0.05,
  on_whatsapp: 1,
  delivery_time: 20,
  type: 3,
  deliverylimit: 50,
  status: 1,
  mall: '',
  emails: { cm: ['deepcafe@easyeat.ai'], pm: ['deepcafe@easyeat.ai'], am: ['deepcafe@easyeat.ai'] },
  config_timings: [{ id: 'f', name: 'FullDay', timing: [480, 1320] }],
  rest_timings: {
    DINING: [
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
    ],
    DELIVERY: [
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
    ],
    TAKEAWAY: [
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
      { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
    ],
  },
  restaurant_open_days: [['f'], ['f'], ['f'], ['f'], ['f'], ['f'], ['f']],
  time_zone: 'Asia/Jakarta',
  fees: [
    {
      id: 'delivery',
      status: 1,
      name: 'Delivery Fee',
      tax: 0,
      data: [
        5, 5, 5, 5.4, 6, 6.6, 7.2, 7.9, 8.6, 9.3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22,
        24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
        70, 72, 74, 76, 78, 80,
      ],
    },
  ],
  addons: [],
  delivery_partner: [
    { partner_id: '1', partner_name: 'mrspeedy', priority: 0 },
    { partner_id: '2', partner_name: 'lalamove', priority: 2 },
  ],
  company_name: '',
  cuisine: [],
  pref_filter: [],
  bnk_nm: '',
  bnk_accn: '',
  acc_holder_nm: '',
  services: [
    {
      category_id: 'cutlery',
      category_name: 'Cutlery',
      icon: 'cutlery-1.png',
      subcategories: [
        {
          subcategory_id: 'cutlery-plate',
          subcategory_name: 'Plate',
          icon: 'dish_plate.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'cutlery-bowl',
          subcategory_name: 'Bowl',
          icon: 'bowl-1.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'cutlery-glass',
          subcategory_name: 'Glass',
          icon: 'glass.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'cutlery-spoon',
          subcategory_name: 'Spoon',
          icon: 'spoon.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'cutlery-fork',
          subcategory_name: 'Fork',
          icon: 'fork.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'cutlery-chopstick',
          subcategory_name: 'Chopstick',
          icon: 'chopsticks.svg',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'cutlery-knife',
          subcategory_name: 'Knife',
          icon: 'knife.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'cutlery-straw',
          subcategory_name: 'Straw',
          icon: 'drinking-straw.svg',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
      ],
      status: 0,
    },
    {
      category_id: 'water',
      category_name: 'Water',
      icon: 'glass.png',
      subcategories: [
        {
          subcategory_id: 'water-regular',
          subcategory_name: 'Regular Water',
          icon: 'glass.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'water-mineral',
          subcategory_name: 'Mineral Water',
          icon: 'water.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'water-hot',
          subcategory_name: 'Hot Water',
          icon: 'water-1.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'water-lemon',
          subcategory_name: 'Lemon Water',
          icon: 'glass.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'water-filtered',
          subcategory_name: 'Filtered Water',
          icon: 'glass.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'water-ice',
          subcategory_name: 'Ice Water',
          icon: 'glass.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
      ],
      status: 0,
    },
    {
      category_id: 'sauces',
      category_name: 'Sauces',
      icon: 'sauces.png',
      subcategories: [
        {
          subcategory_id: 'sauces-tomato',
          subcategory_name: 'Tomato Sauce',
          icon: 'tomato-ketchup.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-alfredo',
          subcategory_name: 'Alfredo',
          icon: '',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-pesto',
          subcategory_name: 'Pesto Sauce',
          icon: 'pesto-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-marinara',
          subcategory_name: 'Marinara',
          icon: '',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-bbq',
          subcategory_name: 'Barbeque Sauce',
          icon: 'bbq-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-chilli',
          subcategory_name: 'Chilli Sauce',
          icon: 'chilli-sauce.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-salsa',
          subcategory_name: 'Salsa',
          icon: '',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-garlic',
          subcategory_name: 'Garlic Sauce',
          icon: 'garlic-sauce.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-mustard',
          subcategory_name: 'Mustard Sauce',
          icon: 'mustard-1.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-mayo',
          subcategory_name: 'Mayonnaise',
          icon: 'mayonnaise-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-tamarind',
          subcategory_name: 'Tamarind',
          icon: 'imli-chatni.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-mint',
          subcategory_name: 'Mint Sauce',
          icon: 'mint-chatni.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-tobasco',
          subcategory_name: 'Tobasco',
          icon: 'tobasco.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-coconut-chutney',
          subcategory_name: 'Coconut chutney',
          icon: 'coconut-chatni.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-coriander-chutney',
          subcategory_name: 'Coriander chutney',
          icon: 'coriander-chatni.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-samber',
          subcategory_name: 'Samber',
          icon: 'Samber.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-sriranha-mayo',
          subcategory_name: 'Sriracha Mayo',
          icon: 'sriracha-mayo.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-duck',
          subcategory_name: 'Duck Sauce',
          icon: 'duck-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-teriyaki',
          subcategory_name: 'Teriyaki Sauce',
          icon: 'teriyaki-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
      ],
      status: 0,
    },
    {
      category_id: 'condiments',
      category_name: 'Condiments',
      icon: '',
      subcategories: [
        {
          subcategory_id: 'condiments-salt',
          subcategory_name: 'Salt',
          icon: 'salt.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'condiments-pepper',
          subcategory_name: 'Pepper',
          icon: 'pepper-1.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'condiments-oregano',
          subcategory_name: 'Oregano',
          icon: '',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'condiments-chilli-flakes',
          subcategory_name: 'Chilli Flakes',
          icon: 'salt.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'condiments-parmesan-cheese',
          subcategory_name: 'Parmesan Cheese',
          icon: 'parmesan-cheese.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'condiments-parmesan-cheese',
          subcategory_name: 'Parmesan Cheese',
          icon: 'parmesan-cheese.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
      ],
      status: 0,
    },
    {
      category_id: 'napkin',
      category_name: 'Napkin',
      icon: 'napkin.png',
      subcategories: [],
      status: 0,
    },
    {
      category_id: 'call-server',
      category_name: 'Call the Server',
      icon: 'waiter.png',
      subcategories: [],
      status: 0,
    },
    {
      category_id: 'wifi-password',
      category_name: 'Wifi Password',
      icon: 'wifi-signal.png',
      ssid: '',
      password: '',
      subcategories: [],
      status: 0,
    },
    {
      category_id: 'smoking-accessories',
      category_name: 'Smoking',
      icon: 'smoking-cat.png',
      subcategories: [
        {
          subcategory_id: 'smoking-ashtray',
          subcategory_name: 'Ashtray',
          icon: 'ashtray.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'smoking-lighter',
          subcategory_name: 'Lighter',
          icon: 'lighter.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
      ],
      status: 0,
    },
  ],
  filters: [
    { id: 'veg', name: 'Veg', 'filter-type': 'preference', status: 0 },
    { id: 'non-veg', name: 'Non Veg', 'filter-type': 'preference', status: 0 },
    { id: 'halal', name: 'Halal', 'filter-type': 'preference', status: 0 },
    { id: 'kosher', name: 'Kosher', 'filter-type': 'preference', status: 0 },
    { id: 'gluten-free', name: 'Gluten Free', 'filter-type': 'preference', status: 0 },
    { id: 'vegan', name: 'Vegan', 'filter-type': 'preference', status: 0 },
    { id: 'price-5', name: '5', currency: 'MYR', 'filter-type': 'price', status: 0, value: 5 },
    { id: 'price-10', name: '10', currency: 'MYR', 'filter-type': 'price', status: 0, value: 10 },
    { id: 'price-15', name: '15', currency: 'MYR', 'filter-type': 'price', status: 0, value: 15 },
    { id: 'price-20', name: '20', currency: 'MYR', 'filter-type': 'price', status: 0, value: 20 },
    { id: 'price-30', name: '30', currency: 'MYR', 'filter-type': 'price', status: 0, value: 30 },
    { id: 'price-40', name: '40', currency: 'MYR', 'filter-type': 'price', status: 0, value: 40 },
    { id: 'price-50', name: '15', currency: 'MYR', 'filter-type': 'price', status: 0, value: 15 },
    { id: 'available', name: 'available', 'filter-type': 'preference', status: 1, selected: true },
  ],
  offline_platforms: [
    {
      id: 'grab',
      name: 'Grab',
      img: 'grab.png',
      order_type: 1,
      comm_amt: 0,
      comm_typ: 'percentage',
    },
    {
      id: 'foodpanda',
      name: 'Foodpanda',
      img: 'panda.png',
      order_type: 1,
      comm_amt: 0,
      comm_typ: 'percentage',
    },
    {
      id: 'others',
      name: 'Others',
      img: 'others_platform.svg',
      order_type: 1,
      comm_amt: 0,
      comm_typ: 'percentage',
    },
  ],
  settings: {
    print: {
      enabled: 1,
      print_bahasa: 0,
      cash_drawer: 0,
      master_docket: 0,
      on_decline: 0,
      on_void_unaccepted: 2,
      on_void_accepted: 2,
      on_void_new_itr: 2,
      on_accept_new_order: 2,
      on_accept_new_itr: 2,
      on_settle: 1,
      on_table_change: 2,
      format_code: null,
      separate_docket: 0,
      void_format_code: null,
      void_separate_docket: 0,
      show_logo: 0,
      print_delay: 3000,
      item_align: 'l',
      font_size: 'l',
      on_accept_enabled: 1,
      void_enabled: 0,
      footer: ['thank you', 'visit again.'],
      header: { custom: ['Deep Cafe', 'KGF Tower, Sector-29'] },
      cash_mgt_format_override: 0,
      inst_font: 's',
      pmt_mode_in_body: 0,
      post_settle: 2,
      response_format: 1,
      show_op_order_id: 2,
      slip_font: {
        bill: 'm',
        counter: 'm',
        master_order_list: 'm',
        master_docket: 'm',
        table_change: 'm',
        cash_in_out: 'm',
        cash_mgt_report: 'm',
      },
      sname: 0,
      table_no_position: 't',
      uname: 0,
    },
    settlement: { enable: 1, visible: 1 },
    login: { skip_verification: 0 },
    reports: {
      enable_eod: 1,
      eod_printer: 'default',
      eod_font_size: '6px',
      eod_page_width: '130px',
      full_eod: 0,
    },
    global: {
      hide_order_image: 1,
      visible_on_app: 1,
      table_layout: 1,
      cash_registry: 1,
      fp_integration: 1,
      no_login_workflow: 1,
      enable_rest_food_logo: 0,
      gf_integration: 1,
      auto_accept: 7,
      auto_accept_sch: 7,
      cust_info_popup: 0,
      hide_download_popup: 0,
      disable_add_more_items: 0,
      skip_service_chrg: 0,
      use_es_service: 1,
      custom_order_dashboard: 1,
      mark_order_prepared: 1,
      multiple_addon: 1,
      hide_action_button: 1,
      split_bill: 1,
      void: 1,
      whatsapp_notifier_order_status: 0,
      enable_server_flow: 0,
      disable_allergy_label: 0,
      delete_order: 0,
      edit_commision: 1,
      enable_pre_paid_order: 1,
      lock_screen: 0,
      lock_screen_idle: 300,
      lock_screen_timeout: 20,
      loyalty: 0,
      mark_prepared_sms: 0,
      pos: 1,
      posItemPriceTKasDinein: 0,
      pos_view: 'l',
      service_bell_enable: 1,
      skip_pkg_chrg: 0,
      skip_pkg_chrg_order_type: 4,
      special_menu: 0,
      takeaway_cash_enable: 0,
      tossed_specific: 0,
      void_item_after_completed: 0,
      print_v2_enabled: 1,
      print_debug_messages: 1,
      auto_refresh: 0,
      pre_paid_order: 2,
    },
    menu: { new_variation: 1, item_code: 5, item_code_max_len: 3, pax: 0, cmm_enable: 1 },
    sounds: { repeat: 1, selected: 'sound1.wav', timeout: 15000 },
  },
  open_items: {
    def_cat: 'feaf966247764be4807e295b57c42d2b',
    def_subcat: '743b3c0a88074bddac83bfc69d14d313',
  },
  dkick_code: [27, 112, 48, 55, 121],
  tech_charges: [],
  pg_charges: [
    {
      online: {
        charges: [{ charge_type: 'percent', charge: 0 }],
        'credit-card': {
          charges: [
            { charge_type: 'flat', charge: 1500 },
            { charge_type: 'percent', charge: 2.5 },
          ],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'direct-debit': {
          charges: [
            { charge_type: 'flat', charge: 1500 },
            { charge_type: 'percent', charge: 1.5 },
          ],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'cimb-direct-debit': {
          charges: [
            { charge_type: 'flat', charge: 1500 },
            { charge_type: 'percent', charge: 1.5 },
          ],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'bca-virtual-account': {
          charges: [{ charge_type: 'flat', charge: 4500 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'bni-virtual-account': {
          charges: [{ charge_type: 'flat', charge: 1800 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'bri-virtual-account': {
          charges: [{ charge_type: 'flat', charge: 1800 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'bsm-virtual-account': {
          charges: [{ charge_type: 'flat', charge: 1800 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'cimb-virtual-account': {
          charges: [{ charge_type: 'flat', charge: 1800 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'doku-virtual-account': {
          charges: [{ charge_type: 'flat', charge: 1800 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'danamon-virtual-account': {
          charges: [{ charge_type: 'flat', charge: 1800 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'mandiri-virtual-account': {
          charges: [{ charge_type: 'flat', charge: 1800 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'permata-virtual-account': {
          charges: [{ charge_type: 'flat', charge: 1800 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'dokuwallet-emoney': {
          charges: [{ charge_type: 'percent', charge: 1.65 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'ovo-emoney': {
          charges: [{ charge_type: 'percent', charge: 1.5 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'ovo-open-api': {
          charges: [{ charge_type: 'percent', charge: 1.5 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        'shopeepay-emoney': {
          charges: [{ charge_type: 'percent', charge: 1.65 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
        qris: {
          charges: [{ charge_type: 'percent', charge: 0.7 }],
          start_epoch: 1659100716,
          end_epoch: null,
        },
      },
      offline: { charges: [{ charge_type: 'percent', charge: 0 }] },
      start_epoch: 1659100716,
      end_epoch: null,
    },
  ],
  block_pmt: [],
  quick_notes: [
    { id: '3919716167474954b63646a4d0d27306', note: 'Less Spicy', visible_to_user: 1 },
    { id: '1cc5ca1cd1554fcb8a4100ce30f9fc07', note: 'alt', visible_to_user: 1 },
    { id: '8008ad8b28e04eac8cad848ede193ec9', note: 'Alt', visible_to_user: 1 },
    { id: '19d2320d25644c20bc48035cfa647704', note: 'heLL', visible_to_user: 1 },
    { id: 'cb567f28651f4bd6b9f6997eabdf1018', note: 'heLLo1', visible_to_user: 1 },
    { id: 'cd8f8e48c4b740d5ad1f93daa16f2196', note: 'Hello', visible_to_user: 1 },
    { id: 'b7b6d182e61d4150a1bfb22b71ca9b44', note: 'HOT & SPICY', visible_to_user: 1 },
  ],
  country_code: 'MY',
  curr_code: 'MYR',
  curr_sym: 'RM',
  language: 'en_US',
  created_at: 1654592581,
  hq_id: '7cc8a0a1bd4c4d2c8993ad1e42ce33c4',
  default_cuisine_image: 'restaurant_food_image/cuisine/no_cuisine/image.png',
  promo_charges: [],
  print_logo: '',
};

let order_details = [
  {
    order_id: 'tmx2cWqYBb1659963721',
    order_no: '15831L02',
    user_id: 'e937ed4723d5d874f2813b91603647235ea6c89addae4ff65fd76e55e67f9e0a',
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    restaurant_name: 'Deep Cafe',
    order_status: 3,
    bill_id: '',
    created_at: 1659963721,
    created_mongodate: '2022-08-08T13:02:01.227Z',
    date: '2022-08-08',
    confirmed_at: 0,
    canceled_at: 0,
    mark_prepared_at: 1659963721,
    schedule_confirmed_at: 0,
    estimated_time: 0,
    completed_at: 0,
    table_id: 'a1',
    table_no: '1',
    floor_id: 'a',
    floor_name: 'Ground Section',
    items: [
      {
        itr: 1,
        item_id: 'b757901190b1456cba96e9ae45bb86df',
        item_name: 'Milodino 恐⻰美禄',
        item_quantity: 1,
        item_price: 35,
        original_price: 35,
        discount_per: 0,
        reward_id: '',
        created_at: '1659963721',
        confirmed_at: 1659963721,
        completed_at: '',
        kitchen_counter_id: null,
        kitchen_picked_at: '',
        kitchen_picked_by: '',
        kitchen_time_to_complete: 10,
        item_status: 3,
        order_item_id: 'WTRLXb757901190b1456cba96e9ae45bb86df',
        prepared_at: 1659963721,
        canceled_at: 0,
        void_at: 0,
        declined_at: 0,
        special_note: '',
        decline_reason: [],
        base_qty: 1,
        unit: 'number',
        gvariations: null,
        variation_ids: '',
        addons: [],
        addon_ids: null,
        gvariation_name: '',
        variation_name: '',
        addons_name: '',
        category_id: '4bb9f8d71b5e705aabb714b765fb6fe673471356b4d23e11bf7fa3e42f6cc55f',
        subcategory_id: '23d9405018ff3af0e2eb83c994db7c50ad5e2c560788e77826248feb03ef8f55',
        is_combo_item: 0,
        cmm_id: null,
        hq_id: null,
        order_by: 'MM',
        new_variation_name: '',
        new_addons_name: '',
        combo_items: [],
        open_item: 0,
        item_code: null,
        new_variation_ids: null,
        variant_info: [],
      },
    ],
    special_notes: [],
    allergic_items: [],
    address: '',
    distance: 0,
    order_type: 0,
    delivery_partner: null,
    delivery_assign_type: null,
    address_obj: null,
    platform: 'easyeat',
    pax: 1,
    order_seq: '1-2',
    op_no: null,
    coupon_id: '',
    coupon_name: '',
    reason: null,
    base_roundoff: 0.05,
    auto_assign_car: null,
    user_platform: '',
    country_code: 'MY',
    skip_service_charge_operation: '0',
    skip_packaging_charge_operation: 0,
    op_order_creation_time: '',
    currency: { curr_sym: 'RM', curr_code: 'MYR' },
    discovery_page: 2,
    order_by: 'MM',
    no_enter: '0',
    name: 'easyeat user',
    phone: '187731010715988',
    dial_code: '+60',
    time_epoch: 0,
    scheduled: 0,
    rest_reach_min_time: 2,
    sname: '',
  },
];

let kitchen_details = {
  kitchen_counter_id: 'X6MPxmwbZj62b1883dbfbd3',
};

let kitchen_counter_details = {
  b757901190b1456cba96e9ae45bb86df: [
    {
      kc_id: 'X6MPxmwbZj62b1883dbfbd3',
      counter_name: 'main_course',
      printer_name: '192.168.29.201:9100',
      is_sticker_printer: 1,
      kitchen_counter_id: 'X6MPxmwbZj62b1883dbfbd3',
    },
  ],
};

// let menu_kitchen_counters = {};

// for (let item of order_details[0]['items']) {
//   if (!menu_kitchen_counters[item['item_id']]) {
//     menu_kitchen_counters[item['item_id']] = {};
//   }
//   menu_kitchen_counters[item['item_id']]['kitchen_counter_id'] = 'X6MPxmwbZj62b1883dbfbd3';
// }

let subcat_counters = {
  '23d9405018ff3af0e2eb83c994db7c50ad5e2c560788e77826248feb03ef8f55': [
    {
      kc_id: '6MPxmwbZj62b1883dbfbd',
      counter_name: 'sub category counter',
      printer_name: '192.168.10.100:9100',
      is_sticker_printer: 0,
      kitchen_counter_id: '6MPxmwbZj62b1883dbfbd',
    },
  ],
};

let bill_details = {
  _id: '62f10949a2c9cb6d9207d9f7',
  bill_id: 'qeqxFZK8h71659963721',
  order_id: 'tmx2cWqYBb1659963721',
  payments: [],
  user_id: 'e937ed4723d5d874f2813b91603647235ea6c89addae4ff65fd76e55e67f9e0a',
  restaurant_id: '54de918896774f82bc8a921a25b24d79',
  curr_code: 'MYR',
  fees: [
    { id: 'item_total', fee_name: 'Item Total', fee: 35, tax: 0 },
    { id: 'coupon_discount', fee_name: 'Discount', fee: 0, tax: 0 },
    { id: 'round_off', fee_name: 'Round Off', fee: 0, tax: 0 },
  ],
  item_total: 35,
  tax: 0,
  bill_total: 35,
  savings: 0,
  earnings: 0,
  balance: 35,
  paid: 0,
  date: '2022-08-08',
  timestamp: 1659963721,
};

let cash_mgt_data = [
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    cash_in_drawer: 90,
    active_epoch: null,
    txn_entries: [],
  },
];

let cash_mgt_entries_data =
  /* 1 */
  [
    {
      restaurant_id: '54de918896774f82bc8a921a25b24d79',
      txn_id: 'ceadb48bee7942af98e650b5d7ed990a',
      type: 'drawer-kick',
      staff_name: 'Deepanshu',
      amount: null,
      reason: 'Testing',
      created_at: 1662960761,
    },
  ];

console.log(
  JSON.stringify(
    generateCashierReportData(
      rest_details,
      1,
      cash_mgt_data,
      cash_mgt_entries_data,
      'ceadb48bee7942af98e650b5d7ed990a',
      '',
      cash_mgt_entries_data,
      'MY',
      'en-US',
    ),
  ),
);
