const { generateCashierReportData } = require('../src/printData');

// let rest_details = {
//   _id: { $oid: '629f1445c204870048f0b9e7' },
//   id: '54de918896774f82bc8a921a25b24d79',
//   name: 'Deep Cafe',
//   nameid: 'deepcafe',
//   logo: '',
//   state: '',
//   phone: '1234567089',
//   dial_code: '++91',
//   email: 'altaf.hussain@easyeat.ai',
//   pin_code: '122001',
//   country: 'Malaysia',
//   address: 'KGF Tower, Sector-28',
//   location: { lat: 3.07588585009742, lon: 101.587342520213 },
//   is_dummy_outlet: false,
//   printer: '192.168.29.201:9100',
//   city: 'Gurgaon',
//   discount: [0, 0, 0],
//   restaurant_certificates: [],
//   account_details: [],
//   tax_details: [],
//   fee: [],
//   preparation_time: [],
//   geo_location: { type: 'Point', coordinates: [101.587342520213, 3.07588585009742] },
//   next_open_epoch: 0,
//   base_roundoff: 0.05,
//   on_whatsapp: 1,
//   delivery_time: 20,
//   type: 3,
//   deliverylimit: 50,
//   status: 1,
//   mall: '',
//   emails: { cm: ['deepcafe@easyeat.ai'], pm: ['deepcafe@easyeat.ai'], am: ['deepcafe@easyeat.ai'] },
//   config_timings: [{ id: 'f', name: 'FullDay', timing: [480, 1320] }],
//   rest_timings: {
//     DINING: [
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//     ],
//     DELIVERY: [
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//     ],
//     TAKEAWAY: [
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//     ],
//   },
//   restaurant_open_days: [['f'], ['f'], ['f'], ['f'], ['f'], ['f'], ['f']],
//   time_zone: 'Asia/Jakarta',
//   fees: [
//     {
//       id: 'delivery',
//       status: 1,
//       name: 'Delivery Fee',
//       tax: 0,
//       data: [
//         5, 5, 5, 5.4, 6, 6.6, 7.2, 7.9, 8.6, 9.3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22,
//         24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
//         70, 72, 74, 76, 78, 80,
//       ],
//     },
//   ],
//   addons: [],
//   delivery_partner: [
//     { partner_id: '1', partner_name: 'mrspeedy', priority: 0 },
//     { partner_id: '2', partner_name: 'lalamove', priority: 2 },
//   ],
//   company_name: '',
//   cuisine: [],
//   pref_filter: [],
//   bnk_nm: '',
//   bnk_accn: '',
//   acc_holder_nm: '',
//   services: [
//     {
//       category_id: 'cutlery',
//       category_name: 'Cutlery',
//       icon: 'cutlery-1.png',
//       subcategories: [
//         {
//           subcategory_id: 'cutlery-plate',
//           subcategory_name: 'Plate',
//           icon: 'dish_plate.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-bowl',
//           subcategory_name: 'Bowl',
//           icon: 'bowl-1.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-glass',
//           subcategory_name: 'Glass',
//           icon: 'glass.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-spoon',
//           subcategory_name: 'Spoon',
//           icon: 'spoon.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-fork',
//           subcategory_name: 'Fork',
//           icon: 'fork.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-chopstick',
//           subcategory_name: 'Chopstick',
//           icon: 'chopsticks.svg',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-knife',
//           subcategory_name: 'Knife',
//           icon: 'knife.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-straw',
//           subcategory_name: 'Straw',
//           icon: 'drinking-straw.svg',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//     {
//       category_id: 'water',
//       category_name: 'Water',
//       icon: 'glass.png',
//       subcategories: [
//         {
//           subcategory_id: 'water-regular',
//           subcategory_name: 'Regular Water',
//           icon: 'glass.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-mineral',
//           subcategory_name: 'Mineral Water',
//           icon: 'water.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-hot',
//           subcategory_name: 'Hot Water',
//           icon: 'water-1.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-lemon',
//           subcategory_name: 'Lemon Water',
//           icon: 'glass.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-filtered',
//           subcategory_name: 'Filtered Water',
//           icon: 'glass.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-ice',
//           subcategory_name: 'Ice Water',
//           icon: 'glass.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//     {
//       category_id: 'sauces',
//       category_name: 'Sauces',
//       icon: 'sauces.png',
//       subcategories: [
//         {
//           subcategory_id: 'sauces-tomato',
//           subcategory_name: 'Tomato Sauce',
//           icon: 'tomato-ketchup.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-alfredo',
//           subcategory_name: 'Alfredo',
//           icon: '',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-pesto',
//           subcategory_name: 'Pesto Sauce',
//           icon: 'pesto-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-marinara',
//           subcategory_name: 'Marinara',
//           icon: '',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-bbq',
//           subcategory_name: 'Barbeque Sauce',
//           icon: 'bbq-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-chilli',
//           subcategory_name: 'Chilli Sauce',
//           icon: 'chilli-sauce.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-salsa',
//           subcategory_name: 'Salsa',
//           icon: '',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-garlic',
//           subcategory_name: 'Garlic Sauce',
//           icon: 'garlic-sauce.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-mustard',
//           subcategory_name: 'Mustard Sauce',
//           icon: 'mustard-1.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-mayo',
//           subcategory_name: 'Mayonnaise',
//           icon: 'mayonnaise-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-tamarind',
//           subcategory_name: 'Tamarind',
//           icon: 'imli-chatni.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-mint',
//           subcategory_name: 'Mint Sauce',
//           icon: 'mint-chatni.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-tobasco',
//           subcategory_name: 'Tobasco',
//           icon: 'tobasco.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-coconut-chutney',
//           subcategory_name: 'Coconut chutney',
//           icon: 'coconut-chatni.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-coriander-chutney',
//           subcategory_name: 'Coriander chutney',
//           icon: 'coriander-chatni.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-samber',
//           subcategory_name: 'Samber',
//           icon: 'Samber.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-sriranha-mayo',
//           subcategory_name: 'Sriracha Mayo',
//           icon: 'sriracha-mayo.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-duck',
//           subcategory_name: 'Duck Sauce',
//           icon: 'duck-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-teriyaki',
//           subcategory_name: 'Teriyaki Sauce',
//           icon: 'teriyaki-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//     {
//       category_id: 'condiments',
//       category_name: 'Condiments',
//       icon: '',
//       subcategories: [
//         {
//           subcategory_id: 'condiments-salt',
//           subcategory_name: 'Salt',
//           icon: 'salt.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-pepper',
//           subcategory_name: 'Pepper',
//           icon: 'pepper-1.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-oregano',
//           subcategory_name: 'Oregano',
//           icon: '',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-chilli-flakes',
//           subcategory_name: 'Chilli Flakes',
//           icon: 'salt.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-parmesan-cheese',
//           subcategory_name: 'Parmesan Cheese',
//           icon: 'parmesan-cheese.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-parmesan-cheese',
//           subcategory_name: 'Parmesan Cheese',
//           icon: 'parmesan-cheese.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//     {
//       category_id: 'napkin',
//       category_name: 'Napkin',
//       icon: 'napkin.png',
//       subcategories: [],
//       status: 0,
//     },
//     {
//       category_id: 'call-server',
//       category_name: 'Call the Server',
//       icon: 'waiter.png',
//       subcategories: [],
//       status: 0,
//     },
//     {
//       category_id: 'wifi-password',
//       category_name: 'Wifi Password',
//       icon: 'wifi-signal.png',
//       ssid: '',
//       password: '',
//       subcategories: [],
//       status: 0,
//     },
//     {
//       category_id: 'smoking-accessories',
//       category_name: 'Smoking',
//       icon: 'smoking-cat.png',
//       subcategories: [
//         {
//           subcategory_id: 'smoking-ashtray',
//           subcategory_name: 'Ashtray',
//           icon: 'ashtray.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'smoking-lighter',
//           subcategory_name: 'Lighter',
//           icon: 'lighter.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//   ],
//   filters: [
//     { id: 'veg', name: 'Veg', 'filter-type': 'preference', status: 0 },
//     { id: 'non-veg', name: 'Non Veg', 'filter-type': 'preference', status: 0 },
//     { id: 'halal', name: 'Halal', 'filter-type': 'preference', status: 0 },
//     { id: 'kosher', name: 'Kosher', 'filter-type': 'preference', status: 0 },
//     { id: 'gluten-free', name: 'Gluten Free', 'filter-type': 'preference', status: 0 },
//     { id: 'vegan', name: 'Vegan', 'filter-type': 'preference', status: 0 },
//     { id: 'price-5', name: '5', currency: 'MYR', 'filter-type': 'price', status: 0, value: 5 },
//     { id: 'price-10', name: '10', currency: 'MYR', 'filter-type': 'price', status: 0, value: 10 },
//     { id: 'price-15', name: '15', currency: 'MYR', 'filter-type': 'price', status: 0, value: 15 },
//     { id: 'price-20', name: '20', currency: 'MYR', 'filter-type': 'price', status: 0, value: 20 },
//     { id: 'price-30', name: '30', currency: 'MYR', 'filter-type': 'price', status: 0, value: 30 },
//     { id: 'price-40', name: '40', currency: 'MYR', 'filter-type': 'price', status: 0, value: 40 },
//     { id: 'price-50', name: '15', currency: 'MYR', 'filter-type': 'price', status: 0, value: 15 },
//     { id: 'available', name: 'available', 'filter-type': 'preference', status: 1, selected: true },
//   ],
//   offline_platforms: [
//     {
//       id: 'grab',
//       name: 'Grab',
//       img: 'grab.png',
//       order_type: 1,
//       comm_amt: 0,
//       comm_typ: 'percentage',
//     },
//     {
//       id: 'foodpanda',
//       name: 'Foodpanda',
//       img: 'panda.png',
//       order_type: 1,
//       comm_amt: 0,
//       comm_typ: 'percentage',
//     },
//     {
//       id: 'others',
//       name: 'Others',
//       img: 'others_platform.svg',
//       order_type: 1,
//       comm_amt: 0,
//       comm_typ: 'percentage',
//     },
//   ],
//   settings: {
//     print: {
//       enabled: 1,
//       print_bahasa: 0,
//       cash_drawer: 0,
//       master_docket: 0,
//       on_decline: 0,
//       on_void_unaccepted: 2,
//       on_void_accepted: 2,
//       on_void_new_itr: 2,
//       on_accept_new_order: 2,
//       on_accept_new_itr: 2,
//       on_settle: 1,
//       on_table_change: 2,
//       format_code: null,
//       separate_docket: 0,
//       void_format_code: null,
//       void_separate_docket: 0,
//       show_logo: 0,
//       print_delay: 3000,
//       item_align: 'l',
//       font_size: 'l',
//       on_accept_enabled: 1,
//       void_enabled: 0,
//       footer: ['thank you', 'visit again.'],
//       header: { custom: ['Deep Cafe', 'KGF Tower, Sector-29'] },
//       cash_mgt_format_override: 0,
//       inst_font: 's',
//       pmt_mode_in_body: 0,
//       post_settle: 2,
//       response_format: 1,
//       show_op_order_id: 2,
//       slip_font: {
//         bill: 'm',
//         counter: 'm',
//         master_order_list: 'm',
//         master_docket: 'm',
//         table_change: 'm',
//         cash_in_out: 'm',
//         cash_mgt_report: 'm',
//       },
//       sname: 0,
//       table_no_position: 't',
//       uname: 0,
//     },
//     settlement: { enable: 1, visible: 1 },
//     login: { skip_verification: 0 },
//     reports: {
//       enable_eod: 1,
//       eod_printer: 'default',
//       eod_font_size: '6px',
//       eod_page_width: '130px',
//       full_eod: 0,
//     },
//     global: {
//       hide_order_image: 1,
//       visible_on_app: 1,
//       table_layout: 1,
//       cash_registry: 1,
//       fp_integration: 1,
//       no_login_workflow: 1,
//       enable_rest_food_logo: 0,
//       gf_integration: 1,
//       auto_accept: 7,
//       auto_accept_sch: 7,
//       cust_info_popup: 0,
//       hide_download_popup: 0,
//       disable_add_more_items: 0,
//       skip_service_chrg: 0,
//       use_es_service: 1,
//       custom_order_dashboard: 1,
//       mark_order_prepared: 1,
//       multiple_addon: 1,
//       hide_action_button: 1,
//       split_bill: 1,
//       void: 1,
//       whatsapp_notifier_order_status: 0,
//       enable_server_flow: 0,
//       disable_allergy_label: 0,
//       delete_order: 0,
//       edit_commision: 1,
//       enable_pre_paid_order: 1,
//       lock_screen: 0,
//       lock_screen_idle: 300,
//       lock_screen_timeout: 20,
//       loyalty: 0,
//       mark_prepared_sms: 0,
//       pos: 1,
//       posItemPriceTKasDinein: 0,
//       pos_view: 'l',
//       service_bell_enable: 1,
//       skip_pkg_chrg: 0,
//       skip_pkg_chrg_order_type: 4,
//       special_menu: 0,
//       takeaway_cash_enable: 0,
//       tossed_specific: 0,
//       void_item_after_completed: 0,
//       print_v2_enabled: 1,
//       print_debug_messages: 1,
//       auto_refresh: 0,
//       pre_paid_order: 2,
//     },
//     menu: { new_variation: 1, item_code: 5, item_code_max_len: 3, pax: 0, cmm_enable: 1 },
//     sounds: { repeat: 1, selected: 'sound1.wav', timeout: 15000 },
//   },
//   open_items: {
//     def_cat: 'feaf966247764be4807e295b57c42d2b',
//     def_subcat: '743b3c0a88074bddac83bfc69d14d313',
//   },
//   dkick_code: [27, 112, 48, 55, 121],
//   tech_charges: [],
//   pg_charges: [
//     {
//       online: {
//         charges: [{ charge_type: 'percent', charge: 0 }],
//         'credit-card': {
//           charges: [
//             { charge_type: 'flat', charge: 1500 },
//             { charge_type: 'percent', charge: 2.5 },
//           ],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'direct-debit': {
//           charges: [
//             { charge_type: 'flat', charge: 1500 },
//             { charge_type: 'percent', charge: 1.5 },
//           ],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'cimb-direct-debit': {
//           charges: [
//             { charge_type: 'flat', charge: 1500 },
//             { charge_type: 'percent', charge: 1.5 },
//           ],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'bca-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 4500 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'bni-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'bri-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'bsm-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'cimb-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'doku-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'danamon-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'mandiri-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'permata-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'dokuwallet-emoney': {
//           charges: [{ charge_type: 'percent', charge: 1.65 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'ovo-emoney': {
//           charges: [{ charge_type: 'percent', charge: 1.5 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'ovo-open-api': {
//           charges: [{ charge_type: 'percent', charge: 1.5 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'shopeepay-emoney': {
//           charges: [{ charge_type: 'percent', charge: 1.65 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         qris: {
//           charges: [{ charge_type: 'percent', charge: 0.7 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//       },
//       offline: { charges: [{ charge_type: 'percent', charge: 0 }] },
//       start_epoch: 1659100716,
//       end_epoch: null,
//     },
//   ],
//   block_pmt: [],
//   quick_notes: [
//     { id: '3919716167474954b63646a4d0d27306', note: 'Less Spicy', visible_to_user: 1 },
//     { id: '1cc5ca1cd1554fcb8a4100ce30f9fc07', note: 'alt', visible_to_user: 1 },
//     { id: '8008ad8b28e04eac8cad848ede193ec9', note: 'Alt', visible_to_user: 1 },
//     { id: '19d2320d25644c20bc48035cfa647704', note: 'heLL', visible_to_user: 1 },
//     { id: 'cb567f28651f4bd6b9f6997eabdf1018', note: 'heLLo1', visible_to_user: 1 },
//     { id: 'cd8f8e48c4b740d5ad1f93daa16f2196', note: 'Hello', visible_to_user: 1 },
//     { id: 'b7b6d182e61d4150a1bfb22b71ca9b44', note: 'HOT & SPICY', visible_to_user: 1 },
//   ],
//   country_code: 'MY',
//   curr_code: 'MYR',
//   curr_sym: 'RM',
//   language: 'en_US',
//   created_at: 1654592581,
//   hq_id: '7cc8a0a1bd4c4d2c8993ad1e42ce33c4',
//   default_cuisine_image: 'restaurant_food_image/cuisine/no_cuisine/image.png',
//   promo_charges: [],
//   print_logo: '',
// };

let rest_details = {
  id: 'c49dee80aeee27ab5e19689fcec88480',
  nameid: 'jibril',
  name: 'Jibril',
  alias: 'a3MO',
  logo: 'https://d1xkxcid7icwfl.cloudfront.net/restaurant_image/c49dee80aeee27ab5e19689fcec88480_1668164100.jpeg',
  address:
    'LG245, LG Floor Da Men Mall USJ, Persiaran Kewajipan, Usj 1, 47600 Subang Jaya, Selangor, Malaysia',
  menu_cover_img:
    'https://d1xkxcid7icwfl.cloudfront.net/coverimage/custom/c49dee80aeee27ab5e19689fcec88480/jibril-2021-07-20-05-25-33.jpg',
  city: 'Shah Alam',
  area: '',
  country: 'Malaysia',
  cashier: 'Ashutosh',
  status: 1,
  type: 3,
  on_whatsapp: 1,
  phone: '8433281075',
  dial_code: '+91',
  base_roundoff: 0.5,
  round_off_close: 1,
  email: 'dilip@easyeat.ai',
  default_customer_phone: '+60123456789',
  geo_location: {
    type: 'Point',
    coordinates: [101.587342520213, 3.07588585009742],
  },
  deliverylimit: 45,
  delivery_time: 20,
  delivery_partner: [],
  fees: [
    {
      id: 'delivery',
      status: 0,
      name: 'Delivery Fee',
      tax: 0,
      charges: [
        5, 5, 5, 5.4, 6, 6.6, 7.2, 7.9, 8.6, 9.3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22,
        24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
        70,
      ],
    },
    {
      id: 'service_tax',
      class: 'service_tax',
      status: 1,
      name: 'Service Charge',
      type: 'percentage',
      order_type: [0, 1, 2],
      tax: 0,
      data: {
        percentage_amount: 18,
      },
      applicable_on: ['category'],
      applicable_cat: ['9ac436de390a448488cca082769d849f'],
      applicable_subcat: ['18fd52aa008245bca734e9341e093ff4'],
      sub_name: 'Service charge',
    },
    {
      status: 1,
      type: 'percentage',
      order_type: [0, 1],
      data: {
        percentage_amount: 5,
      },
      tax: 0,
      applicable_on: ['category'],
      applicable_cat: [],
      applicable_subcat: [],
      class: 'sst_tax',
      id: 'sst_tax',
      name: 'SST',
      sub_name: 'SST',
    },
  ],
  avg_rating: 4.44117647058824,
  rest_timings: {
    DINING: [
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
    ],
    TAKEAWAY: [
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
    ],
    DELIVERY: [
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
      {
        is_enabled: true,
        slot: [
          {
            start: 0,
            end: 1439,
          },
        ],
        days: [],
      },
    ],
  },
  printer: '192.168.1.103:9100',
  cash_mgt_printer: null,
  dkick_code: [27, 112, 0, 50, 250],
  filters: [
    {
      id: 'veg',
      name: 'Veg',
      'filter-type': 'preference',
      status: 1,
    },
    {
      id: 'non-veg',
      name: 'Non Veg',
      'filter-type': 'preference',
      status: 1,
    },
    {
      id: 'halal',
      name: 'Halal',
      'filter-type': 'preference',
      status: 0,
    },
    {
      id: 'kosher',
      name: 'Kosher',
      'filter-type': 'preference',
      status: 0,
    },
    {
      id: 'gluten-free',
      name: 'Gluten Free',
      'filter-type': 'preference',
      status: 0,
    },
    {
      id: 'vegan',
      name: 'Vegan',
      'filter-type': 'preference',
      status: 0,
    },
    {
      id: 'price-5',
      name: '5',
      currency: 'MYR',
      'filter-type': 'price',
      status: 0,
      value: 5,
    },
    {
      id: 'price-10',
      name: '10',
      currency: 'MYR',
      'filter-type': 'price',
      status: 0,
      value: 10,
    },
    {
      id: 'price-15',
      name: '15',
      currency: 'MYR',
      'filter-type': 'price',
      status: 0,
      value: 15,
    },
    {
      id: 'price-20',
      name: '20',
      currency: 'MYR',
      'filter-type': 'price',
      status: 1,
      value: 20,
    },
    {
      id: 'price-50',
      name: '50',
      currency: 'MYR',
      'filter-type': 'price',
      status: 1,
      value: 50,
    },
    {
      id: 'price-40',
      name: '40',
      currency: 'MYR',
      'filter-type': 'price',
      status: 0,
      value: 40,
    },
    {
      id: 'price-50',
      name: '50',
      currency: 'MYR',
      'filter-type': 'price',
      status: 1,
    },
    {
      id: 'available',
      name: 'available',
      'filter-type': 'preference',
      status: 1,
    },
  ],
  services: [
    {
      category_id: 'cutlery',
      category_name: 'Cutlery',
      icon: 'cutlery-1.png',
      subcategories: [
        {
          subcategory_id: 'cutlery-plate',
          subcategory_name: 'Plate',
          icon: 'dish_plate.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'cutlery-bowl',
          subcategory_name: 'Bowl',
          icon: 'bowl-1.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'cutlery-glass',
          subcategory_name: 'Glass',
          icon: 'glass.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'cutlery-spoon',
          subcategory_name: 'Spoon',
          icon: 'spoon.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'cutlery-fork',
          subcategory_name: 'Fork',
          icon: 'fork.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'cutlery-chopstick',
          subcategory_name: 'Chopstick',
          icon: 'chopsticks.svg',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'cutlery-knife',
          subcategory_name: 'Knife',
          icon: 'knife.png',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'cutlery-straw',
          subcategory_name: 'Straw',
          icon: 'drinking-straw.svg',
          price_flag: 0,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
      ],
      status: 1,
    },
    {
      category_id: 'water',
      category_name: 'Water',
      icon: 'glass.png',
      subcategories: [
        {
          subcategory_id: 'water-regular',
          subcategory_name: 'Regular Water',
          icon: 'glass.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'water-mineral',
          subcategory_name: 'Mineral Water',
          icon: 'water.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'water-hot',
          subcategory_name: 'Hot Water',
          icon: 'water-1.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'water-lemon',
          subcategory_name: 'Lemon Water',
          icon: 'glass.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'water-filtered',
          subcategory_name: 'Filtered Water',
          icon: 'glass.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'water-ice',
          subcategory_name: 'Ice Water',
          icon: 'glass.png',
          price_flag: 1,
          quantity_flag: 1,
          price: 0,
          status: 1,
        },
      ],
      status: 1,
    },
    {
      category_id: 'sauces',
      category_name: 'Sauces',
      icon: 'sauces.png',
      subcategories: [
        {
          subcategory_id: 'sauces-tomato',
          subcategory_name: 'Tomato Sauce',
          icon: 'tomato-ketchup.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-alfredo',
          subcategory_name: 'Alfredo',
          icon: '',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-pesto',
          subcategory_name: 'Pesto Sauce',
          icon: 'pesto-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-marinara',
          subcategory_name: 'Marinara',
          icon: '',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-bbq',
          subcategory_name: 'Barbeque Sauce',
          icon: 'bbq-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-chilli',
          subcategory_name: 'Chilli Sauce',
          icon: 'chilli-sauce.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-salsa',
          subcategory_name: 'Salsa',
          icon: '',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-garlic',
          subcategory_name: 'Garlic Sauce',
          icon: 'garlic-sauce.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-mustard',
          subcategory_name: 'Mustard Sauce',
          icon: 'mustard-1.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-mayo',
          subcategory_name: 'Mayonnaise',
          icon: 'mayonnaise-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-tamarind',
          subcategory_name: 'Tamarind',
          icon: 'imli-chatni.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-mint',
          subcategory_name: 'Mint Sauce',
          icon: 'mint-chatni.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-tobasco',
          subcategory_name: 'Tobasco',
          icon: 'tobasco.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-coconut-chutney',
          subcategory_name: 'Coconut chutney',
          icon: 'coconut-chatni.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-coriander-chutney',
          subcategory_name: 'Coriander chutney',
          icon: 'coriander-chatni.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-samber',
          subcategory_name: 'Samber',
          icon: 'Samber.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'sauces-sriranha-mayo',
          subcategory_name: 'Sriracha Mayo',
          icon: 'sriracha-mayo.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'sauces-duck',
          subcategory_name: 'Duck Sauce',
          icon: 'duck-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'sauces-teriyaki',
          subcategory_name: 'Teriyaki Sauce',
          icon: 'teriyaki-sauce.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
      ],
      status: 1,
    },
    {
      category_id: 'condiments',
      category_name: 'Condiments',
      icon: '',
      subcategories: [
        {
          subcategory_id: 'condiments-salt',
          subcategory_name: 'Salt',
          icon: 'salt.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'condiments-pepper',
          subcategory_name: 'Pepper',
          icon: 'pepper-1.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'condiments-oregano',
          subcategory_name: 'Oregano',
          icon: '',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'condiments-chilli-flakes',
          subcategory_name: 'Chilli Flakes',
          icon: 'salt.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 0,
        },
        {
          subcategory_id: 'condiments-parmesan-cheese',
          subcategory_name: 'Parmesan Cheese',
          icon: 'parmesan-cheese.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'condiments-parmesan-cheese',
          subcategory_name: 'Parmesan Cheese',
          icon: 'parmesan-cheese.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
      ],
      status: 1,
    },
    {
      category_id: 'napkin',
      category_name: 'Napkin',
      icon: 'napkin.png',
      subcategories: [],
      status: 0,
    },
    {
      category_id: 'call-server',
      category_name: 'Call the Server',
      icon: 'waiter.png',
      subcategories: [],
      status: 1,
    },
    {
      category_id: 'wifi-password',
      category_name: 'Wifi Password',
      icon: 'wifi-signal.png',
      ssid: '',
      password: '',
      subcategories: [],
      status: 0,
    },
    {
      category_id: 'smoking-accessories',
      category_name: 'Smoking',
      icon: 'smoking-cat.png',
      subcategories: [
        {
          subcategory_id: 'smoking-ashtray',
          subcategory_name: 'Ashtray',
          icon: 'ashtray.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'smoking-lighter',
          subcategory_name: 'Lighter',
          icon: 'lighter.png',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
      ],
      status: 1,
    },
    {
      category_id: 'drink',
      category_name: 'Drink',
      icon: 'soft-drink.svg',
      subcategories: [
        {
          subcategory_id: 'drink-water',
          subcategory_name: 'Water',
          icon: 'drink-water.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'drink-soup',
          subcategory_name: 'Soup',
          icon: 'drink-soup.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
        {
          subcategory_id: 'drink-tea',
          subcategory_name: 'Tea',
          icon: 'drink-tea.svg',
          price_flag: 0,
          quantity_flag: 0,
          price: 0,
          status: 1,
        },
      ],
      status: 1,
    },
  ],
  discount: [15, 10, 8],
  preparation_time: 20,
  restaurant_open_days: [
    ['1639329894782Break_fast'],
    [],
    ['1639329894782Break_fast'],
    ['1639329894782Break_fast'],
    ['1639329894782Break_fast'],
    ['1639329894782Break_fast'],
    ['1639329894782Break_fast'],
  ],
  config_timings: [
    {
      timing: [540, 1260],
      name: 'Dinner',
      id: '1665647247370Dinner',
    },
  ],
  time_zone: 'Asia/Kuala_Lumpur',
  next_open_epoch: 1672675200,
  working_days: [
    {
      day: 0,
      time: [0, 1440],
    },
    {
      day: 1,
      time: [0, 1440],
    },
    {
      day: 2,
      time: [0, 1440],
    },
    {
      day: 3,
      time: [0, 1440],
    },
    {
      day: 4,
      time: [0, 1440],
    },
    {
      day: 5,
      time: [0, 1440],
    },
    {
      day: 6,
      time: [0, 1440],
    },
  ],
  mall: 'empress',
  foodcourt: 'empress',
  sub_domain: 'empress',
  addons: [],
  country_code: 'MY',
  curr_sym: 'RM',
  emails: {
    cm: ['ashutosh.kumar@easyeat.ai', 'admin@easyeat.ai'],
    pm: ['ashutosh.kumar@easyeat.ai'],
    am: ['ashutosh.kumar@easyeat.ai'],
  },
  offline_platforms: [
    {
      country_codes: [],
      id: 'hungry2u',
      order_type: 3,
      name: 'Hungry2U',
      img: 'hungry2u.png',
      status: 1,
      comm_amt: 17,
      comm_typ: 'percentage',
      pkg_applicable: 1,
    },
    {
      country_codes: [],
      id: 'deliver_eat',
      order_type: 3,
      name: 'DeliverEat',
      img: 'delivereat.png',
      status: 1,
      comm_amt: 5,
      comm_typ: 'percentage',
      pkg_applicable: 1,
    },
    {
      country_codes: [],
      id: 'whatsapp',
      order_type: 1,
      name: 'Whatsapp',
      img: 'whatsapp.png',
      status: 1,
      code: '',
      comm_amt: 6,
      comm_typ: 'fixed',
      pkg_applicable: 1,
    },
    {
      country_codes: [],
      id: 'foodpanda',
      name: 'Foodpanda',
      img: 'panda.png',
      order_type: 1,
      comm_amt: 0,
      comm_typ: 'percentage',
      email: 'richiamopetronjitra@gmail.com',
      password: 'c28ca9a15b009bb643388188e56adfd9ad37e6dabf542d099cc59caa1df13cc1',
      rest_id: 'g4vf',
      sync: 1,
    },
    {
      country_codes: [],
      id: 'just_order_today',
      order_type: 1,
      name: 'Just Order Today',
      img: 'just_order_today.png',
      code: '',
      status: 1,
      created_at: 1646322462,
      payment_channel: 'offline_just_order_today',
      comm_amt: 10,
      comm_typ: 'percentage',
      pkg_applicable: 0,
    },
    {
      country_codes: [],
      id: 'airasia',
      order_type: 3,
      name: 'Air Asia Food',
      img: 'airasia.png',
      status: 1,
      code: '',
      comm_amt: 10,
      comm_typ: 'percentage',
      pkg_applicable: 0,
    },
    {
      country_codes: ['MY'],
      id: 'yes_bank',
      order_type: 3,
      name: 'YES Bank',
      img: 'yes_bank.jpg',
      code: '',
      status: 1,
      created_at: 1653621154,
      payment_channel: 'offline_online_pay',
      comm_amt: 20,
      comm_typ: 'percentage',
      pkg_applicable: 1,
    },
    {
      country_codes: ['MY', 'ID'],
      id: 'grab',
      name: 'Grab',
      img: 'grab.png',
      order_type: 1,
      status: 1,
      code: '',
      comm_amt: 0,
      comm_typ: 'percentage',
      pkg_applicable: 0,
      password: '4b121da7cf43ba5a0eafc44ecd5fca48dd6d8c46232426fae88d64938fc55f6a',
      username: 'darnacuisinekotadamansara@gmail.com',
      sync: 1,
    },
    {
      country_codes: ['MY'],
      id: 'cash_bank',
      order_type: 1,
      name: 'Cash Bank',
      img: 'cash_bank.png',
      code: '',
      status: 1,
      created_at: 1653530151,
      payment_channel: 'cash',
      comm_amt: 21,
      comm_typ: 'fixed',
      pkg_applicable: 1,
    },
  ],
  priority: 3,
  pmt_commissions: [
    {
      start_epoch: 0,
      charge: 1.25,
      end_epoch: 1607558400,
    },
    {
      start_epoch: 1607558400,
      charge: 0,
    },
  ],
  tech_charges: [
    {
      id: '123456',
      start_epoch: 1617235200,
      end_epoch: 1664208000,
      user: {
        dine_in: {
          charge_type: 'percent',
          charge: 2,
        },
        delivery: {
          charge_type: 'percent',
          charge: 2,
        },
        pickup: {
          charge_type: 'percent',
          charge: 2,
        },
      },
      pos: {
        dine_in: {
          charge_type: 'percent',
          charge: 3,
        },
        delivery: {
          charge_type: 'percent',
          charge: 3,
        },
        pickup: {
          charge_type: 'percent',
          charge: 3,
        },
      },
      orig_end_epoch: null,
      modified_at: 1664181007,
    },
    {
      user: {
        dine_in: {
          charge_type: 'percent',
          charge: 1,
        },
        delivery: {
          charge_type: 'percent',
          charge: 1,
        },
        pickup: {
          charge_type: 'percent',
          charge: 2,
        },
      },
      pos: {
        dine_in: {
          charge_type: 'percent',
          charge: 2,
        },
        delivery: {
          charge_type: 'percent',
          charge: 2,
        },
        pickup: {
          charge_type: 'percent',
          charge: 2,
        },
      },
      start_epoch: 1664208000,
      end_epoch: 1677513600,
      id: 'm0C5hVYVXp7yjoXp5cwm',
      created_at: 1664181007,
      modified_at: 1677494373,
      orig_end_epoch: null,
    },
    {
      user: {
        dine_in: {
          charge_type: 'percent',
          charge: 1.75,
        },
        delivery: {
          charge_type: 'percent',
          charge: 1,
        },
        pickup: {
          charge_type: 'percent',
          charge: 2,
        },
      },
      pos: {
        dine_in: {
          charge_type: 'percent',
          charge: 2,
        },
        delivery: {
          charge_type: 'percent',
          charge: 2,
        },
        pickup: {
          charge_type: 'percent',
          charge: 2,
        },
      },
      start_epoch: 1677513600,
      end_epoch: null,
      id: 'PvyO6q8EshsWyj06f4Q6',
      created_at: 1677494373,
      modified_at: 1677494373,
    },
  ],
  pg_charges: [
    {
      id: '123456',
      start_epoch: 0,
      end_epoch: 1619625600,
      online: {
        charge_type: 'percent',
        charge: 2,
        fpm_cimb: {
          charge_type: 'percent',
          charge: 0,
          start_epoch: 1617235200,
          end_epoch: 1625097599,
          valid_from: '01 Apr 2021',
          valid_to: '01 Jul 2021',
        },
        boost: {
          start_epoch: 1617235200,
          end_epoch: 1625097599,
          charge_type: 'percent',
          charge: 1,
          valid_from: '01 Apr 2021',
          valid_to: '01 Jul 2021',
        },
      },
      offline: {
        charge_type: 'percent',
        charge: 1,
      },
    },
    {
      online: {
        netbanking: {
          start_epoch: 1619712000,
          end_epoch: null,
          valid_from: '30 Apr 2021',
          valid_to: 'Infinity',
          charges: [
            {
              charge: 5,
              charge_type: 'percent',
            },
          ],
        },
        charges: [
          {
            charge: 2,
            charge_type: 'percent',
          },
        ],
      },
      offline: {
        charges: [
          {
            charge: 0,
            charge_type: 'percent',
          },
        ],
      },
      start_epoch: 1619712000,
      end_epoch: 1664208000,
      orig_end_epoch: null,
      modified_at: 1664181007,
    },
    {
      online: {
        charges: [
          {
            charge_type: 'percent',
            charge: 0,
          },
        ],
        netbanking: {
          charges: [
            {
              charge: 5,
              charge_type: 'percent',
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
      },
      offline: {
        charges: [
          {
            charge_type: 'percent',
            charge: 0,
          },
        ],
      },
      start_epoch: 1664208000,
      end_epoch: 1664208000,
      id: 'iOOnhviZb1gjVtKvTy5h',
      created_at: 1664181007,
      modified_at: 1664181201,
      orig_end_epoch: null,
    },
    {
      online: {
        charges: [
          {
            charge_type: 'percent',
            charge: 0,
          },
        ],
      },
      offline: {
        charges: [
          {
            charge_type: 'percent',
            charge: 0,
          },
        ],
      },
      start_epoch: 1664208000,
      end_epoch: 1664208000,
      id: 'ch3DpVLZ3m6fjFNze2eo',
      created_at: 1664181201,
      modified_at: 1664181227,
      orig_end_epoch: null,
    },
    {
      online: {
        charges: [
          {
            charge_type: 'percent',
            charge: 0,
          },
        ],
        credit: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 1,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        credit20: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_amb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 2,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_hlb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 1,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_bimb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 1.5,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_ocbc: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_uob: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 2,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_rhb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_cimbclicks: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_bsn: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_hsbc: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_pbb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_kfh: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_abb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_bmmb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_abmb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_mb2u: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_scb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        fpx_bkrm: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        BOOST: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        GrabPay: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        'TNG-EWALLET': {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
        ShopeePay: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1664208000,
          end_epoch: null,
          valid_from: '27 Sep 2022',
          valid_to: 'Infinity',
        },
      },
      offline: {
        charges: [
          {
            charge_type: 'percent',
            charge: 0,
          },
        ],
      },
      start_epoch: 1664208000,
      end_epoch: 1677513600,
      id: 'iwkT3wV2C6pYMbxgr5t8',
      created_at: 1664181227,
      modified_at: 1677494373,
      orig_end_epoch: null,
    },
    {
      online: {
        charges: [
          {
            charge_type: 'percent',
            charge: 0,
          },
        ],
        credit: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 1,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        credit20: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_amb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 2,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_hlb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 1,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_bimb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 1.5,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_ocbc: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_uob: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 2,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_rhb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_cimbclicks: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_bsn: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_hsbc: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_pbb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_kfh: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_abb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_bmmb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_abmb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_mb2u: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_scb: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        fpx_bkrm: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        BOOST: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        GrabPay: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        'TNG-EWALLET': {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
        ShopeePay: {
          charges: [
            {
              charge_type: 'flat',
              charge: 0,
            },
            {
              charge_type: 'percent',
              charge: 0,
            },
          ],
          start_epoch: 1677513600,
          end_epoch: null,
        },
      },
      offline: {
        charges: [
          {
            charge_type: 'percent',
            charge: 0,
          },
        ],
      },
      start_epoch: 1677513600,
      end_epoch: null,
      id: 'e68y3VXDAoLUh5BjkT1d',
      created_at: 1677494373,
      modified_at: 1677494373,
    },
  ],
  promo_charges: [
    {
      id: '123456',
      start_epoch: 0,
      end_epoch: 1619625600,
      limit: 5000,
      tech_charges: {
        user: {
          dine_in: {
            charge_type: 'percent',
            charge: 2,
          },
          delivery: {
            charge_type: 'percent',
            charge: 2,
          },
          pickup: {
            charge_type: 'percent',
            charge: 2,
          },
        },
        pos: {},
      },
      pg_charges: {
        online: {
          charge_type: 'percent',
          charge: 2,
          net_banking: {
            charge_type: 'percent',
            charge: 2,
          },
          credit_card: {},
          wallet: {},
          fpm_amb: {
            charge_type: 'percent',
            charge: 2,
          },
        },
        offline: {
          charge_type: 'percent',
          charge: 2,
        },
      },
      promo_id: 'q1LALhQrImJv1J7Fka8R',
    },
    {
      limit: 15000,
      tech_charges: {
        user: {
          dine_in: {
            charge_type: 'percent',
            charge: 0,
          },
          delivery: {
            charge_type: 'percent',
            charge: 0,
          },
          pickup: {
            charge_type: 'percent',
            charge: 0,
          },
        },
        pos: {
          dine_in: {
            charge_type: 'percent',
            charge: 0,
          },
          delivery: {
            charge_type: 'percent',
            charge: 0,
          },
          pickup: {
            charge_type: 'percent',
            charge: 0,
          },
        },
      },
      pg_charges: {
        online: {
          charge_type: 'percent',
          charge: 0,
        },
        offline: {
          charge_type: 'percent',
          charge: 0,
        },
      },
      start_epoch: 1622304000,
      end_epoch: 1619702382,
      orig_end_epoch: 1622390399,
      promo_id: '8MOZgq0jAFSMI5oNnmIR',
    },
    {
      limit: null,
      tech_charges: {
        user: {
          dine_in: {
            charge_type: 'percent',
            charge: 1,
          },
          delivery: {
            charge_type: 'percent',
            charge: 4,
          },
          pickup: {
            charge_type: 'percent',
            charge: 1,
          },
        },
        pos: {
          dine_in: {
            charge_type: 'percent',
            charge: 1,
          },
          delivery: {
            charge_type: 'percent',
            charge: 1,
          },
          pickup: {
            charge_type: 'percent',
            charge: 1,
          },
        },
      },
      pg_charges: {
        online: {
          charges: [
            {
              charge: 1,
              charge_type: 'percent',
            },
          ],
        },
        offline: {
          charges: [
            {
              charge: 1,
              charge_type: 'percent',
            },
          ],
        },
      },
      promo_id: 'QWzpjAreRjIDIxqgcKrQ',
      start_epoch: 1680364800,
      end_epoch: 1681574399,
      created_at: 1680432479,
      updated_at: 1680432479,
    },
  ],
  ee_wallet: {
    amount: 500,
    expiry: 1634237064,
  },
  open_items: {
    def_cat: 'b083a3baa1507b476d2701bf9bbfe424',
    def_subcat: '0255a9b2492e1f36a86c6cb57fcf1f27',
  },
  special_menu: [
    {
      id: '141b108a57506f924d69cfa83b0f74c8f99171b4ce621d8b6457e7a8e73b9c7d',
      sp_id: '1',
      name: 'Chinese New Year Menu',
      img: 'sunday.png',
      bg_img: 'sunday_bg.png',
      description: 'Available for Pre-order now.',
      start_date: '2021-02-01',
      end_date: '2021-04-25',
      status: 1,
    },
    {
      id: '60325b1a732cdc189a20d83a37170d5d5bb468d606c6178643f2d59b23ac4aa8',
      name: 'Eid Special Menu',
      sp_id: '2',
      img: 'eid.jpg',
      bg_img: 'eid_bg.jpg',
      description: 'Eid Special Category',
      start_date: '2021-01-29',
      end_date: '2021-02-25',
      status: 1,
    },
  ],
  settings: {
    marketing: {
      fb_pixel: '4038234622896695',
    },
    print: {
      qty_align: 'l',
      label_format_v2: 1,
      show_item_name_with_variant: 1,
      cash_drawer: 24,
      master_docket: 1,
      master_order_printer: ['192.168.1.200:9100', '192.168.1.210:9100'],
      on_decline: 8,
      on_void_unaccepted: 11,
      on_void_accepted: 11,
      on_void_new_itr: 11,
      on_accept_new_order: 11,
      on_accept_new_itr: 11,
      on_settle: 9,
      on_table_change: 2,
      format_code: null,
      separate_docket: 0,
      void_format_code: null,
      void_separate_docket: 1,
      show_logo: 0,
      print_delay: 0,
      item_align: 'l',
      font_size: 'm',
      on_accept_enabled: 1,
      void_enabled: 1,
      enabled: 1,
      header: {
        prepend: [],
        custom: [],
        append: [],
      },
      footer: ['Thanks for the ordering with us.'],
      inst_font: 'm',
      pmt_mode_in_body: 1,
      post_settle: 11,
      show_op_order_id: 0,
      sname: 1,
      table_no_position: 't',
      uname: 1,
      show_mob: 1,
      cash_mgt_format_override: 0,
      master_counter_list: 1,
      response_format: 1,
      print_bahasa: 0,
      slip_font: {
        bill: 'm',
        counter: 's',
        master_order_list: 's',
        master_docket: 's',
        table_change: 's',
        cash_in_out: 's',
        cash_mgt_report: 's',
      },
      configurable_settings: {
        bill_receipt: {},
        counter_receipt: {
          header_space: 2,
          table: {
            name: 'TABLE NO',
            show: 1,
            section: 'h',
            fs: 'm',
            o_type: 7,
            ft: 'n',
            priority: 1,
          },
          time: {
            name: 'TIME',
            show: 1,
            section: 'h',
            fs: 's',
            o_type: 7,
            ft: 'b',
            priority: 1,
          },
          counter_name: {
            fs: 's',
            ft: 'b',
          },
          order_type: {
            show: 1,
            section: 'h',
            fs: 's',
            o_type: 7,
            ft: 'b',
            priority: 1,
          },
          order_seq: {
            name: 'ORDER NO',
            show: 1,
            section: 'h',
            fs: 's',
            ft: 'n',
            o_type: 7,
            priority: 1,
          },
          invoice_no: {
            name: 'INVOICE NO',
            show: 1,
            section: 'h',
            fs: 's',
            ft: 'b',
            o_type: 1,
            priority: 1,
          },
          pax: {
            name: 'PAX',
            show: 0,
            section: 'h',
            fs: 'm',
            o_type: 7,
            ft: 'n',
            priority: 1,
          },
          date: {
            name: 'DATE',
            show: 1,
            section: 'h',
            fs: 's',
            o_type: 7,
            ft: 'n',
            priority: 1,
          },
          date_time: {
            name: 'BILL DATE',
            show: 1,
            section: 'h',
            fs: 's',
            ft: 'n',
            o_type: 7,
            priority: 1,
          },
          staff_name: {
            name: 'STAFF NAME',
            show: 0,
            section: 'h',
            fs: 's',
            o_type: 7,
            ft: 'n',
            priority: 1,
          },
          customer_name: {
            name: 'CUSTOMER NAME',
            show: 1,
            section: 'h',
            fs: 'm',
            o_type: 7,
            ft: 'n',
            priority: 1,
          },
          customer_phone: {
            name: 'CUSTOMER PHONE',
            show: 1,
            section: 'h',
            fs: 's',
            o_type: 7,
            ft: 'n',
            priority: 1,
          },
          no_of_items: {
            name: 'NUMBER OF ITEMS',
            show: 0,
            section: 'h',
            fs: 's',
            o_type: 7,
            ft: 'n',
            priority: 1,
          },
          item_name: {
            fs: 's',
            ft: 'b',
          },
          variant: {
            fs: 's',
            ft: 'n',
          },
          addon: {
            fs: 's',
            ft: 'n',
          },
          notes: {
            fs: 's',
            ft: 'n',
          },
          allergies: {
            fs: 's',
            ft: 'n',
          },
        },
      },
      split_addon_variant: 0,
      feed_point: 61,
    },
    settlement: {
      enable: 1,
      visible: 1,
    },
    menu: {
      item_code: 31,
      pax: 1,
      item_code_max_len: 2,
      new_variation: 1,
      collapse: 0,
    },
    global: {
      from_mongo: 0,
      is_realm_enabled: 1,
      is_recipe_enabled: 0,
      reprint_enabled: 1,
      show_active_printers: 1,
      is_order_sync: false,
      print_v2_enabled: 1,
      print_debug_messages: 0,
      ring_notification: true,
      print_bahasa: 1,
      no_login_workflow: 0,
      auto_refresh: 0,
      auto_refresh_interval: 2000,
      visible_on_app: 1,
      posItemPriceTKasDinein: 0,
      pos_view: 'm',
      fp_integration: 1,
      loyalty: 0,
      pos: 1,
      void: 1,
      tossed_specific: 1,
      hide_action_button: 0,
      cash_registry: 1,
      edit_commision: 1,
      special_menu: 1,
      lock_screen: 1,
      lock_screen_idle: 3000,
      lock_screen_timeout: 3600,
      split_bill: 1,
      skip_pkg_chrg: 3,
      skip_pkg_chrg_order_type: 7,
      auto_accept: 1,
      auto_accept_sch: 1,
      table_layout: 1,
      delete_order: 1,
      void_item_after_completed: 0,
      gf_integration: 1,
      mark_prepared_sms: 0,
      mark_order_prepared: 1,
      tp_voucher: 1,
      delete_table_floor: 0,
      takeaway_cash_enable: 1,
      multiple_addon: 1,
      enable_schedule_order: 1,
      service_bell_enable: 1,
      cust_info_popup: 1,
      enable_pre_paid_order: 0,
      foodcourt_delivery: 1,
      pre_paid_order: 2,
      item_level_discount: 7,
      use_es_service: 1,
      store_credit_hq_lvl: 0,
      socket_printing: 1,
      whatsapp_notifier_order_status: 1,
      skip_service_chrg: 1,
      custom_order_dashboard: 1,
      offline_partial_payment: 1,
      enable_rest_food_logo: 1,
      disable_add_more_items: 0,
      hide_download_popup: 1,
      force_close_cash_mgt: 0,
      hide_order_image: 0,
      disable_allergy_label: 0,
      enable_server_flow: 1,
      show_food_combiner_logo: 0,
      loyalty_v2: true,
      loyalty_v2_visible_on_pos: 1,
      loyalty_auto_apply: 0,
      is_fp_new_calculation: 0,
      is_gf_new_calculation: 0,
      show_recommendations: 1,
      send_loyalty_sms: 1,
      cust_data_report: 1,
      disable_foodcourt_operation: 0,
    },
    discount: {
      enabled: 1,
      applicable_day: [0, 0, 0, 1, 0, 0, 0],
      custom_percentage_list: [
        {
          id: 1,
          name: '5% off',
          value: '5',
          type: 'discount',
        },
        {
          id: 2,
          name: '10% off',
          value: '10',
          type: 'discount',
        },
        {
          id: 3,
          name: '20% off',
          subname: '(Senior Citizen)',
          value: '20',
          type: 'discount',
        },
      ],
      custom_flat_list: [
        {
          id: 1,
          name: '-RM 5',
          value: '5',
          type: 'flat',
        },
        {
          id: 2,
          name: '-RM 10',
          value: '10',
          type: 'flat',
        },
        {
          id: 3,
          name: '-RM 20',
          value: '20',
          type: 'flat',
        },
      ],
      custom_flatTopup_list: [
        {
          id: 1,
          name: '+RM 5',
          value: '5',
          type: 'flat',
        },
        {
          id: 2,
          name: '+RM 10',
          value: '10',
          type: 'flat',
        },
        {
          id: 3,
          name: '+RM 20',
          value: '20',
          type: 'flat',
        },
      ],
      preset: 1,
    },
    sounds: {
      force_stop_sound: 0,
      repeat: 0,
      selected: 'sound2.wav',
      timeout: 60000,
      notification_sound: 'sound1.wav',
    },
    logo: {
      width: 250,
      height: 250,
      delay: 5,
    },
    delivery: {
      enabled: 1,
      rest_reach_min_time: 10,
      rest_reach_min_time_scheduled: 2,
      car_min_items: 5,
      auto_assign_car: 1,
    },
    login: {
      skip_verification: 1,
      is_whatsapp: 1,
    },
    reports: {
      enable_eod: 1,
      eod_font_size: '6px',
      eod_page_width: '200px',
      eod_printer: '11.11.12.68:9100',
      full_eod: 1,
    },
    hubspot: {
      deal_id: 7359242590,
    },
    referral: {
      enabled: 1,
    },
  },
  quick_notes: [
    {
      id: 'on0qt',
      note: 'qedqecqw',
      visible_to_user: 0,
    },
  ],
  created_at: 1587946893,
  report_timing: [
    {
      name: 'ALL DAY(DEFAULT)',
      id: '1576a',
      timing: [0, 1440],
    },
  ],
  location: {
    lat: 3.07588585009742,
    lon: 101.587342520213,
  },
  voucher_items: {
    v_cat: 'd9e85b37fe092dd28903f127084a28d5478ce3ebb083d64d583bf803d7787b70',
    v_subcat: 'e9bed89fe261852160510f336a53abbff5a56685d97fa8481c18d92fc15bd09f',
  },
  state: 'Selangor',
  pin_code: '40000',
  address_1:
    'LG Floor Da Men Mall USJ, Persiaran Kewajipan, Usj 1, 47600 Subang Jaya, Selangor, Malaysia',
  address_2: 'LG245',
  report_timings: [
    {
      id: 'n42mcsqVBUp3',
      name: 'Shift2',
      start_time: '12:00 AM',
      end_time: '11:59 PM',
      is_default: 0,
      status: 1,
    },
  ],
  delivery_settings: {
    del_fee_concession: {
      status: 1,
      type: null,
      amount: null,
      min_cart_value: 100,
    },
    delivery_type: 2,
    fixed_distance: 10,
    fixed_price: 2,
    self_delivery_limit: {
      delivery_limit: 5,
      status: 1,
    },
    subsequent_price: 1,
  },
  old_fees: {
    id: 'delivery',
    status: 1,
    name: 'Delivery Fee',
    tax: 0,
    data: [
      2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
      21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
    ],
  },
  menu_cover: {
    img: 'jibril-2021-07-20-05-25-33.jpg',
    is_custom: 1,
  },
  last_order_at: 1636738711,
  custom_print: [
    {
      item_id: '15bf2412918542659ee5bcef21f57875',
      count: 4,
    },
    {
      item_id: 'c2b806b56ca043da93ae05337d82464e',
      count: 3,
    },
    {
      item_id: '4e1c1568ecb045fd9176b9134356785b',
      count: 20,
    },
    {
      item_id: 'dc27ace1ab024f4383d3ee81b7635467',
      count: 2,
    },
  ],
  total_rating: 272,
  hq_id: '5a28e2885772410ba5ef29a0f07d9603',
  language: 'en_US',
  restaurant_image: 'c49dee80aeee27ab5e19689fcec88480_1651468102.jpeg',
  cuisine: ['thai', 'chinese'],
  curr_code: 'MYR',
  loyalty_settings_v2: {
    cashback: 10,
    banner_path:
      '{"id":"template-1","type":1,"img":"https://d1xkxcid7icwfl.cloudfront.net/promotion-templates/bg-1.png","img_with_text":"https://d1xkxcid7icwfl.cloudfront.net/promotion-templates/bg-1-text.png","bg_color":"#f8d77b","bottom":{"img1":"https://d1xkxcid7icwfl.cloudfront.net/promotion-templates/menu-1.svg","img2":"https://d1xkxcid7icwfl.cloudfront.net/promotion-templates/order-1.svg","img3":"https://d1xkxcid7icwfl.cloudfront.net/promotion-templates/payment-1.svg"},"properties":{"text1":{"color":"#000000","font-size":"16px","font-weight":"bold","align":"center"},"text2":{"color":"#F75841","font-size":"36px","font-weight":"bold","align":"center"},"text3":{"color":"#000000","font-size":"16px","font-weight":"bold","align":"center"},"text4":{"color":"#000000","font-size":"14px","font-weight":"normal","align":"center"}},"button":{"color":"#6cc433","font-size":"13px","font-weight":"bold"},"country_code":"MY"}',
    order_types: ['DINEIN', 'TAKEAYPICKUP', 'DLEV'],
    visibility: true,
    is_loyalty_active: true,
    min_item_value: 30,
    min_item_value_earning: 30,
    sub_text: 'Welcome to Easy eat',
    heading: '20 OFF',
    order_type_names: {
      DINEIN: 'Dine in',
      TAKEAYPICKUP: 'Pick Up',
      DLEV: 'Delivery',
    },
  },
  print_logo:
    'https://d1xkxcid7icwfl.cloudfront.net/restaurant_image/c49dee80aeee27ab5e19689fcec88480_bw_1668164100.jpeg',
  block_pmt: [
    {
      payment_method: 'OFFLINE-POS',
      channel_id: [
        'offline_fpanda_settle',
        'offline_bigpay',
        'offline_mastercard',
        'offline_grab_settle',
        'offline_grabpay',
        'offline_hungry2u',
        'offline_visa',
        'offline_american_express',
      ],
    },
  ],
  order_status: 4,
  ruid: '082',
  report_email: 'gurasees@easyeat.ai',
  report_period: 1,
  placeId: 'ChIJF_BpPsrB1DsRcReQzOdt5ew',
  third_party_platforms: {
    fmh: {
      version: 2,
    },
    fmhv2: {
      phone_code: null,
      phone_number: null,
    },
  },
  void_item_after_completed: 1,
  lastActiveTime: 1677217329,
  last_active_time: 1681108829,
  reasons: {
    recommendation_off_reason: 'abcd',
    recom_off_reason_updated: '2023-04-11',
  },
};

let order_details = [
  {
    order_id: 'tmx2cWqYBb1659963721',
    order_no: '15831L02',
    user_id: 'e937ed4723d5d874f2813b91603647235ea6c89addae4ff65fd76e55e67f9e0a',
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    restaurant_name: 'Deep Cafe',
    order_status: 3,
    bill_id: '',
    created_at: 1659963721,
    created_mongodate: '2022-08-08T13:02:01.227Z',
    date: '2022-08-08',
    confirmed_at: 0,
    canceled_at: 0,
    mark_prepared_at: 1659963721,
    schedule_confirmed_at: 0,
    estimated_time: 0,
    completed_at: 0,
    table_id: 'a1',
    table_no: '1',
    floor_id: 'a',
    floor_name: 'Ground Section',
    items: [
      {
        itr: 1,
        item_id: 'b757901190b1456cba96e9ae45bb86df',
        item_name: 'Milodino 恐⻰美禄',
        item_quantity: 1,
        item_price: 35,
        original_price: 35,
        discount_per: 0,
        reward_id: '',
        created_at: '1659963721',
        confirmed_at: 1659963721,
        completed_at: '',
        kitchen_counter_id: null,
        kitchen_picked_at: '',
        kitchen_picked_by: '',
        kitchen_time_to_complete: 10,
        item_status: 3,
        order_item_id: 'WTRLXb757901190b1456cba96e9ae45bb86df',
        prepared_at: 1659963721,
        canceled_at: 0,
        void_at: 0,
        declined_at: 0,
        special_note: '',
        decline_reason: [],
        base_qty: 1,
        unit: 'number',
        gvariations: null,
        variation_ids: '',
        addons: [],
        addon_ids: null,
        gvariation_name: '',
        variation_name: '',
        addons_name: '',
        category_id: '4bb9f8d71b5e705aabb714b765fb6fe673471356b4d23e11bf7fa3e42f6cc55f',
        subcategory_id: '23d9405018ff3af0e2eb83c994db7c50ad5e2c560788e77826248feb03ef8f55',
        is_combo_item: 0,
        cmm_id: null,
        hq_id: null,
        order_by: 'MM',
        new_variation_name: '',
        new_addons_name: '',
        combo_items: [],
        open_item: 0,
        item_code: null,
        new_variation_ids: null,
        variant_info: [],
      },
    ],
    special_notes: [],
    allergic_items: [],
    address: '',
    distance: 0,
    order_type: 0,
    delivery_partner: null,
    delivery_assign_type: null,
    address_obj: null,
    platform: 'easyeat',
    pax: 1,
    order_seq: '1-2',
    op_no: null,
    coupon_id: '',
    coupon_name: '',
    reason: null,
    base_roundoff: 0.05,
    auto_assign_car: null,
    user_platform: '',
    country_code: 'MY',
    skip_service_charge_operation: '0',
    skip_packaging_charge_operation: 0,
    op_order_creation_time: '',
    currency: { curr_sym: 'RM', curr_code: 'MYR' },
    discovery_page: 2,
    order_by: 'MM',
    no_enter: '0',
    name: 'easyeat user',
    phone: '187731010715988',
    dial_code: '+60',
    time_epoch: 0,
    scheduled: 0,
    rest_reach_min_time: 2,
    sname: '',
  },
];

let kitchen_details = {
  kitchen_counter_id: 'X6MPxmwbZj62b1883dbfbd3',
};

let kitchen_counter_details = {
  b757901190b1456cba96e9ae45bb86df: [
    {
      kc_id: 'X6MPxmwbZj62b1883dbfbd3',
      counter_name: 'main_course',
      printer_name: '192.168.29.201:9100',
      is_sticker_printer: 1,
      kitchen_counter_id: 'X6MPxmwbZj62b1883dbfbd3',
    },
  ],
};

// let menu_kitchen_counters = {};

// for (let item of order_details[0]['items']) {
//   if (!menu_kitchen_counters[item['item_id']]) {
//     menu_kitchen_counters[item['item_id']] = {};
//   }
//   menu_kitchen_counters[item['item_id']]['kitchen_counter_id'] = 'X6MPxmwbZj62b1883dbfbd3';
// }

let subcat_counters = {
  '23d9405018ff3af0e2eb83c994db7c50ad5e2c560788e77826248feb03ef8f55': [
    {
      kc_id: '6MPxmwbZj62b1883dbfbd',
      counter_name: 'sub category counter',
      printer_name: '192.168.10.100:9100',
      is_sticker_printer: 0,
      kitchen_counter_id: '6MPxmwbZj62b1883dbfbd',
    },
  ],
};

let bill_details = {
  _id: '62f10949a2c9cb6d9207d9f7',
  bill_id: 'qeqxFZK8h71659963721',
  order_id: 'tmx2cWqYBb1659963721',
  payments: [],
  user_id: 'e937ed4723d5d874f2813b91603647235ea6c89addae4ff65fd76e55e67f9e0a',
  restaurant_id: '54de918896774f82bc8a921a25b24d79',
  curr_code: 'MYR',
  fees: [
    { id: 'item_total', fee_name: 'Item Total', fee: 35, tax: 0 },
    { id: 'coupon_discount', fee_name: 'Discount', fee: 0, tax: 0 },
    { id: 'round_off', fee_name: 'Round Off', fee: 0, tax: 0 },
  ],
  item_total: 35,
  tax: 0,
  bill_total: 35,
  savings: 0,
  earnings: 0,
  balance: 35,
  paid: 0,
  date: '2022-08-08',
  timestamp: 1659963721,
};

let cash_mgt_data = [
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    cash_in_drawer: 90,
    active_epoch: 0,
    txn_entries: [],
  },
];

let cash_mgt_entries_data = [
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    txn_id: 'b9a8c96d48934078a5772a4fccfd8865',
    type: 'drawer-kick',
    staff_name: 'Deepanshu',
    amount: null,
    reason: 'Testing',
    created_at: 1662960783,
  },
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    txn_id: 'ceadb48bee7942af98e650b5d7ed990a',
    type: 'drawer-kick',
    staff_name: 'Deepanshu',
    amount: null,
    reason: 'Testing',
    created_at: 1662960761,
  },
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    txn_id: '28dcf626dd474d3db04a5e3a2a9f4817',
    type: 'drawer-kick',
    staff_name: 'Deepanshu',
    amount: null,
    reason: 'Testing',
    created_at: 1662960744,
  },
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    txn_id: 'e427dbea9ffb4a35bf1a3a0a3dece34a',
    type: 'drawer-kick',
    staff_name: 'Deepanshu',
    amount: null,
    reason: 'Testing',
    created_at: 1662960728,
  },
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    txn_id: 'e3afae49c69944048c2f083b0fb2e18d',
    type: 'drawer-kick',
    staff_name: 'Deepanshu',
    amount: null,
    reason: 'Testing',
    created_at: 1662960710,
  },
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    txn_id: 'fdd98158f0d341608be90f974f006d97',
    type: 'cash-out',
    staff_name: 'Deepanshu',
    amount: 10,
    reason: 'Testing',
    created_at: 1662960110,
  },
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    txn_id: 'ea4b497f69f340d18b82025b6c5bcef6',
    type: 'open-cashier',
    staff_name: 'Deepanshu',
    amount: 100,
    reason: 'opening cash float',
    created_at: 1662960072,
  },
];

let open_cashier_data = [
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    txn_id: 'ea4b497f69f340d18b82025b6c5bcef6',
    type: 'open-cashier',
    staff_name: 'Deepanshu',
    amount: 100,
    reason: 'opening cash float',
    created_at: 1662960072,
  },
];

let close_cashier_data = [
  {
    restaurant_id: '54de918896774f82bc8a921a25b24d79',
    txn_id: '41c6d0f9f16b4a71b547200ccbdcedd7',
    type: 'close-cashier',
    staff_name: 'System',
    amount: 232,
    reason: 'Eod Update',
    created_at: 1662660003,
  },
];

let cashier_report_data = [
  {
    restaurant_id: 'c49dee80aeee27ab5e19689fcec88480',
    date: '2023-04-13',
    open_cashier_date_time: '13/04/2023 09:01 PM',
    open_cashier_epoch: 1681390887,
    close_cashier_date_time: '13/04/2023 09:01 PM',
    close_cashier_epoch: 1681390913,
    close_cashier_txn_id: 'c56eeea5aa824abdbee3825c81b5bef6',
    opening_cash_float: '342.00',
    total_cash_in: '0.00',
    cash_in_sales: '0.00',
    cash_in_others: '0.00',
    total_cash_out: '0.00',
    net_cash_balance: '0.00',
    expected_cash_in_drawer: '342.00',
    actual_cash_in_drawer: '362.00',
    excess_short_cash: '20.00',
    cash_count_enabled: 1,
    denominations: [
      {
        key: 'zero_point_zero_five',
        value: '0.05',
        count: 0,
      },
      {
        key: 'zero_point_ten',
        value: '0.10',
        count: 0,
      },
      {
        key: 'zero_point_twenty',
        value: '0.20',
        count: 0,
      },
      {
        key: 'zero_point_fifty',
        value: '0.50',
        count: 0,
      },
      {
        key: 'one',
        value: '1.00',
        count: 2,
      },
      {
        key: 'five',
        value: '5.00',
        count: 0,
      },
      {
        key: 'ten',
        value: '10.00',
        count: 0,
      },
      {
        key: 'twenty',
        value: '20.00',
        count: 3,
      },
      {
        key: 'fifty',
        value: '50.00',
        count: 0,
      },
      {
        key: 'hundred',
        value: '100.00',
        count: 3,
      },
    ],
    staff_name: 'alt',
    close_cashier: 'APPROVED BY JIBRIL MERCHANT MANAGER',
    created_at: 1681390913,
  },
];

console.log(
  JSON.stringify(
    generateCashierReportData(
      rest_details,
      1,
      order_details,
      [bill_details],
      open_cashier_data,
      close_cashier_data,
      cash_mgt_data,
      cash_mgt_entries_data,
      'report',
      'MY',
      'en-US',
      true,
      cashier_report_data,
    ),
  ),
);
