const { generatePrintData } = require('../src/printData');

// let rest_details = {
//   _id: { $oid: '629f1445c204870048f0b9e7' },
//   id: '54de918896774f82bc8a921a25b24d79',
//   name: 'Deep Cafe',
//   nameid: 'deepcafe',
//   logo: '',
//   state: '',
//   phone: '1234567089',
//   dial_code: '++91',
//   email: 'altaf.hussain@easyeat.ai',
//   pin_code: '122001',
//   country: 'Malaysia',
//   address: 'KGF Tower, Sector-28',
//   location: { lat: 3.07588585009742, lon: 101.587342520213 },
//   is_dummy_outlet: false,
//   printer: '192.168.29.201:9100',
//   city: 'Gurgaon',
//   discount: [0, 0, 0],
//   restaurant_certificates: [],
//   account_details: [],
//   tax_details: [],
//   fee: [],
//   preparation_time: [],
//   geo_location: { type: 'Point', coordinates: [101.587342520213, 3.07588585009742] },
//   next_open_epoch: 0,
//   base_roundoff: 0.05,
//   on_whatsapp: 1,
//   delivery_time: 20,
//   type: 3,
//   deliverylimit: 50,
//   status: 1,
//   mall: '',
//   emails: { cm: ['deepcafe@easyeat.ai'], pm: ['deepcafe@easyeat.ai'], am: ['deepcafe@easyeat.ai'] },
//   config_timings: [{ id: 'f', name: 'FullDay', timing: [480, 1320] }],
//   rest_timings: {
//     DINING: [
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//     ],
//     DELIVERY: [
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//     ],
//     TAKEAWAY: [
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//       { is_enabled: true, slot: [{ start: 480, end: 1320 }] },
//     ],
//   },
//   restaurant_open_days: [['f'], ['f'], ['f'], ['f'], ['f'], ['f'], ['f']],
//   time_zone: 'Asia/Jakarta',
//   fees: [
//     {
//       id: 'delivery',
//       status: 1,
//       name: 'Delivery Fee',
//       tax: 0,
//       data: [
//         5, 5, 5, 5.4, 6, 6.6, 7.2, 7.9, 8.6, 9.3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22,
//         24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
//         70, 72, 74, 76, 78, 80,
//       ],
//     },
//   ],
//   addons: [],
//   delivery_partner: [
//     { partner_id: '1', partner_name: 'mrspeedy', priority: 0 },
//     { partner_id: '2', partner_name: 'lalamove', priority: 2 },
//   ],
//   company_name: '',
//   cuisine: [],
//   pref_filter: [],
//   bnk_nm: '',
//   bnk_accn: '',
//   acc_holder_nm: '',
//   services: [
//     {
//       category_id: 'cutlery',
//       category_name: 'Cutlery',
//       icon: 'cutlery-1.png',
//       subcategories: [
//         {
//           subcategory_id: 'cutlery-plate',
//           subcategory_name: 'Plate',
//           icon: 'dish_plate.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-bowl',
//           subcategory_name: 'Bowl',
//           icon: 'bowl-1.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-glass',
//           subcategory_name: 'Glass',
//           icon: 'glass.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-spoon',
//           subcategory_name: 'Spoon',
//           icon: 'spoon.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-fork',
//           subcategory_name: 'Fork',
//           icon: 'fork.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-chopstick',
//           subcategory_name: 'Chopstick',
//           icon: 'chopsticks.svg',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-knife',
//           subcategory_name: 'Knife',
//           icon: 'knife.png',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'cutlery-straw',
//           subcategory_name: 'Straw',
//           icon: 'drinking-straw.svg',
//           price_flag: 0,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//     {
//       category_id: 'water',
//       category_name: 'Water',
//       icon: 'glass.png',
//       subcategories: [
//         {
//           subcategory_id: 'water-regular',
//           subcategory_name: 'Regular Water',
//           icon: 'glass.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-mineral',
//           subcategory_name: 'Mineral Water',
//           icon: 'water.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-hot',
//           subcategory_name: 'Hot Water',
//           icon: 'water-1.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-lemon',
//           subcategory_name: 'Lemon Water',
//           icon: 'glass.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-filtered',
//           subcategory_name: 'Filtered Water',
//           icon: 'glass.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'water-ice',
//           subcategory_name: 'Ice Water',
//           icon: 'glass.png',
//           price_flag: 1,
//           quantity_flag: 1,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//     {
//       category_id: 'sauces',
//       category_name: 'Sauces',
//       icon: 'sauces.png',
//       subcategories: [
//         {
//           subcategory_id: 'sauces-tomato',
//           subcategory_name: 'Tomato Sauce',
//           icon: 'tomato-ketchup.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-alfredo',
//           subcategory_name: 'Alfredo',
//           icon: '',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-pesto',
//           subcategory_name: 'Pesto Sauce',
//           icon: 'pesto-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-marinara',
//           subcategory_name: 'Marinara',
//           icon: '',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-bbq',
//           subcategory_name: 'Barbeque Sauce',
//           icon: 'bbq-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-chilli',
//           subcategory_name: 'Chilli Sauce',
//           icon: 'chilli-sauce.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-salsa',
//           subcategory_name: 'Salsa',
//           icon: '',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-garlic',
//           subcategory_name: 'Garlic Sauce',
//           icon: 'garlic-sauce.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-mustard',
//           subcategory_name: 'Mustard Sauce',
//           icon: 'mustard-1.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-mayo',
//           subcategory_name: 'Mayonnaise',
//           icon: 'mayonnaise-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-tamarind',
//           subcategory_name: 'Tamarind',
//           icon: 'imli-chatni.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-mint',
//           subcategory_name: 'Mint Sauce',
//           icon: 'mint-chatni.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-tobasco',
//           subcategory_name: 'Tobasco',
//           icon: 'tobasco.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-coconut-chutney',
//           subcategory_name: 'Coconut chutney',
//           icon: 'coconut-chatni.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-coriander-chutney',
//           subcategory_name: 'Coriander chutney',
//           icon: 'coriander-chatni.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-samber',
//           subcategory_name: 'Samber',
//           icon: 'Samber.svg',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-sriranha-mayo',
//           subcategory_name: 'Sriracha Mayo',
//           icon: 'sriracha-mayo.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-duck',
//           subcategory_name: 'Duck Sauce',
//           icon: 'duck-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'sauces-teriyaki',
//           subcategory_name: 'Teriyaki Sauce',
//           icon: 'teriyaki-sauce.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//     {
//       category_id: 'condiments',
//       category_name: 'Condiments',
//       icon: '',
//       subcategories: [
//         {
//           subcategory_id: 'condiments-salt',
//           subcategory_name: 'Salt',
//           icon: 'salt.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-pepper',
//           subcategory_name: 'Pepper',
//           icon: 'pepper-1.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-oregano',
//           subcategory_name: 'Oregano',
//           icon: '',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-chilli-flakes',
//           subcategory_name: 'Chilli Flakes',
//           icon: 'salt.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-parmesan-cheese',
//           subcategory_name: 'Parmesan Cheese',
//           icon: 'parmesan-cheese.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'condiments-parmesan-cheese',
//           subcategory_name: 'Parmesan Cheese',
//           icon: 'parmesan-cheese.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//     {
//       category_id: 'napkin',
//       category_name: 'Napkin',
//       icon: 'napkin.png',
//       subcategories: [],
//       status: 0,
//     },
//     {
//       category_id: 'call-server',
//       category_name: 'Call the Server',
//       icon: 'waiter.png',
//       subcategories: [],
//       status: 0,
//     },
//     {
//       category_id: 'wifi-password',
//       category_name: 'Wifi Password',
//       icon: 'wifi-signal.png',
//       ssid: '',
//       password: '',
//       subcategories: [],
//       status: 0,
//     },
//     {
//       category_id: 'smoking-accessories',
//       category_name: 'Smoking',
//       icon: 'smoking-cat.png',
//       subcategories: [
//         {
//           subcategory_id: 'smoking-ashtray',
//           subcategory_name: 'Ashtray',
//           icon: 'ashtray.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//         {
//           subcategory_id: 'smoking-lighter',
//           subcategory_name: 'Lighter',
//           icon: 'lighter.png',
//           price_flag: 0,
//           quantity_flag: 0,
//           price: 0,
//           status: 0,
//         },
//       ],
//       status: 0,
//     },
//   ],
//   filters: [
//     { id: 'veg', name: 'Veg', 'filter-type': 'preference', status: 0 },
//     { id: 'non-veg', name: 'Non Veg', 'filter-type': 'preference', status: 0 },
//     { id: 'halal', name: 'Halal', 'filter-type': 'preference', status: 0 },
//     { id: 'kosher', name: 'Kosher', 'filter-type': 'preference', status: 0 },
//     { id: 'gluten-free', name: 'Gluten Free', 'filter-type': 'preference', status: 0 },
//     { id: 'vegan', name: 'Vegan', 'filter-type': 'preference', status: 0 },
//     { id: 'price-5', name: '5', currency: 'MYR', 'filter-type': 'price', status: 0, value: 5 },
//     { id: 'price-10', name: '10', currency: 'MYR', 'filter-type': 'price', status: 0, value: 10 },
//     { id: 'price-15', name: '15', currency: 'MYR', 'filter-type': 'price', status: 0, value: 15 },
//     { id: 'price-20', name: '20', currency: 'MYR', 'filter-type': 'price', status: 0, value: 20 },
//     { id: 'price-30', name: '30', currency: 'MYR', 'filter-type': 'price', status: 0, value: 30 },
//     { id: 'price-40', name: '40', currency: 'MYR', 'filter-type': 'price', status: 0, value: 40 },
//     { id: 'price-50', name: '15', currency: 'MYR', 'filter-type': 'price', status: 0, value: 15 },
//     { id: 'available', name: 'available', 'filter-type': 'preference', status: 1, selected: true },
//   ],
//   offline_platforms: [
//     {
//       id: 'grab',
//       name: 'Grab',
//       img: 'grab.png',
//       order_type: 1,
//       comm_amt: 0,
//       comm_typ: 'percentage',
//     },
//     {
//       id: 'foodpanda',
//       name: 'Foodpanda',
//       img: 'panda.png',
//       order_type: 1,
//       comm_amt: 0,
//       comm_typ: 'percentage',
//     },
//     {
//       id: 'others',
//       name: 'Others',
//       img: 'others_platform.svg',
//       order_type: 1,
//       comm_amt: 0,
//       comm_typ: 'percentage',
//     },
//   ],
//   settings: {
//     print: {
//       enabled: 1,
//       print_bahasa: 0,
//       cash_drawer: 0,
//       master_docket: 0,
//       on_decline: 0,
//       on_void_unaccepted: 2,
//       on_void_accepted: 2,
//       on_void_new_itr: 2,
//       on_accept_new_order: 2,
//       on_accept_new_itr: 2,
//       on_settle: 1,
//       on_table_change: 2,
//       format_code: null,
//       separate_docket: 0,
//       void_format_code: null,
//       void_separate_docket: 0,
//       show_logo: 0,
//       print_delay: 3000,
//       item_align: 'l',
//       font_size: 'l',
//       on_accept_enabled: 1,
//       void_enabled: 0,
//       footer: ['thank you', 'visit again.'],
//       header: { custom: ['Deep Cafe', 'KGF Tower, Sector-29'] },
//       cash_mgt_format_override: 0,
//       inst_font: 's',
//       pmt_mode_in_body: 0,
//       post_settle: 2,
//       response_format: 1,
//       show_op_order_id: 2,
//       slip_font: {
//         bill: 'm',
//         counter: 'm',
//         master_order_list: 'm',
//         master_docket: 'm',
//         table_change: 'm',
//         cash_in_out: 'm',
//         cash_mgt_report: 'm',
//       },
//       sname: 0,
//       table_no_position: 't',
//       uname: 0,
//     },
//     settlement: { enable: 1, visible: 1 },
//     login: { skip_verification: 0 },
//     reports: {
//       enable_eod: 1,
//       eod_printer: 'default',
//       eod_font_size: '6px',
//       eod_page_width: '130px',
//       full_eod: 0,
//     },
//     global: {
//       hide_order_image: 1,
//       visible_on_app: 1,
//       table_layout: 1,
//       cash_registry: 1,
//       fp_integration: 1,
//       no_login_workflow: 1,
//       enable_rest_food_logo: 0,
//       gf_integration: 1,
//       auto_accept: 7,
//       auto_accept_sch: 7,
//       cust_info_popup: 0,
//       hide_download_popup: 0,
//       disable_add_more_items: 0,
//       skip_service_chrg: 0,
//       use_es_service: 1,
//       custom_order_dashboard: 1,
//       mark_order_prepared: 1,
//       multiple_addon: 1,
//       hide_action_button: 1,
//       split_bill: 1,
//       void: 1,
//       whatsapp_notifier_order_status: 0,
//       enable_server_flow: 0,
//       disable_allergy_label: 0,
//       delete_order: 0,
//       edit_commision: 1,
//       enable_pre_paid_order: 1,
//       lock_screen: 0,
//       lock_screen_idle: 300,
//       lock_screen_timeout: 20,
//       loyalty: 0,
//       mark_prepared_sms: 0,
//       pos: 1,
//       posItemPriceTKasDinein: 0,
//       pos_view: 'l',
//       service_bell_enable: 1,
//       skip_pkg_chrg: 0,
//       skip_pkg_chrg_order_type: 4,
//       special_menu: 0,
//       takeaway_cash_enable: 0,
//       tossed_specific: 0,
//       void_item_after_completed: 0,
//       print_v2_enabled: 1,
//       print_debug_messages: 1,
//       auto_refresh: 0,
//       pre_paid_order: 2,
//     },
//     menu: { new_variation: 1, item_code: 5, item_code_max_len: 3, pax: 0, cmm_enable: 1 },
//     sounds: { repeat: 1, selected: 'sound1.wav', timeout: 15000 },
//   },
//   open_items: {
//     def_cat: 'feaf966247764be4807e295b57c42d2b',
//     def_subcat: '743b3c0a88074bddac83bfc69d14d313',
//   },
//   dkick_code: [27, 112, 48, 55, 121],
//   tech_charges: [],
//   pg_charges: [
//     {
//       online: {
//         charges: [{ charge_type: 'percent', charge: 0 }],
//         'credit-card': {
//           charges: [
//             { charge_type: 'flat', charge: 1500 },
//             { charge_type: 'percent', charge: 2.5 },
//           ],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'direct-debit': {
//           charges: [
//             { charge_type: 'flat', charge: 1500 },
//             { charge_type: 'percent', charge: 1.5 },
//           ],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'cimb-direct-debit': {
//           charges: [
//             { charge_type: 'flat', charge: 1500 },
//             { charge_type: 'percent', charge: 1.5 },
//           ],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'bca-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 4500 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'bni-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'bri-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'bsm-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'cimb-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'doku-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'danamon-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'mandiri-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'permata-virtual-account': {
//           charges: [{ charge_type: 'flat', charge: 1800 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'dokuwallet-emoney': {
//           charges: [{ charge_type: 'percent', charge: 1.65 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'ovo-emoney': {
//           charges: [{ charge_type: 'percent', charge: 1.5 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'ovo-open-api': {
//           charges: [{ charge_type: 'percent', charge: 1.5 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         'shopeepay-emoney': {
//           charges: [{ charge_type: 'percent', charge: 1.65 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//         qris: {
//           charges: [{ charge_type: 'percent', charge: 0.7 }],
//           start_epoch: 1659100716,
//           end_epoch: null,
//         },
//       },
//       offline: { charges: [{ charge_type: 'percent', charge: 0 }] },
//       start_epoch: 1659100716,
//       end_epoch: null,
//     },
//   ],
//   block_pmt: [],
//   quick_notes: [
//     { id: '3919716167474954b63646a4d0d27306', note: 'Less Spicy', visible_to_user: 1 },
//     { id: '1cc5ca1cd1554fcb8a4100ce30f9fc07', note: 'alt', visible_to_user: 1 },
//     { id: '8008ad8b28e04eac8cad848ede193ec9', note: 'Alt', visible_to_user: 1 },
//     { id: '19d2320d25644c20bc48035cfa647704', note: 'heLL', visible_to_user: 1 },
//     { id: 'cb567f28651f4bd6b9f6997eabdf1018', note: 'heLLo1', visible_to_user: 1 },
//     { id: 'cd8f8e48c4b740d5ad1f93daa16f2196', note: 'Hello', visible_to_user: 1 },
//     { id: 'b7b6d182e61d4150a1bfb22b71ca9b44', note: 'HOT & SPICY', visible_to_user: 1 },
//   ],
//   country_code: 'MY',
//   curr_code: 'MYR',
//   curr_sym: 'RM',
//   language: 'en_US',
//   created_at: 1654592581,
//   hq_id: '7cc8a0a1bd4c4d2c8993ad1e42ce33c4',
//   default_cuisine_image: 'restaurant_food_image/cuisine/no_cuisine/image.png',
//   promo_charges: [],
//   print_logo: '',
// };

// let order_details = [
//   {
//     _id: '634e87c496626cb5320ae4ca',
//     order_id: '86LMYm5i5r1666090948',
//     order_no: '15831Q4N',
//     user_id: 'ba032a65a4e349dbaa4f94a9eb6ca2920e2cd6c5cf68f807201d34dce1843c47',
//     restaurant_id: '54de918896774f82bc8a921a25b24d79',
//     restaurant_name: 'Deep Cafe',
//     order_status: 3,
//     bill_id: '',
//     created_at: 1666090948,
//     created_mongodate: '2022-10-18T11:02:28.281Z',
//     date: '2022-10-18',
//     confirmed_at: 0,
//     canceled_at: 0,
//     mark_prepared_at: 1666090948,
//     schedule_confirmed_at: 0,
//     estimated_time: 0,
//     completed_at: 0,
//     table_id: 'a1',
//     table_no: '1',
//     floor_id: 'a',
//     floor_name: 'Ground Section',
//     items: [
//       {
//         itr: 1,
//         item_id: '00c4d7b75f7044d095cc63d71d7e7ac2',
//         item_name: 'Kebab Parantha 1',
//         item_quantity: 1,
//         item_price: 46,
//         original_price: 46,
//         discount_per: 0,
//         reward_id: '',
//         created_at: 1666090948,
//         confirmed_at: 1666090948,
//         completed_at: 0,
//         kitchen_counter_id: '',
//         kitchen_picked_at: '',
//         kitchen_picked_by: '',
//         kitchen_time_to_complete: 15,
//         item_status: 3,
//         order_item_id: 'YGpTO00c4d7b75f7044d095cc63d71d7e7ac2',
//         prepared_at: 1666090948,
//         canceled_at: 0,
//         void_at: 0,
//         declined_at: 0,
//         special_note: '',
//         decline_reason: [],
//         grabItemID: '',
//         base_qty: 1,
//         unit: 'number',
//         gvariations: [],
//         variation_ids: '',
//         addons: [],
//         addon_ids: '',
//         gvariation_name: '',
//         variation_name: '',
//         addons_name: '',
//         category_id: '4bb9f8d71b5e705aabb714b765fb6fe673471356b4d23e11bf7fa3e42f6cc55f',
//         subcategory_id: '23d9405018ff3af0e2eb83c994db7c50ad5e2c560788e77826248feb03ef8f55',
//         is_combo_item: 0,
//         cmm_id: '2a1110f7afe74b00b6675313bce0c99c',
//         hq_id: '7cc8a0a1bd4c4d2c8993ad1e42ce33c4',
//         order_by: 'MM',
//         new_variation_name: '',
//         new_addons_name: '',
//         combo_items: [],
//         open_item: 0,
//         item_code: '',
//         new_variation_ids: '',
//         variant_info: [],
//       },
//     ],
//     special_notes: [],
//     allergic_items: [],
//     address: '',
//     distance: 0,
//     order_type: 0,
//     delivery_partner: '',
//     delivery_assign_type: null,
//     address_obj: {},
//     platform: 'easyeat',
//     pax: 0,
//     order_seq: '1-6',
//     op_no: '',
//     coupon_id: '',
//     coupon_name: '',
//     reason: '',
//     base_roundoff: 0.05,
//     auto_assign_car: null,
//     user_platform: '',
//     country_code: 'MY',
//     skip_service_charge_operation: 0,
//     skip_packaging_charge_operation: 0,
//     op_order_creation_time: '',
//     currency: { curr_sym: 'RM', curr_code: 'MYR' },
//     discovery_page: 2,
//     order_by: 'MM',
//     no_enter: 0,
//     name: 'easyeat user',
//     phone: '602332690636016',
//     dial_code: '+60',
//     time_epoch: 0,
//     scheduled: 0,
//     rest_reach_min_time: 2,
//     guests: [
//       {
//         guest_id: 's24PE',
//         guest_name: '',
//         items: [{ order_item_id: 'YGpTO00c4d7b75f7044d095cc63d71d7e7ac2', item_quantity: 1 }],
//       },
//     ],
//   },
//   {
//     _id: '634e87cc2fa3a54e84076438',
//     order_id: 'KH1yyyfKOJ1666090956',
//     order_no: '15831Q4O',
//     user_id: 'b0a07fc75fb2b9db260d5d9d95c801d29cfe196fa5c1984ca0f258f836f115ca',
//     restaurant_id: '54de918896774f82bc8a921a25b24d79',
//     restaurant_name: 'Deep Cafe',
//     order_status: 3,
//     bill_id: '',
//     created_at: 1666090956,
//     created_mongodate: '2022-10-18T11:02:36.909Z',
//     date: '2022-10-18',
//     confirmed_at: 0,
//     canceled_at: 0,
//     mark_prepared_at: 1666090957,
//     schedule_confirmed_at: 0,
//     estimated_time: 0,
//     completed_at: 0,
//     table_id: 'a2',
//     table_no: '2',
//     floor_id: 'a',
//     floor_name: 'Ground Section',
//     items: [
//       {
//         itr: 1,
//         item_id: '00c4d7b75f7044d095cc63d71d7e7ac2',
//         item_name: 'Kebab Parantha 1',
//         item_quantity: 1,
//         item_price: 46,
//         original_price: 46,
//         discount_per: 0,
//         reward_id: '',
//         created_at: 1666090956,
//         confirmed_at: 1666090957,
//         completed_at: 0,
//         kitchen_counter_id: '',
//         kitchen_picked_at: '',
//         kitchen_picked_by: '',
//         kitchen_time_to_complete: 15,
//         item_status: 3,
//         order_item_id: '4tJeb00c4d7b75f7044d095cc63d71d7e7ac2',
//         prepared_at: 1666090957,
//         canceled_at: 0,
//         void_at: 0,
//         declined_at: 0,
//         special_note: '',
//         decline_reason: [],
//         grabItemID: '',
//         base_qty: 1,
//         unit: 'number',
//         gvariations: [],
//         variation_ids: '',
//         addons: [],
//         addon_ids: '',
//         gvariation_name: '',
//         variation_name: '',
//         addons_name: '',
//         category_id: '4bb9f8d71b5e705aabb714b765fb6fe673471356b4d23e11bf7fa3e42f6cc55f',
//         subcategory_id: '23d9405018ff3af0e2eb83c994db7c50ad5e2c560788e77826248feb03ef8f55',
//         is_combo_item: 0,
//         cmm_id: '2a1110f7afe74b00b6675313bce0c99c',
//         hq_id: '7cc8a0a1bd4c4d2c8993ad1e42ce33c4',
//         order_by: 'MM',
//         new_variation_name: '',
//         new_addons_name: '',
//         combo_items: [],
//         open_item: 0,
//         item_code: '',
//         new_variation_ids: '',
//         variant_info: [],
//       },
//     ],
//     special_notes: [],
//     allergic_items: [],
//     address: '',
//     distance: 0,
//     order_type: 0,
//     delivery_partner: '',
//     delivery_assign_type: null,
//     address_obj: {},
//     platform: 'easyeat',
//     pax: 0,
//     order_seq: '1-7',
//     op_no: '',
//     coupon_id: '',
//     coupon_name: '',
//     reason: '',
//     base_roundoff: 0.05,
//     auto_assign_car: null,
//     user_platform: '',
//     country_code: 'MY',
//     skip_service_charge_operation: 0,
//     skip_packaging_charge_operation: 0,
//     op_order_creation_time: '',
//     currency: { curr_sym: 'RM', curr_code: 'MYR' },
//     discovery_page: 2,
//     order_by: 'MM',
//     no_enter: 0,
//     name: 'easyeat user',
//     phone: '444504613440907',
//     dial_code: '+60',
//     time_epoch: 0,
//     scheduled: 0,
//     rest_reach_min_time: 2,
//     guests: [
//       {
//         guest_id: '28bLd',
//         guest_name: '',
//         items: [{ order_item_id: '4tJeb00c4d7b75f7044d095cc63d71d7e7ac2', item_quantity: 1 }],
//       },
//     ],
//   },
// ];

// let bill_details = [
//   {
//     _id: '634e87c496626cb5320ae4cb',
//     bill_id: 'HkTeEMIER01666090948',
//     order_id: '86LMYm5i5r1666090948',
//     payments: [
//       {
//         payment_id: 'ASUnzYBS3g1666090967hbdGgqGGSB',
//         amount: 46,
//         status: 1,
//         payment_method: 'Cash',
//         config_id: '1',
//         epoch: 1666090967,
//         payment_channel: 'cash',
//         transaction_id: '',
//         collected_amt: 46,
//         returned_amt: 0,
//         merged_with: '86LMYm5i5r1666090948',
//         merged_along: ['KH1yyyfKOJ1666090956', '86LMYm5i5r1666090948'],
//         guest_amounts: [{ guest_id: 's24PE', amount: 46 }],
//       },
//     ],
//     user_id: 'ba032a65a4e349dbaa4f94a9eb6ca2920e2cd6c5cf68f807201d34dce1843c47',
//     restaurant_id: '54de918896774f82bc8a921a25b24d79',
//     curr_code: 'MYR',
//     fees: [
//       { id: 'item_total', fee_name: 'Item Total', fee: 46, tax: 0 },
//       { id: 'coupon_discount', fee_name: 'Discount', fee: 0, tax: 0 },
//       { id: 'round_off', fee_name: 'Round Off', fee: 0, tax: 0 },
//     ],
//     item_total: 46,
//     tax: 0,
//     bill_total: 46,
//     savings: 0,
//     earnings: 0,
//     balance: 0,
//     paid: 46,
//     date: '2022-10-18',
//     timestamp: 1666090948,
//     guests: [
//       {
//         guest_id: 's24PE',
//         item_total: 46,
//         bill_total: 46,
//         tax: 0,
//         savings: 0,
//         earnings: 0,
//         balance: 0,
//         paid: 46,
//         fees: [
//           { id: 'item_total', fee_name: 'Item Total', fee: 46, tax: 0 },
//           { id: 'coupon_discount', fee_name: 'Discount', fee: 0, tax: 0 },
//           { id: 'round_off', fee_name: 'Round Off', fee: 0, tax: 0 },
//         ],
//         payment_ids: ['ASUnzYBS3g1666090967hbdGgqGGSB'],
//       },
//     ],
//   },
//   {
//     _id: '634e87cc2fa3a54e84076439',
//     bill_id: 'xejfTQBICk1666090956',
//     order_id: 'KH1yyyfKOJ1666090956',
//     payments: [
//       {
//         payment_id: 'IKWRpx9TZn1666090966MwOkPZXOX5',
//         amount: 46,
//         status: 1,
//         payment_method: 'Cash',
//         config_id: '1',
//         epoch: 1666090966,
//         payment_channel: 'cash',
//         transaction_id: '',
//         collected_amt: 46,
//         returned_amt: 0,
//         merged_with: '86LMYm5i5r1666090948',
//         merged_along: ['KH1yyyfKOJ1666090956', '86LMYm5i5r1666090948'],
//         guest_amounts: [{ guest_id: '28bLd', amount: 46 }],
//       },
//     ],
//     user_id: 'b0a07fc75fb2b9db260d5d9d95c801d29cfe196fa5c1984ca0f258f836f115ca',
//     restaurant_id: '54de918896774f82bc8a921a25b24d79',
//     curr_code: 'MYR',
//     fees: [
//       { id: 'item_total', fee_name: 'Item Total', fee: 46, tax: 0 },
//       { id: 'coupon_discount', fee_name: 'Discount', fee: 0, tax: 0 },
//       { id: 'round_off', fee_name: 'Round Off', fee: 0, tax: 0 },
//     ],
//     item_total: 46,
//     tax: 0,
//     bill_total: 46,
//     savings: 0,
//     earnings: 0,
//     balance: 0,
//     paid: 46,
//     date: '2022-10-18',
//     timestamp: 1666090956,
//     guests: [
//       {
//         guest_id: '28bLd',
//         item_total: 46,
//         bill_total: 46,
//         tax: 0,
//         savings: 0,
//         earnings: 0,
//         balance: 0,
//         paid: 46,
//         fees: [
//           { id: 'item_total', fee_name: 'Item Total', fee: 46, tax: 0 },
//           { id: 'coupon_discount', fee_name: 'Discount', fee: 0, tax: 0 },
//           { id: 'round_off', fee_name: 'Round Off', fee: 0, tax: 0 },
//         ],
//         payment_ids: ['IKWRpx9TZn1666090966MwOkPZXOX5'],
//       },
//     ],
//   },
// ];

// console.log(JSON.stringify(generateBillReceipt(order_details, rest_details, bill_details)));

const bill_details = [
  {
    _id: '62f0af407c6b1964b33f169c',
    balance: 111,
    bill_id: 'IvEpfg0y9J1659940672',
    bill_total: 12.25,
    curr_code: 'MYR',
    date: '2022-08-08',
    earning: null,
    earnings: 0,
    fees: [
      {
        data: null,
        distance: null,
        fee: 12.27,
        fee_name: 'Item Total',
        id: 'item_total',
        partner_fee: null,
        partner_name: null,
        reason: null,
        rest_add: null,
        tax: 0,
        user_add: null,
      },
      {
        data: null,
        distance: null,
        fee: 0,
        fee_name: 'Discount',
        id: 'coupon_discount',
        partner_fee: null,
        partner_name: null,
        reason: null,
        rest_add: null,
        tax: 0,
        user_add: null,
      },
      {
        data: null,
        distance: null,
        fee: -0.02,
        fee_name: 'Round Off',
        id: 'round_off',
        partner_fee: null,
        partner_name: null,
        reason: null,
        rest_add: null,
        tax: 0,
        user_add: null,
      },
    ],
    guests: [],
    is_pc_applied: null,
    item_total: 12.27,
    lock_epoch: 1659973336,
    lock_id: 'd5d1b931-a860-4e7c-8220-49c5bba999ba',
    loyalty_cashback_used: null,
    order_id: 'g9QjbWiTec1659940672',
    paid: 12,
    payments: [
      {
        amount: null,
        collected_amt: null,
        config_id: null,
        epoch: null,
        guest_amounts: [],
        issuer_name: null,
        merged_along: [],
        merged_with: null,
        paid_amount_list: [],
        paid_channel_id_list: [],
        paid_order_list: [],
        paid_paymentid_list: [],
        paid_total: null,
        payment_channel: null,
        payment_id: null,
        payment_method: null,
        returned_amt: null,
        status: null,
        transaction_id: null,
        updated_at: null,
        user_id: null,
      },
      {
        amount: 26.4,
        collected_amt: 28.14,
        config_id: '1',
        epoch: 1234123,
        guest_amounts: [],
        issuer_name: null,
        merged_along: ['cp8jV94Y7N1664775846', 'Iu8cumIHyg1664776915'],
        merged_with: 'Iu8cumIHyg1664776915',
        paid_amount_list: [],
        paid_channel_id_list: [],
        paid_order_list: [],
        paid_paymentid_list: [],
        paid_total: null,
        payment_channel: 'cash',
        payment_id: 'NLzArWmxXn16657465818XPNw2dHH5',
        payment_method: 'Cash',
        returned_amt: 1.74,
        status: 1,
        transaction_id: '',
        updated_at: null,
        user_id: null,
      },
    ],
    restaurant_id: 'c49dee80aeee27ab5e19689fcec88480',
    savings: 1.3600000000000012,
    settlements: [],
    subtotal: null,
    tax: 0,
    timestamp: 1659940672,
    user_id: '597d0748b98aa0be2fb2dd69be329cdc9efe43ec5b70c8100d92d7ae6aa011ef',
  },
  {
    _id: '63528d81a3fd185c2e072330',
    balance: 41.349999999999994,
    bill_id: 'ZiVxC87yQp1666354561',
    bill_total: 41.349999999999994,
    curr_code: 'MYR',
    date: '2022-10-21',
    earning: 0,
    earnings: 0,
    fees: [
      {
        data: null,
        distance: null,
        fee: 41.37,
        fee_name: 'Item Total',
        id: 'item_total',
        partner_fee: null,
        partner_name: null,
        reason: null,
        rest_add: null,
        tax: 0,
        user_add: null,
      },
      {
        data: null,
        distance: null,
        fee: -0.02,
        fee_name: 'Round Off',
        id: 'round_off',
        partner_fee: null,
        partner_name: null,
        reason: null,
        rest_add: null,
        tax: 0,
        user_add: null,
      },
    ],
    guests: [],
    is_pc_applied: 0,
    item_total: 41.37,
    lock_epoch: 0,
    lock_id: '',
    loyalty_cashback_used: false,
    order_id: 'EtTvJFj5O21666354561',
    paid: 0,
    payments: [],
    restaurant_id: 'c49dee80aeee27ab5e19689fcec88480',
    savings: 0,
    settlements: [],
    subtotal: 41.349999999999994,
    tax: 0,
    timestamp: 1666354561,
    user_id: 'b6125fbace20d291a8696604ec72361997f441610e676001dcefd0acb7515665',
  },
];

const order_details = [
  {
    _id: '62f0af407c6b1964b33f169b',
    address: '',
    address_obj: null,
    allergic_items: { categories: [], is_allergy: null },
    analytics: null,
    base_roundoff: 0.05,
    bill_id: '',
    cancel_code: null,
    canceled_at: 0,
    completed_at: 1664782626,
    confirmed_at: 1659940672,
    country_code: 'MY',
    coupon_id: '',
    coupon_name: '',
    created_at: 1659940672,
    currency: { curr_code: 'MYR', curr_sym: 'RM' },
    date: '2022-08-08',
    delete_code: null,
    deleted: null,
    deleted_at: null,
    deleted_reason: null,
    deliver_now: null,
    delivery_assign_at: null,
    delivery_assign_type: null,
    delivery_fee: 0,
    delivery_notes: null,
    delivery_partner: null,
    dial_code: '+60',
    discovery_page: 2,
    distance: 0,
    dtype: null,
    dvalue: null,
    estimated_time: 0,
    fc_name: null,
    fc_order_id: null,
    fc_orders: [],
    finished_at: 1664782626,
    floor_id: 'yq1G5ZVX',
    floor_name: 'First Floor',
    foodcourt: null,
    guests: [],
    is_settled: null,
    items: [],
    mark_prepared_at: 1659973291,
    name: 'easyeat user',
    no_enter: 0,
    op_no: null,
    op_order_creation_time: '',
    order_by: 'MM',
    order_id: 'g9QjbWiTec1659940672',
    order_no: '15849G4E',
    order_seq: '1-6',
    order_status: 1,
    order_type: 0,
    pax: 1,
    pay_with_cash: null,
    phone: '553887943927759',
    platform: 'easyeat',
    primary_fc_order: null,
    reason: null,
    rest_reach_min_time: 2,
    restaurant_id: 'c49dee80aeee27ab5e19689fcec88480',
    restaurant_name: 'Easy Eat Test Restaurant',
    sch_time: null,
    schedule_confirmed_at: 0,
    scheduled: 0,
    skip_packaging_charge_operation: 0,
    skip_service_charge_operation: 0,
    special_notes: [],
    table_id: 'GIwVSgmEX5',
    table_no: 'C8',
    tasks: null,
    time_epoch: 0,
    time_zone: null,
    user_id: '597d0748b98aa0be2fb2dd69be329cdc9efe43ec5b70c8100d92d7ae6aa011ef',
    user_platform: '',
    vehicle_type: null,
    void_items: [
      {
        addon_ids: null,
        addons: [],
        addons_name: '',
        base_qty: 1,
        canceled_at: 0,
        category_id: 'b083a3baa1507b476d2701bf9bbfe424',
        completed_at: 0,
        confirmed_at: 1659940672,
        created_at: 1659940672,
        decline_reason: { decline_item_code: 5, decline_reason: 'Add On Out Of Stock' },
        declined_at: 0,
        discount_per: 10,
        gvariation_name: '',
        gvariations: [],
        is_combo_item: 0,
        item_code: null,
        item_id: 'a1066b1ac537cc3bf0787f4ff59f0cf0',
        item_name: 'Butterscotch Latte',
        item_price: 12.27,
        item_quantity: 7,
        item_status: 3,
        itr: 1,
        kitchen_counter_id: null,
        kitchen_picked_at: '1659973290',
        kitchen_picked_by: '',
        kitchen_time_to_complete: 10,
        new_addons_name: '',
        new_variation_ids: null,
        new_variation_name: '',
        open_item: 0,
        order_by: 'MM',
        order_item_id: 'nt1DBa1066b1ac537cc3bf0787f4ff59f0cf0',
        original_price: 13.63,
        prepared_at: 1659973291,
        reward_id: '',
        special_note: '',
        subcategory_id: '0255a9b2492e1f36a86c6cb57fcf1f27',
        unit: 'number',
        variant_info: [],
        variant_printer: [],
        variation_ids: '',
        variation_name: '',
        void_at: 1664782626,
        voided_by: {
          user_id: 'b6125fbace20d291a8696604ec72361997f441610e676001dcefd0acb7515665',
          user_name: 'Jibril Merchant Manager',
        },
      },
    ],
  },
  {
    _id: '63528d81a3fd185c2e07232f',
    address: '',
    address_obj: null,
    allergic_items: null,
    analytics: null,
    base_roundoff: 0.05,
    bill_id: '',
    cancel_code: 0,
    canceled_at: 0,
    completed_at: 0,
    confirmed_at: 1666354561,
    country_code: 'MY',
    coupon_id: '',
    coupon_name: '',
    created_at: 1666354561,
    currency: { curr_code: 'MYR', curr_sym: 'RM' },
    date: '2022-10-21',
    delete_code: 0,
    deleted: null,
    deleted_at: 0,
    deleted_reason: '',
    deliver_now: 0,
    delivery_assign_at: 0,
    delivery_assign_type: 0,
    delivery_fee: 0,
    delivery_notes: null,
    delivery_partner: '',
    dial_code: '+60',
    discovery_page: 2,
    distance: 0,
    dtype: '',
    dvalue: 0,
    estimated_time: 0,
    fc_name: '',
    fc_order_id: '',
    fc_orders: [],
    finished_at: 0,
    floor_id: 'yq1G5ZVX',
    floor_name: 'First Floor',
    foodcourt: '',
    guests: [],
    is_settled: 0,
    items: [
      {
        addon_ids: '',
        addons: [
          {
            id: null,
            itemids: [],
            max_qty: null,
            name: null,
            price: null,
            qty: null,
            status: null,
          },
        ],
        addons_name: '',
        base_qty: 1,
        canceled_at: 0,
        category_id: '428bd60cb45a529878308b695b4d881ce9624f07d4e3ddb38c80920063f38427',
        cmm_id: '',
        combo_items: [],
        completed_at: 0,
        decline_reason: null,
        confirmed_at: 1666354561,
        created_at: 1666354561,
        declined_at: 0,
        discount_per: 0,
        finished_at: 0,
        gvariation_name: 'Size',
        is_combo_item: 0,
        is_new_variation: 0,
        item_code: '',
        item_discount: null,
        item_id: '30b8714d12834063ab149c1806ddba6b',
        item_image: '',
        item_name: 'Tomato Soup',
        item_price: 6,
        item_quantity: 1,
        item_status: 1,
        itr: 1,
        kitchen_counter_id: null,
        kitchen_picked_at: '',
        kitchen_picked_by: '',
        kitchen_time_to_complete: 10,
        new_addons_name: '',
        new_variation: [],
        new_variation_ids: '|[object Object]',
        new_variation_name: '(Medium )',
        open_item: 0,
        order_by: 'MM',
        order_item_id: 'vcv8t30b8714d12834063ab149c1806ddba6b',
        original_price: 6,
        prepared_at: 0,
        reward_id: '',
        special_note: '',
        subcategory_id: '4ed203d834abb44186ca46031299304e2104bc41fb89303ee55c1f3e81d91ce0',
        unit: 'number',
        variant_info: [
          {
            group_id: 'ca469ad13869450698f2b8d5fcc671e4',
            options: [{ id: '4F3Kt0B7Lg', price: 2 }],
          },
        ],
        variant_printer: [],
        variation_ids: '',
        variation_name: 'Medium ',
        void_at: 0,
      },
      {
        addon_ids:
          '|9bdf1f89c880410399f539272aaf9d68|b910b4db4d064ba5be6f3331dfc12938|5122433c06cc47a498e992a741f5cbde',
        addons: [
          {
            id: null,
            itemids: [],
            max_qty: null,
            name: null,
            price: null,
            qty: null,
            status: null,
          },
        ],
        addons_name: 'gudba x1,Gurbaba x1,Testing Bitch x1',
        base_qty: 1,
        canceled_at: 0,
        category_id: '888cf82400668e3b41226b130f51a9bf7132e0ecbfab81967251363cc8f6fd75',
        cmm_id: '',
        combo_items: [],
        completed_at: 0,
        decline_reason: null,
        confirmed_at: 1666354654,
        created_at: 1666354654,
        declined_at: 0,
        discount_per: 0,
        finished_at: 0,
        gvariation_name: 'Bread|butter',
        is_combo_item: 0,
        is_new_variation: 0,
        item_code: '',
        item_discount: null,
        item_id: 'e8c6352a5696efabde132cd98df35e94',
        item_image: 'thumb_e8c6352a5696efabde132cd98df35e94nX2DX1QU3Xkurosawa.jpeg',
        item_name: 'Kurosawa',
        item_price: 24.87,
        item_quantity: 1,
        item_status: 1,
        itr: 2,
        kitchen_counter_id: null,
        kitchen_picked_at: '',
        kitchen_picked_by: '',
        kitchen_time_to_complete: 15,
        new_addons_name: 'gudba x1, Gurbaba x1, Testing Bitch x1',
        new_variation: [],
        new_variation_ids: '|UxrAHR88Oh|8uJVlr7GTH',
        new_variation_name: '(Corn, butter kaya)',
        open_item: 0,
        order_by: 'MM',
        order_item_id: 'NanGDe8c6352a5696efabde132cd98df35e94',
        original_price: 24.87,
        prepared_at: 0,
        reward_id: '',
        special_note: '',
        subcategory_id: 'd3b51e22e314d35504fa456b09f22e251eaab817cba403ec9c434eb5b6f3070f',
        unit: 'number',
        variant_info: [
          {
            group_id: '561786ea25564e6c881339531a45cb04',
            options: [{ id: 'UxrAHR88Oh', price: 0 }],
          },
          {
            group_id: 'defc993b88b447f58225b44f4605dc47',
            options: [{ id: '8uJVlr7GTH', price: 0.5 }],
          },
        ],
        variant_printer: [],
        variation_ids: '',
        variation_name: 'Corn, butter kaya',
        void_at: 0,
      },
      {
        addon_ids: '',
        addons: [
          {
            id: null,
            itemids: [],
            max_qty: null,
            name: null,
            price: null,
            qty: null,
            status: null,
          },
        ],
        addons_name: '',
        base_qty: 1,
        canceled_at: 0,
        category_id: '428bd60cb45a529878308b695b4d881ce9624f07d4e3ddb38c80920063f38427',
        cmm_id: '',
        combo_items: [],
        completed_at: 0,
        decline_reason: null,
        confirmed_at: 1666354654,
        created_at: 1666354654,
        declined_at: 0,
        discount_per: 0,
        finished_at: 0,
        gvariation_name: 'Size',
        is_combo_item: 0,
        is_new_variation: 0,
        item_code: '',
        item_discount: null,
        item_id: '30b8714d12834063ab149c1806ddba6b',
        item_image: '',
        item_name: 'Tomato Soup',
        item_price: 6,
        item_quantity: 1,
        item_status: 1,
        itr: 2,
        kitchen_counter_id: null,
        kitchen_picked_at: '',
        kitchen_picked_by: '',
        kitchen_time_to_complete: 10,
        new_addons_name: '',
        new_variation: [],
        new_variation_ids: '|[object Object]',
        new_variation_name: '(Medium )',
        open_item: 0,
        order_by: 'MM',
        order_item_id: 'uOpg430b8714d12834063ab149c1806ddba6b',
        original_price: 6,
        prepared_at: 0,
        reward_id: '',
        special_note: '',
        subcategory_id: '4ed203d834abb44186ca46031299304e2104bc41fb89303ee55c1f3e81d91ce0',
        unit: 'number',
        variant_info: [
          {
            group_id: 'ca469ad13869450698f2b8d5fcc671e4',
            options: [{ id: '4F3Kt0B7Lg', price: 2 }],
          },
        ],
        variant_printer: [],
        variation_ids: '',
        variation_name: 'Medium ',
        void_at: 0,
      },
      {
        addon_ids: '',
        addons: [
          {
            id: null,
            itemids: [],
            max_qty: null,
            name: null,
            price: null,
            qty: null,
            status: null,
          },
        ],
        addons_name: '',
        base_qty: 1,
        canceled_at: 0,
        category_id: 'fb153306921d4b48b2f6b6e6bfff9474',
        cmm_id: '',
        combo_items: [],
        completed_at: 0,
        decline_reason: null,
        confirmed_at: 1666354654,
        created_at: 1666354654,
        declined_at: 0,
        discount_per: 0,
        finished_at: 0,
        gvariation_name: '',
        is_combo_item: 0,
        is_new_variation: 0,
        item_code: '',
        item_discount: null,
        item_id: 'dced5d2f9ce14555aee12e2486af65f9',
        item_image: '',
        item_name: 'Bihun Goreng Biasa',
        item_price: 4.5,
        item_quantity: 1,
        item_status: 1,
        itr: 2,
        kitchen_counter_id: null,
        kitchen_picked_at: '',
        kitchen_picked_by: '',
        kitchen_time_to_complete: 20,
        new_addons_name: '',
        new_variation: [],
        new_variation_ids: '',
        new_variation_name: '',
        open_item: 0,
        order_by: 'MM',
        order_item_id: 'YNQjndced5d2f9ce14555aee12e2486af65f9',
        original_price: 4.5,
        prepared_at: 0,
        reward_id: '',
        special_note: '',
        subcategory_id: '9fe38835da1b4e9fa7bf9c941a5dccdf',
        unit: 'number',
        variant_info: [],
        variant_printer: [],
        variation_ids: '',
        variation_name: '',
        void_at: 0,
      },
    ],
    mark_prepared_at: 0,
    name: 'EasyEat User',
    no_enter: 0,
    op_no: '',
    op_order_creation_time: '',
    order_by: 'MM',
    order_id: 'EtTvJFj5O21666354561',
    order_no: 'ieBSZwEs-RNR',
    order_seq: 'x07B-RNR',
    order_status: 2,
    order_type: 0,
    pax: 5,
    pay_with_cash: 0,
    phone: '463485578129317',
    platform: 'easyeat',
    primary_fc_order: 0,
    reason: '',
    rest_reach_min_time: 2,
    restaurant_id: 'c49dee80aeee27ab5e19689fcec88480',
    restaurant_name: 'Easyy Eat Test Restaurant',
    sch_time: '',
    schedule_confirmed_at: 0,
    scheduled: 0,
    skip_packaging_charge_operation: 0,
    skip_service_charge_operation: 0,
    special_notes: [],
    table_id: '2CWRLSN0rY',
    table_no: 'C7',
    tasks: null,
    time_epoch: 0,
    time_zone: '',
    user_id: 'b6125fbace20d291a8696604ec72361997f441610e676001dcefd0acb7515665',
    user_platform: 'RNR',
    vehicle_type: '',
    void_items: [],
  },
];

const rest_details = {
  _id: '5e8cd97e3b59bf4b3a77ff62',
  address: 'Ground Floor 4, 1800 Ellis St, San Francisco, CA 94115, USA',
  address_1: '1800 Ellis St, San Francisco, CA 94115, USA',
  address_2: 'Ground Floor 4',
  area: '',
  base_roundoff: 0.05,
  block_pmt: [
    {
      channel_id: ['fpx_rhb'],
      payment_method: 'NET-BANKING',
    },
    {
      channel_id: ['offline_debit_card', 'offline_tng-ewallet'],
      payment_method: 'OFFLINE-POS',
    },
  ],
  city: 'Radin',
  collapse: true,
  company_name: null,
  config_timings: [
    {
      id: 'w',
      name: 'Weekdays',
      timing: [704, 1439],
    },
    {
      id: '1625194688288Weekends',
      name: 'Weekends',
      timing: [600, 1200],
    },
    {
      id: '1626091726279lunch',
      name: 'lunch',
      timing: [720, 900],
    },
    {
      id: '1626924799653Special_',
      name: 'Special',
      timing: [780, 960],
    },
    {
      id: '1626964817966All_Day',
      name: 'All Day',
      timing: [1, 1439],
    },
    {
      id: '1632476627204Special_Test_Slot',
      name: 'Special Test Slot',
      timing: [600, 1110],
    },
    {
      id: '1637574662532Breakfast',
      name: 'Breakfast',
      timing: [420, 600],
    },
    {
      id: '1638169009888ljkjl',
      name: 'ljkjl',
      timing: [540, 1260],
    },
    {
      id: '1654514218270Weekdays',
      name: 'Weekdays',
      timing: [540, 1260],
    },
  ],
  country: 'Malaysia',
  country_code: 'MY',
  created_at: 1587818951,
  cuisine: [],
  curr_code: 'MYR',
  curr_sym: 'RM',
  custom_print: [
    {
      count: 12,
      item_id: '6013c48e1e5b2a09a84f0dbba53bba41',
    },
    {
      count: 10,
      item_id: '32df4861789092b464477cbea03161c6',
    },
    {
      count: 5,
      item_id: 'a1066b1ac537cc3bf0787f4ff59f0cf0',
    },
  ],
  dial_code: '+60',
  dkick_code: [27, 112, 0, 50, 250],
  email: 'ashutosh.sharma@easyeat.ai',
  emails: {
    am: ['ashutosh.kumar@easyeat.ai'],
    cm: ['ashutosh.kumar@easyeat.ai', 'admin@easyeat.ai'],
    pm: ['ashutosh.kumar@easyeat.ai'],
  },
  fees: [
    {
      applicable_cat: [],
      applicable_on: [],
      applicable_subcat: [],
      charges: [
        5, 5, 5, 5.4, 6, 6.6, 7.2, 7.9, 8.6, 9.3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22,
        24, 26, 28, 30, 32, 34, 36, 38, 40,
      ],
      class: null,
      data: null,
      id: 'delivery',
      name: 'Delivery Fee',
      order_type: [],
      status: 1,
      sub_name: null,
      tax: 0,
      type: null,
    },
  ],
  foodcourt: null,
  hq_id: '81f50d767f5d43a8a3c322cf7df4bee3',
  id: 'c49dee80aeee27ab5e19689fcec88480',
  is_dummy_outlet: true,
  is_realm_enabled: null,
  language: 'en_US',
  logo: 'c49dee80aeee27ab5e19689fcec88480_1657537757.jpeg',
  loyalty_settings_v2: {
    banner_path:
      '{"id":"template-1","type":1,"img":"https://d208quqxsjalxm.cloudfront.net/promotion-templates/bg-1.png","img_with_text":"https://d208quqxsjalxm.cloudfront.net/promotion-templates/bg-1-text.png","bg_color":"#f8d77b","bottom":{"img1":"https://d208quqxsjalxm.cloudfront.net/promotion-templates/menu-1.svg","img2":"https://d208quqxsjalxm.cloudfront.net/promotion-templates/order-1.svg","img3":"https://d208quqxsjalxm.cloudfront.net/promotion-templates/payment-1.svg"},"properties":{"text1":{"color":"#000000","font-size":"16px","font-weight":"bold","align":"center"},"text2":{"color":"#F75841","font-size":"36px","font-weight":"bold","align":"center"},"text3":{"color":"#000000","font-size":"16px","font-weight":"bold","align":"center"},"text4":{"color":"#000000","font-size":"14px","font-weight":"normal","align":"center"}},"button":{"color":"#6cc433","font-size":"13px","font-weight":"bold"},"country_code":"MY"}',
    cashback: 5,
    expiry_days: 45,
    heading: '40',
    is_loyalty_active: true,
    min_item_value: 10,
    order_type_names: {
      DINEIN: 'Dine in',
      DLEV: 'Delivery',
      TAKEAYPICKUP: 'Pick Up',
    },
    order_types: ['DINEIN', 'TAKEAYPICKUP', 'DLEV'],
    sub_category_ids: null,
    sub_text: '30',
    visibility: true,
  },
  mall: 'abc',
  name: 'Easyy Eat Test Restaurant',
  nameid: 'jibril',
  next_open_epoch: 1659686689,
  offline_platforms: [
    {
      code: null,
      comm_amt: 2.5,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'others',
      img: 'others_platform.svg',
      name: 'Others',
      order_type: 1,
      password: null,
      payment_channel: null,
      pkg_applicable: 1,
      rest_id: null,
      status: null,
      sync: null,
      username: null,
    },
    {
      code: null,
      comm_amt: 0,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'hungry2u',
      img: 'hungry2u.png',
      name: 'Hungry2U',
      order_type: 1,
      password: null,
      payment_channel: null,
      pkg_applicable: null,
      rest_id: null,
      status: null,
      sync: null,
      username: null,
    },
    {
      code: null,
      comm_amt: 10,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'fave',
      img: 'fave.png',
      name: 'Fave',
      order_type: 1,
      password: null,
      payment_channel: null,
      pkg_applicable: 0,
      rest_id: null,
      status: null,
      sync: null,
      username: null,
    },
    {
      code: null,
      comm_amt: 20,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'bungkusit',
      img: 'bungkusit.png',
      name: 'Bungkus IT',
      order_type: 1,
      password: null,
      payment_channel: null,
      pkg_applicable: 1,
      rest_id: null,
      status: null,
      sync: null,
      username: null,
    },
    {
      code: null,
      comm_amt: 0,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'whatsapp',
      img: 'whatsapp.png',
      name: 'WhatsApp',
      order_type: 3,
      password: null,
      payment_channel: null,
      pkg_applicable: 1,
      rest_id: null,
      status: null,
      sync: null,
      username: null,
    },
    {
      code: null,
      comm_amt: 6,
      comm_typ: 'fixed',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'website',
      img: 'others_platform.svg',
      name: 'Website',
      order_type: 3,
      password: null,
      payment_channel: null,
      pkg_applicable: 0,
      rest_id: null,
      status: null,
      sync: null,
      username: null,
    },
    {
      code: null,
      comm_amt: 5,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'dine_by_wix',
      img: 'dine_by_wix.png',
      name: 'Dine by Wix',
      order_type: 1,
      password: null,
      payment_channel: null,
      pkg_applicable: 0,
      rest_id: null,
      status: null,
      sync: null,
      username: null,
    },
    {
      code: null,
      comm_amt: 0,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'beep_delivery',
      img: 'beep.png',
      name: 'Beepit',
      order_type: 1,
      password: null,
      payment_channel: null,
      pkg_applicable: 1,
      rest_id: null,
      status: 1,
      sync: null,
      username: null,
    },
    {
      code: null,
      comm_amt: 0,
      comm_typ: 'fixed',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'snailer',
      img: 'snailer.png',
      name: 'Snailer',
      order_type: 3,
      password: null,
      payment_channel: null,
      pkg_applicable: 0,
      rest_id: null,
      status: 1,
      sync: null,
      username: null,
    },
    {
      code: null,
      comm_amt: 10,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'eatmol',
      img: 'eatmol.png',
      name: 'Eatmol',
      order_type: 3,
      password: null,
      payment_channel: null,
      pkg_applicable: 1,
      rest_id: null,
      status: 1,
      sync: null,
      username: null,
    },
    {
      code: '',
      comm_amt: 10,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'meniaga',
      img: 'meniaga.png',
      name: 'Meniaga',
      order_type: 3,
      password: null,
      payment_channel: null,
      pkg_applicable: 0,
      rest_id: null,
      status: 1,
      sync: null,
      username: null,
    },
    {
      code: '',
      comm_amt: 10,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: 1646322462,
      email: null,
      fp_sync: null,
      id: 'just_order_today',
      img: 'just_order_today.png',
      name: 'Just Order Today',
      order_type: 1,
      password: null,
      payment_channel: 'offline_just_order_today',
      pkg_applicable: 0,
      rest_id: null,
      status: 1,
      sync: null,
      username: null,
    },
    {
      code: '',
      comm_amt: 11,
      comm_typ: 'percentage',
      country_codes: [],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'grab',
      img: 'grab.png',
      name: 'Grab',
      order_type: 3,
      password: null,
      payment_channel: null,
      pkg_applicable: 1,
      rest_id: null,
      status: 1,
      sync: null,
      username: null,
    },
    {
      code: '',
      comm_amt: 2.5,
      comm_typ: 'percentage',
      country_codes: ['MY'],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'foodpanda',
      img: 'panda.png',
      name: 'Foodpanda',
      order_type: 3,
      password: null,
      payment_channel: null,
      pkg_applicable: 1,
      rest_id: null,
      status: 1,
      sync: null,
      username: null,
    },
    {
      code: '',
      comm_amt: 0,
      comm_typ: 'percentage',
      country_codes: ['MY'],
      created_at: null,
      email: null,
      fp_sync: null,
      id: 'sama2_lokal',
      img: 'sama2local.png',
      name: 'Sama2 Lokal',
      order_type: 3,
      password: null,
      payment_channel: null,
      pkg_applicable: 1,
      rest_id: null,
      status: 1,
      sync: null,
      username: null,
    },
  ],
  on_whatsapp: 0,
  open_items: {
    def_cat: 'ffc4f06c74fe317e25d2764a75c8fb1dd097f19c55438ae083482de7d20fe585',
    def_subcat: '4ccb2df3eaa50ae1cf909efefdcc18b7060ec69dc5020574dc4264e1f53bc05b',
  },
  phone: '1121151876',
  pin_code: '94115',
  print: null,
  print_logo: 'restaurant_image/c49dee80aeee27ab5e19689fcec88480_bw_1657537757.jpeg',
  printer: '192.168.29.222:9100',
  priority: 3,
  quick_notes: [
    {
      id: 'ABNXs',
      note: 'salty bit1',
      visible_to_user: 1,
    },
    {
      id: 'xBIdI',
      note: 'Jibril',
      visible_to_user: 1,
    },
    {
      id: 'z337m',
      note: 'Dessert',
      visible_to_user: 1,
    },
    {
      id: 'qYbhm',
      note: 'Hot with less spices',
      visible_to_user: 1,
    },
    {
      id: 'opcor',
      note: 'Taknak Ice',
      visible_to_user: 1,
    },
    {
      id: 'ldYjE',
      note: 'Extra Green Sauce',
      visible_to_user: 1,
    },
    {
      id: 'cHejf',
      note: 'Extra gravy',
      visible_to_user: 1,
    },
    {
      id: 'qIsvz',
      note: 'testing123123',
      visible_to_user: 0,
    },
    {
      id: 'yDT9f',
      note: 'abcd',
      visible_to_user: 0,
    },
    {
      id: 'pjPsY',
      note: 'egf',
      visible_to_user: 0,
    },
    {
      id: 'qGD2z',
      note: 'abcdef',
      visible_to_user: 0,
    },
    {
      id: 'yY5EV',
      note: 'geetgeet',
      visible_to_user: 0,
    },
    {
      id: '22821ce842ce4d0c8427309b124319cb',
      note: " .njbgvhbjnklk;l'\n;kljklbjvkhj",
      visible_to_user: 1,
    },
    {
      id: 'd493ad8dfb4e43ab9692e327692e4f24',
      note: 'alt',
      visible_to_user: 1,
    },
  ],
  report_timings: [
    {
      id: 'UqoAiuEs6JUS',
      is_default: 0,
      name: 'Morning Shift',
      status: 1,
      timings: [600, 1380],
    },
    {
      id: 'V90YkzsMaRIK',
      is_default: 0,
      name: 'Night Shift',
      status: 1,
      timings: [780, 120],
    },
  ],
  rest_timings: {
    DELIVERY: [],
    DINING: [
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
    ],
    TAKEAWAY: [
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
      {
        days: [],
        is_enabled: true,
        slot: [
          {
            end: 1439,
            start: 0,
          },
        ],
        tab: null,
      },
    ],
  },
  restaurant_image: null,
  settings: {
    cash_mgt: {
      enable: 1,
    },
    delivery: {
      auto_assign_car: 1,
      car_min_items: 5,
      enabled: null,
      rest_reach_min_time: 5,
      rest_reach_min_time_scheduled: null,
      showRainBanner: false,
    },
    discount: {
      custom_percentage_list1: [],
      enabled: 1,
      preset: 1,
    },
    global: {
      auto_accept: 0,
      auto_accept_sch: 0,
      auto_refresh: 0,
      auto_refresh_interval: 5000,
      cash_registry: 1,
      cust_info_popup: 1,
      custom_order_dashboard: 1,
      default_device: {
        uid: '9EB4A88D-ED0B-4F78-8E3D-9D3A88A2216D',
      },
      delete_order: 1,
      disable_add_more_items: 0,
      edit_commision: 1,
      enable_pre_paid_order: 1,
      enable_rest_food_logo: 0,
      enable_server_flow: 0,
      force_close_cash_mgt: 0,
      fp_integration: 1,
      gf_integration: 1,
      hide_action_button: 1,
      hide_action_button_react: null,
      hide_download_popup: 0,
      hide_order_image: 0,
      is_order_sync: true,
      item_level_discount: 1,
      lock_screen: 1,
      lock_screen_idle: 2000000,
      lock_screen_timeout: 200000000,
      loyalty: 0,
      loyalty_v2: true,
      loyalty_v2_visible_on_pos: 1,
      mark_order_prepared: 0,
      mark_prepared_sms: 1,
      multiple_addon: 1,
      no_login_workflow: 1,
      pos: 1,
      posItemPriceTKasDinein: 1,
      pos_view: 's',
      pre_paid_order: 6,
      print_debug_messages: 0,
      print_v2_enabled: 1,
      ring_notification: true,
      service_bell_enable: 1,
      show_active_printers: 1,
      skip_pkg_chrg: 2,
      skip_pkg_chrg_order_type: 7,
      skip_service_chrg: 1,
      socket_printing: 1,
      special_menu: 1,
      split_bill: 1,
      table_layout: 1,
      takeaway_cash_enable: 1,
      tossed_specific: 1,
      tp_voucher: 1,
      use_es_service: 1,
      veg_option_enable: 1,
      visible_on_app: 0,
      void: 1,
      void_item_after_completed: 1,
      whatsapp_notifier_order_status: 1,
    },
    hubspot: {
      deal_id: null,
    },
    login: {
      skip_verification: 1,
    },
    marketing: {
      fb_pixel: '',
    },
    menu: {
      cmm_enable: null,
      collapse: 1,
      item_code: 31,
      item_code_max_len: 1,
      new_variation: 1,
      pax: 1,
    },
    print: {
      cash_drawer: 31,
      cash_mgt_format_override: 0,
      char_page_code: null,
      configurable_settings: {
        counter_receipt: {
          addon: {
            fs: 's',
            ft: 'n',
          },
          allergies: {
            fs: 's',
            ft: 'n',
          },
          counter_name: {
            fs: 'l',
            ft: 'b',
          },
          customer_name: {
            fs: 'm',
            ft: 'n',
            name: 'CUSTOMER NAME',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          customer_phone: {
            fs: 's',
            ft: 'n',
            name: 'CUSTOMER PHONE',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          date: {
            fs: 'm',
            ft: 'n',
            name: 'DATE',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 0,
          },
          date_time: {
            fs: 'm',
            ft: 'n',
            name: 'BILL DATE',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          header_space: 5,
          invoice_no: {
            fs: 'm',
            ft: 'n',
            name: 'INVOICE NO',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          item_name: {
            fs: 'm',
            ft: 'b',
          },
          no_of_items: {
            fs: 's',
            ft: 'n',
            name: 'NUMBER OF ITEMS',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          notes: {
            fs: 's',
            ft: 'n',
          },
          order_seq: {
            fs: 'm',
            ft: 'b',
            name: 'ORDER NO',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          order_type: {
            fs: 's',
            ft: 'n',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          pax: {
            fs: 's',
            ft: 'n',
            name: 'PAX',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          staff_name: {
            fs: 'm',
            ft: 'n',
            name: 'STAFF NAME',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          table: {
            fs: 'm',
            ft: 'b',
            name: 'TABLE NO',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 1,
          },
          time: {
            fs: 's',
            ft: 'n',
            name: 'TIME',
            o_type: 7,
            priority: 1,
            section: 'h',
            show: 0,
          },
          variant: {
            fs: 's',
            ft: 'n',
          },
        },
      },
      counter_footer: [' '],
      enabled: 1,
      feed_point: 25,
      font_size: 's',
      footer: [' '],
      format_code: null,
      header: {
        append: ['', 'SST No.: B16-2011-32100018', ''],
        custom: [],
        prepend: ['Easy Eat Sdn Bhd', 'Co. No. 123456789'],
      },
      inst_font: 'm',
      item_align: 'l',
      label_format_v2: 1,
      language_code: null,
      master_counter_itr_list: null,
      master_docket: 1,
      master_docket_printer: null,
      master_order_printer: [],
      on_accept_enabled: 1,
      on_accept_new_itr: 10,
      on_accept_new_order: 11,
      on_decline: 3,
      on_settle: 10,
      on_table_change: 10,
      on_void_accepted: 3,
      on_void_new_itr: 11,
      on_void_unaccepted: 3,
      pmt_mode_in_body: 1,
      post_settle: 8,
      print_bahasa: null,
      print_delay: 300,
      receipt_keyname: 'receiptprint',
      response_format: 0,
      separate_docket: 0,
      show_logo: 1,
      show_op_order_id: 11,
      slip_font: {
        bill: 's',
        cash_in_out: 's',
        cash_mgt_report: 's',
        counter: 's',
        master_docket: 's',
        master_order_list: 's',
        table_change: 's',
      },
      sname: 1,
      split_addon_variant: null,
      table_no_position: 'b',
      uname: 1,
      void_enabled: 1,
      void_format_code: null,
      void_separate_docket: 0,
    },
    reports: {
      enable_eod: 1,
      eod_font_size: '8px',
      eod_left_margin: null,
      eod_page_width: '180px',
      eod_printer: 'Newme',
      full_eod: 0,
    },
    settlement: {
      enable: 1,
      visible: 1,
    },
    sounds: {
      force_stop_sound: 0,
      repeat: 1,
      selected: 'sound1.wav',
      timeout: 20000,
    },
  },
  state: 'Maluku',
  status: 1,
  sub_domain: null,
  tax_after_discount: null,
  third_party_platforms: null,
  time_zone: 'Asia/Kuala_Lumpur',
  type: 3,
  voucher_items: null,
};

console.log(
  JSON.stringify(
    generatePrintData(order_details, rest_details, 1, 1, {}, {}, {}, bill_details, ''),
  ),
);
