const pmt = {
  fpx_amb: 'Am Bank',
  fpx_bimb: 'Bank Islam',
  fpx_cimbclicks: 'CIMB Bank',
  fpx_hlb: 'Hong Leong Bank',
  fpx_pbb: 'Public Bank',
  fpx_ocbc: 'OCBC Bank',
  fpx_scb: 'Standard Chartered Bank',
  fpx_abb: 'Affin Bank Berhad',
  fpx_abmb: 'Alliance Bank',
  fpx_uob: 'United Overseas Bank',
  fpx_bsn: 'Bank Simpanan Nasional',
  fpx_kfh: 'Kuwait Finance House',
  fpx_bkrm: 'Kerjasama Rakyat Malaysia',
  fpx_bmmb: 'Bank Muamalat',
  fpx_hsbc: 'HSBC',
  boost: 'Boost',
  'mb2u_qrpay-push': 'Maybank QRPay',
  'tng-ewallet': 'Touch n Go',
  credit: 'Credit Card',
  grabpay: 'Grab Pay',
  fpx_rhb: 'RHB Bank',
  cash: 'Cash',
  offline_mastercard: 'Master Card',
  offline_visa: 'Visa Card',
  offline_american_express: 'American Express',
  offline_online_pay: 'Online Bank Transfer',
  offline_boost: 'Offline Boost',
  offline_grabpay: 'Offline Grab Pay',
  'offline_mb2u_qrpay-push': 'Offline Maybank QRPay',
  'offline_tng-ewallet': 'Offline Touch n Go',
  offline_fpanda_settle: 'Food Panda Settlement',
  offline_grab_settle: 'Grab Food Settlement',
  offline_shopee_pay: 'Offline Shopee Pay',
  offline_lazada_pay: 'Offline Lazada Pay',
  offline_klook_pay: 'Offline Klook Pay',
  offline_fave_pay: 'Offline Fave Pay',
  offline_oddle: 'Offline Oddle',
  offline_hungry2u: 'Offline Hungry2U',
  offline_add_to_room: 'Add to Room Charges',
  offline_eatigo: 'Offline Eatigo',
  offline_bonuslink: 'Bonuslink',
  offline_delivery_partner: 'Delivery Partner(Bank Deposit)',
  offline_website_stripe: 'Website(Stripe)',
  offline_bigpay: 'Offline BigPay',
  offline_others: 'Others',
  offline_no_payment_required: 'No Payment Required',
  offline_teleport: 'Offline Teleport',
  offline_deliver_eat: 'DeliverEat Settlement',
  offline_aliments: 'Aliments Settlement',
  offline_airasia_food: 'AirAsia Food Settlement',
  offline_debit_card: 'Debit Card',
  offline_zesty_clickz: 'Zesty Clickz Settlement',
  offline_mulaeats: 'Mulaeats Settlement',
  offline_meniaga: 'Meniaga Settlement',
  offline_easi_eats: 'Easi Eats Settlement',
  offline_dine_by_wix: 'Dine by Wix Settlement',
  offline_entertainment: 'Entertainment',
  offline_olarme: 'OlarMe Settlement',
  offline_snailer: 'Snailer Settlement',
  offline_eatmol: 'Eatmol Settlement',
  offline_z_city: 'Offline Z-City',
  offline_fave_voucher: 'Fave Voucher',
  offline_klook_voucher: 'Klook Voucher',
  offline_shopee_voucher: 'Shopee Voucher',
  offline_lazada_voucher: 'Lazada Voucher',
  offline_beepit: 'Beepit Settlement',
  offline_shopee_food: 'Offline Shopee Food',
  offline_staff: 'Staff',
  offline_revenue_monster: 'Revenue Monster',
  offline_voucher: 'Voucher',
  offline_wct_buddy: 'Offline Wct Buddy',
  offline_sunway_pals: 'Sunway Pals',
  offline_canton_payment: 'Canton2u.com payment',
  offline_union_experience_voucher: 'Union Experience',
  loyalty_cashback: 'Loyalty Cashback',
  offline_ghl: 'GHL',
  offline_setia_voucher: 'Setia Voucher',
  shopeepay: 'ShopeePay',
  offline_wct: 'Offline WCT',
  offline_11street_voucher: '11 Street Voucher',
  offline_suria_klcc_voucher: 'Suria KLCC Voucher',
  offline_ambank_qr: 'Ambank QR',
  offline_candybar_voucher: 'Candybar Voucher',
  offline_one_shop: 'One Shop',
  offline_1_pay: 'Offline 1 Pay',
  offline_sungei_wang_voucher: 'Sungei Wang Voucher',
  offline_quick_sent: 'Quick Sent',
  offline_mae_by_maybank: 'MAE by Maybank',
  offline_pbe_qr: 'PBe QR',
  offline_just_order_today: 'Just Order Today Settlement',
  offline_plug_n_pay: 'Plug N Pay',
  offline_easi_settlement: 'EASI Settlement',
  offline_gunners_settle: 'Gunners Delivery',
  offline_staff_meals: 'Staff Meals',
  offline_sunway_emall: 'Sunway eMall',
  offline_grabfood_abe_yus_cafe: 'GrabFood Abe Yus Cafe',
  offline_grabfood_nasi_kaw_kaw: 'GrabFood Nasi Kaw Kaw',
  offline_grabfood_ikan_bakar: 'GrabFood Ikan Bakar',
  offline_grabfood_jom_laksa: 'GrabFood Jom Laksa',
  offline_fpanda_abe_yus_cafe: 'FoodPanda Abe Yus Cafe',
  offline_fpanda_jom_laksa: 'FoodPanda Jom Laksa',
  offline_fpanda_nasi_kaw: 'FoodPanda Nasi Kaw Kaw',
  offline_fpanda_ikan_bakar: 'FoodPanda Ikan Bakar',
  offline_fpanda_kari_puff_abe_yus: 'FoodPanda Kari Puff Abe Yus',
  offline_fpanda_lunch_box: 'FoodPanda Lunch Box',
  offline_fpanda_honest_bowl: 'FoodPanda Honest Bowl',
  offline_fpanda_faasos: 'FoodPanda Faasos',
  offline_fpanda_mix_n_match: 'FoodPanda Mix And Match',
  offline_shopee_abe_yus_cafe: 'Shopee Food Abe Yus Cafe',
  offline_shopee_jom_laksa: 'Shopee Food Jom Laksa',
  offline_shopee_nasi_kaw: 'Shopee Food Nasi Kaw Kaw',
  offline_shopee_ikan_bakar: 'Shopee Food Ikan Bakar',
  offline_shopee_kari_puff_abe_yus: 'Shopee Food Kari Puff Abe Yus',
  offline_d_kocek: 'd-Kocek',
  offline_fpanda_sweet_spot: 'FoodPanda Sweet Spot',
  offline_live_express: 'Live Express',
  offline_woodsfield: 'Woodsfield',
  offline_ioupay: 'IOUpay',
  offline_shopee_platter_box: 'Shopee Food Platter Box',
  offline_umai: 'UMAI',
  offline_smartbite: 'Smartbite',
  fpx_mb2u: 'Maybank',
  user_credits: 'User Credits',
  offline_ovo: 'Offline OVO',
  offline_edc_bca: 'EDC BCA',
  offline_dana: 'Offline Dana',
  offline_edc_cimb_niaga: 'EDC CIMB Niaga',
  offline_link_aja: 'Offline Link Aja',
  offline_edc_bri: 'EDC BRI',
  offline_edc_mandiri: 'EDC Mandiri',
  offline_edc_other: 'Other EDC',
  offline_gopay: 'Offline GoPay',
  offline_edc_bni: 'EDC BNI',
  offline_citibank: 'Citibank',
  'mandiri-virtual-account': 'Mandiri',
  'bni-virtual-account': 'BNI',
  'ovo-open-api': 'OVO Open API',
  'shopeepay-emoney': 'ShopeePay',
  'doku-virtual-account': 'DOKU',
  'dokuwallet-emoney': 'DOKU Wallet',
  'ovo-emoney': 'OVO',
  'bsm-virtual-account': 'Bank Syariah Indonesia (BSI)',
  'bca-virtual-account': 'BCA',
  'permata-virtual-account': 'Permata',
  'credit-card': 'Credit Card',
  'cimb-direct-debit': 'CIMB Direct Debit',
  'danamon-virtual-account': 'Danamon',
  'bri-virtual-account': 'BRI',
  'cimb-virtual-account': 'CIMB',
  'direct-debit': 'BRI Direct Debit',
  offline_forestone: 'ForestOne',
  offline_customer_credit: 'Customer Credit',
  offline_panda_pro: 'Panda Pro',
  offline_shopee_takeaway: 'Shopee Takeaway',
  offline_ioi_shopz: 'IOI Shopz',
  offline_symplified: 'SYMplified',
  offline_rhb_qr: 'RHB QR',
  qris: 'QRIS',
  offline_grab_mart: 'Grab Mart',
  offline_panda_frozen: 'Panda Frozen',
  offline_setel: 'Setel',
  offline_bangsar_south: 'Voucher Bangsar South',
  offline_we_eat: 'We Eat',
  offline_setia_one_touch: 'Setia One Touch',
  offline_lalamove_settlement: 'Lalamove Settlement',
  offline_public_bank_qr: 'Offline Public Bank QR',
  offline_minimart: 'Minimart',
  offline_alliance_bank_qr: 'Offline Alliance Bank QR',
  offline_mcash: 'MCash',
  sama_sama_lokal: 'Sama Sama Lokal',
  offline_heineken: 'Heineken',
  nmoom: 'NMooM',
  offline_qr__rhb: 'offline QR RHB',
  toyyib_pay: 'ToyyibPay',
  public_bank_qrpay: 'Public Bank QRPay',
  offline_qris: 'Offline QRIS',
  traveloka_eats: 'Traveloka Eats',
  edc_hsbc: 'EDC HSBC',
  edc_bca_debit: 'EDC BCA Debit',
  edc_bca_credit: 'EDC BCA Credit',
  ar_cl: 'AR CL',
  down_payment: 'Down Payment',
  bayarlah: 'bayarlah',
  usm_po: 'USM PO',
  union_pay_online: 'UnionPay Online',
  delivery_pmt: 'Delivery',
  hospital_voucher: 'Hospital Voucher',
  shoppe_settlement: 'Shoppe Settlement',
  gift_voucher: 'Gift Voucher',
  go_food: 'Go Food',
  kiplepay: 'Kiplepay',
  cimb_duitnow: 'CIMB Duitnow QRPay',
  club_ioi: 'Club IOI',
  tiktok_seller: 'TikTok Seller',
  shoppe_partner: 'Shoppe Partner',
  shopzpin: 'Shopzpin',
  cimb_1: 'CIMB',
  bank_islam: 'Offline Bank Islam',
  rev_pay: 'Rev Pay',
  offline_cimb: 'QR OFFLINE CIMB',
  marketing_button: 'marketing button',
  food_testing: 'RnD food testing button',
  offline_foodpanda: 'Offline FoodPanda Payment',
  hong__eong_bank: 'Hong Leong Bank QR Scan',
  pos_pay: 'POS PAY',
  tj_cash: 'TJ Cash',
  tj_e_wallet: 'TJ e-wallet',
  giler_ketam: 'Giler Ketam',
  threebuddies: 'ThreeBuddies',
  unick_kitchen: 'Unick Kitchen',
  wood_shisha: 'Wood Shisha',
  fam_fries: 'Fam Fries',
  tiau_lah: 'Tiau lah',
  rimba_kitchen: 'Rimba Kitchen',
  rimba_drinks: 'Rimba Drinks',
  pay_later: 'Pay Later',
  my_debit: 'MyDebit',
  offline_go_biz: 'GoBiz',
  offline_jcb: 'JCB',
  offline_offline_qris_gojek: 'Offline Qris Gojek',
  offline_offline_qris_grab: 'Offline QRIS Grab',
  offline_cashback: 'Cashback',
  gopay: 'GoPay',
  offline_testing123: 'testing123',
  offline_assasin: 'Assasin',
  offline_assassin: 'Assassin',
  offline_backend_test_payment_method: 'Backend Test Payment method',
  offline_operation_testing: 'Operation testing',
  offline_demo_jatin: 'Demo_Jatin',
};

class PaymentConfig {
  constructor(pmt) {
    this.pmt = pmt;
  }

  getOnlineWalletList() {
    return [
      'boost',
      'mb2u_qrpay-push',
      'tng-ewallet',
      'grabpay',
      'loyalty_cashback',
      'shopeepay',
      'user_credits',
      'ovo-open-api',
      'shopeepay-emoney',
      'dokuwallet-emoney',
      'ovo-emoney',
      'qris',
      'gopay',
    ];
  }

  getNetbankingList() {
    return [
      'fpx_amb',
      'fpx_bimb',
      'fpx_cimbclicks',
      'fpx_hlb',
      'fpx_pbb',
      'fpx_ocbc',
      'fpx_scb',
      'fpx_abb',
      'fpx_abmb',
      'fpx_uob',
      'fpx_bsn',
      'fpx_kfh',
      'fpx_bkrm',
      'fpx_bmmb',
      'fpx_hsbc',
      'fpx_rhb',
      'fpx_mb2u',
      'mandiri-virtual-account',
      'bni-virtual-account',
      'doku-virtual-account',
      'bsm-virtual-account',
      'bca-virtual-account',
      'permata-virtual-account',
      'danamon-virtual-account',
      'bri-virtual-account',
      'cimb-virtual-account',
    ];
  }

  getCreditCardList() {
    return ['credit', 'credit-card', 'cimb-direct-debit', 'direct-debit'];
  }

  getOfflineWalletList() {
    return [
      'offline_online_pay',
      'offline_boost',
      'offline_grabpay',
      'offline_mb2u_qrpay-push',
      'offline_tng-ewallet',
      'offline_fpanda_settle',
      'offline_grab_settle',
      'offline_shopee_pay',
      'offline_lazada_pay',
      'offline_klook_pay',
      'offline_fave_pay',
      'offline_oddle',
      'offline_hungry2u',
      'offline_add_to_room',
      'offline_eatigo',
      'offline_bonuslink',
      'offline_delivery_partner',
      'offline_website_stripe',
      'offline_bigpay',
      'offline_others',
      'offline_no_payment_required',
      'offline_teleport',
      'offline_deliver_eat',
      'offline_aliments',
      'offline_airasia_food',
      'offline_zesty_clickz',
      'offline_mulaeats',
      'offline_meniaga',
      'offline_easi_eats',
      'offline_dine_by_wix',
      'offline_entertainment',
      'offline_olarme',
      'offline_snailer',
      'offline_eatmol',
      'offline_z_city',
      'offline_fave_voucher',
      'offline_klook_voucher',
      'offline_shopee_voucher',
      'offline_lazada_voucher',
      'offline_beepit',
      'offline_shopee_food',
      'offline_staff',
      'offline_revenue_monster',
      'offline_voucher',
      'offline_wct_buddy',
      'offline_sunway_pals',
      'offline_canton_payment',
      'offline_union_experience_voucher',
      'offline_ghl',
      'offline_setia_voucher',
      'offline_wct',
      'offline_11street_voucher',
      'offline_suria_klcc_voucher',
      'offline_ambank_qr',
      'offline_candybar_voucher',
      'offline_one_shop',
      'offline_1_pay',
      'offline_sungei_wang_voucher',
      'offline_quick_sent',
      'offline_mae_by_maybank',
      'offline_pbe_qr',
      'offline_just_order_today',
      'offline_plug_n_pay',
      'offline_easi_settlement',
      'offline_gunners_settle',
      'offline_staff_meals',
      'offline_sunway_emall',
      'offline_grabfood_abe_yus_cafe',
      'offline_grabfood_nasi_kaw_kaw',
      'offline_grabfood_ikan_bakar',
      'offline_grabfood_jom_laksa',
      'offline_fpanda_abe_yus_cafe',
      'offline_fpanda_jom_laksa',
      'offline_fpanda_nasi_kaw',
      'offline_fpanda_ikan_bakar',
      'offline_fpanda_kari_puff_abe_yus',
      'offline_fpanda_lunch_box',
      'offline_fpanda_honest_bowl',
      'offline_fpanda_faasos',
      'offline_fpanda_mix_n_match',
      'offline_shopee_abe_yus_cafe',
      'offline_shopee_jom_laksa',
      'offline_shopee_nasi_kaw',
      'offline_shopee_ikan_bakar',
      'offline_shopee_kari_puff_abe_yus',
      'offline_d_kocek',
      'offline_fpanda_sweet_spot',
      'offline_live_express',
      'offline_woodsfield',
      'offline_ioupay',
      'offline_shopee_platter_box',
      'offline_umai',
      'offline_smartbite',
      'offline_ovo',
      'offline_dana',
      'offline_link_aja',
      'offline_gopay',
      'offline_forestone',
      'offline_customer_credit',
      'offline_panda_pro',
      'offline_shopee_takeaway',
      'offline_ioi_shopz',
      'offline_symplified',
      'offline_rhb_qr',
      'offline_grab_mart',
      'offline_panda_frozen',
      'offline_setel',
      'offline_bangsar_south',
      'offline_we_eat',
      'offline_setia_one_touch',
      'offline_lalamove_settlement',
      'offline_public_bank_qr',
      'offline_minimart',
      'offline_alliance_bank_qr',
      'offline_mcash',
      'sama_sama_lokal',
      'offline_heineken',
      'nmoom',
      'offline_qr__rhb',
      'toyyib_pay',
      'public_bank_qrpay',
      'offline_qris',
      'traveloka_eats',
      'edc_hsbc',
      'edc_bca_debit',
      'edc_bca_credit',
      'ar_cl',
      'down_payment',
      'bayarlah',
      'usm_po',
      'union_pay_online',
      'delivery_pmt',
      'hospital_voucher',
      'shoppe_settlement',
      'gift_voucher',
      'go_food',
      'kiplepay',
      'cimb_duitnow',
      'club_ioi',
      'tiktok_seller',
      'shoppe_partner',
      'shopzpin',
      'cimb_1',
      'bank_islam',
      'rev_pay',
      'offline_cimb',
      'marketing_button',
      'food_testing',
      'offline_foodpanda',
      'hong__eong_bank',
      'pos_pay',
      'tj_cash',
      'tj_e_wallet',
      'giler_ketam',
      'threebuddies',
      'unick_kitchen',
      'wood_shisha',
      'fam_fries',
      'tiau_lah',
      'rimba_kitchen',
      'rimba_drinks',
      'pay_later',
      'my_debit',
      'offline_go_biz',
      'offline_jcb',
      'offline_offline_qris_gojek',
      'offline_offline_qris_grab',
      'offline_cashback',
      'offline_testing123',
      'offline_assasin',
      'offline_assassin',
      'offline_backend_test_payment_method',
      'offline_operation_testing',
      'offline_demo_jatin',
    ];
  }

  getOfflineCreditCardList() {
    return [
      'offline_mastercard',
      'offline_visa',
      'offline_american_express',
      'offline_edc_bca',
      'offline_edc_cimb_niaga',
      'offline_edc_bri',
      'offline_edc_mandiri',
      'offline_edc_other',
      'offline_edc_bni',
      'offline_debit_card',
    ];
  }

  getOfflineRefundOnlyList() {
    return ['offline_citibank'];
  }

  /* Get online payment methods excluding netbanking */
  getOnlinePmtMethods() {
    return [...this.getOnlineWalletList(), ...this.getCreditCardList()];
  }

  /* Get all online payment methods */
  getAllOnlinePmtMethods() {
    return [
      ...this.getNetbankingList(),
      ...this.getOnlineWalletList(),
      ...this.getCreditCardList(),
    ];
  }

  /* Get all offline payment methods */
  getOfflinePmtMethods() {
    return ['cash', ...this.getOfflineCreditCardList(), ...this.getOfflineWalletList()];
  }
}

/* Get payment_method from payment_channel */
const getPmtMethodName = (pmt_channel) => {
  return pmt[pmt_channel] ? pmt[pmt_channel] : pmt_channel;
};

/* Get payment_channel-payment_method mapping obj */
const getPmtMethods = (type) => {
  const pmtConfig = new PaymentConfig(pmt);
  const obj = {};
  const pmt_obj = pmtConfig.pmt;
  let pmt_channels = [];

  // 1:cash
  if (type.includes(1)) {
    pmt_channels.push('cash');
  }
  // 2:wallets
  if (type.includes(2)) {
    pmt_channels = pmt_channels.concat(pmtConfig.getOnlineWalletList());
  }
  // 3:cards
  if (type.includes(3)) {
    pmt_channels = pmt_channels.concat(pmtConfig.getCreditCardList());
  }
  // 4:Netbanking
  if (type.includes(4)) {
    pmt_channels = pmt_channels.concat(pmtConfig.getNetbankingList());
  }
  // 5:offline wallets
  if (type.includes(5)) {
    pmt_channels = pmt_channels.concat(pmtConfig.getOfflineWalletList());
  }
  // 6:offline cards
  if (type.includes(6)) {
    pmt_channels = pmt_channels.concat(pmtConfig.getOfflineCreditCardList());
  }
  // 7:refund only pmt methods
  if (type.includes(7)) {
    // pmt_channels = pmt_channels.concat(pmtConfig.getRefundOnlyMethodList());
    pmt_channels = pmt_channels.concat(pmtConfig.getOfflineRefundOnlyList());
  }
  for (const channel of pmt_channels) {
    obj[channel] = pmt_obj[channel];
  }
  return obj;
};

module.exports = {
  getPmtMethodName,
  getPmtMethods,
};
