const enKeys = {
  createdDate: 'CREATED DATE',
  createdTime: 'CREATED TIME',
  serialNumber: 'SR NO.',
  invoiceNumber: 'INVOICE NO.',
  numItems: 'NO. OF ITEMS',
  pax: 'PAX',
  platform: 'PLATFORM',
  completedDate: 'COMPLETED DATE',
  completedTime: 'COMPLETED TIME',
  amountPaid: 'AMOUNT PAID',
  itemTotal: 'ITEM TOTAL',
  billTotal: 'BILL TOTAL',
  refunds: 'REFUNDS',
  commission: 'COMMISSION',
  promotion: 'PROMOTION',
  serviceCharges: 'SERVICE CHARGES',
  packagingCharges: 'PACKAGING CHARGES',
  tax: 'TAX',
  deliveryFee: 'DELIVERY FEE',
  roundOff: 'ROUND OFF',
  paymentMode: 'PAYMENT MODE',
  orderReportHeadingCaps: 'ORDER REPORT OVER TIME',
  orderReportSheetName: 'Order Report Over Time',
  orderReportFileName: 'Order_Report_Over_Time',
  thanksReportFooter: 'Thanks & Regards',
  contactReportFooter: 'For any queries, contact: hello@easyeat.ai',
  greatDay: 'Have a great day!',
  dineIn: 'Dine In',
  delivery: 'Delivery',
  takeAway: 'Take Away',
  itemCategory: 'CATEGORY',
  itemSubCategory: 'SUB-CATEGORY',
  itemCode: 'ITEM CODE',
  itemName: 'ITEM NAME',
  variationsOptions: 'VARIATION OPTIONS',
  itemQuantity: 'QUANTITY',
  averagePrice: 'AVERAGE PRICE',
  total: 'TOTAL',
  availability: 'AVAILABILITY',
  dishReportHeadingCaps: 'DISH REPORT OVER TIME',
  dishReportSheetName: 'Dish Report Over Time',
  dishReportFileName: 'Dish_Report_Over_Time',
  available: 'Available',
  unavailable: 'Unavailable',
  addOnName: 'ADD-ON NAME',
  quantitySold: 'QUANTITY SOLD',
  addOnReportHeadingCaps: 'ADD-ON REPORT OVER TIME',
  completed: 'Completed',
  canceled: 'Cancelled',
  customerCancelled: 'Customer Cancelled',
  restaurantCancelled: 'Restaurant Cancelled',
  expired: 'Expired',
  date: 'DATE',
  time: 'TIME',
  item: 'ITEM',
  category: 'CATEGORY',
  quantityVoided: 'QUANTITY VOIDED',
  totalPrice: 'TOTAL PRICE',
  voidedBy: 'VOIDED BY',
  reason: 'REASON',
  voidReportHeadingCaps: 'VOID ITEMS REPORT OVER TIME',
  couponCode: 'COUPON-CODE',
  title: 'TITLE',
  channel: 'CHANNEL',
  appliedTimes: 'APPLIED-TIMES',
  totalDiscounts: 'TOTAL DISCOUNTS',
  promotionReportHeadingCaps: 'PROMOTION REPORT OVER TIME',
  promotionReportSheetName: 'Promotion Report Over Date',
  promotionReportFileName: 'Promotion_Report_Over_Time',
  eeCustomerApp: 'Easy Eat Customer App',
  pos: 'POS',
  manualTopUp: 'Manual Top-up',
  reasonNotMentioned: 'Reason not mentioned by staff',
  manualDiscount: 'Manual Discount',
  restaurantNotFoundError: 'Restaurant not found',
  dateFormatError: 'Date must be of format YYYY-MM-DD',
  hqNotFound: 'HQ not found',
  voucherCode: 'VOUCHER CODE',
  availableQty: 'AVAILABLE QUANTITY',
  unavailableQty: 'UNAVAILABLE QUANTITY',
  orderNumber: 'ORDER NUMBER',
  orderDate: 'ORDER DATE',
  voucherReportHeadingCaps: 'VOUCHER REPORT TITLE',
  voucherReportSheetName: 'Voucher Report',
  voucherReportFileName: 'Voucher_Report',
  eodReport: 'End Of Day Report',
  eodReportOverRange: 'EOD Report Summary Over Date Range',
  eodReportFutureDateError: 'You cannot download the EOD Report for future date',
  eodReportActiveOrderError:
    'Please complete or cancel all active orders before generating EOD Report.',
  couponNotUsed: 'COUPON NOT USED',
  invalidStartDateFormatError: 'Either invalid start_date or invalid start_date format',
  invalidEndDateFormatError: 'Either invalid end_date or invalid end_date format',
  endDateLowerThanStartError: 'End Date cannot be lower than Start Date',
  '90daysDateRangeError': 'Date range should lie within 90 days',
  totalSales: 'TOTAL SALES',
  totalOrders: 'TOTAL ORDERS',
  govtTax: 'GOVERNMENT TAX',
  netSales: 'NET SALES',
  avgSalesPerOrder: 'AVERAGE NET SALES PER ORDER',
  avgNetSales: 'AVERAGE NET SALES',
  totalCustomers: 'TOTAL CUSTOMERS',
  avgSalesPerCustomer: 'AVERAGE NET SALES PER CUSTOMER',
  salesOverTimeReportHeadingCaps: 'SALES OVER TIME',
  salesOverTimeReportSheetName: 'Sales Over Time',
  salesOverTimeReportFileName: 'Sales_Over_Time',
  totalSalesFooter: 'Total Sales, TS = Gross Sales, Sum of Bill Total of all Orders',
  totalOrdersFooter: 'Total Orders = Count of all Orders Completed and Paid on given day',
  netSalesFooter: 'Net Sales (NS) = Total Sales (TS) - Delivery Fee (DL) - Govt. Tax (GT)',
  avgNetSalesPerOrderFooter:
    '(ANS perO = NS/ TO) Average Net Sales per Order = Net Sales / Total Orders',
  avgNetSalesPerCustomerFooter:
    '(ANS perC = NS/ TC) Average Net Sales per Customer = Net Sales / Total Customers',
  totalCustomersFooter:
    'Total Customers = Count of Customers who placed and paid orders on given day',
  salesReportPlatform: 'PLATFORM (A)',
  salesReportTotalSales: 'TOTAL SALES (B)',
  salesReportTotalOrders: 'TOTAL ORDERS (C)',
  salesReportCommission: 'COMMISSION (D)',
  salesReportAllCharges: 'ALL CHARGES (E)',
  salesReportNetSales: 'NET SALES (F=B-D-E)',
  salesReportAvgNetSales: 'AVG. NET SALES (G=F/C)',
  salesByPlatformReportHeadingCaps: 'SALES BY PLATFORM OVER TIME',
  salesByPlatformReportFileName: 'SALES_BY_PLATFORM_OVER_TIME',
  transactionChannel: 'TRANSACTION CHANNEL',
  totalTransactions: 'TOTAL TRANSACTIONS',
  salesByTransactionReportHeadingCaps: 'SALES BY TRANSACTION CHANNEL',
  salesByTransactionReportSheetName: 'Sales By Transaction',
  salesByTransactionReportFileName: 'Sales_By_Transaction_Channel',
  offlineFooter:
    'Offline = Includes all transactions outside EasyEat App = Cash, Grab Offline, etc.',
  onlineFooter:
    'Online = Includes all transactions done on EasyEat App = Online Banking, E-Wallets, etc.',
  avgNetSalesFooter:
    'ANS = NS/ TT; Average Net Sales = Net Sales / Total Transactions on given day',
  totalTransactionsFooter:
    'Total Transactions = Count of all transactions for all Order Completed and Paid on given day (single order may include multiple transactions)',
  paymentMethod: 'PAYMENT METHOD',
  paymentChannel: 'PAYMENT CHANNEL',
  avgTransactionAmount: 'AVERAGE TRANSACTION AMOUNT',
  salesByPaymentReportHeadingCaps: 'SALES BY PAYMENT CHANNEL',
  salesByPaymentReportSheetName: 'Sales By Payment',
  salesByPaymentReportFileName: 'Sales_By_Payment_Channel',
  noOrderFoundError: 'No orders found',
  noBillsFoundError: 'No Bills found',
  transactionId: 'TRANSACTION ID',
  amount: 'AMOUNT',
  reportOverTime: 'REPORT OVER TIME',
  paymentMethodReportSheetName: 'Payment Method Report',
  paymentMethodReportFileName: 'Payment_Method_Report_Over_Time',
  cashManagementNotFoundError: 'No cash management system found',
  txnEntryNotFoundError: 'No transaction entry found',
  staff: 'STAFF',
  type: 'TYPE',
  cashTxn: 'Cash Transactions',
  cashTxnReportFileName: 'cash_transactions',
  avgTransactionAmountFormula: 'AVG TRANSACTION AMOUNT = TOTAL SALES / TOTAL TRANSACTIONS',
  endDataIsGrtThenStart: 'end_date must be greater than start_date',
  hqIdToBePresent: 'hq_id should be present',
  hqIdNotSentError: 'Please send hq id',
  hqNotExist: 'Hq does not exist',
  uploadFile: 'Please upload a file!',
  userSegNotFound: 'For given Hq, User Segments not found.',
  successfullyDeleted: 'Successfully deleted!',
  segmentAlreadyExist: 'Already exist with same customer group name',
  dialCode: 'dial_code',
  phone: 'phone',
  email: 'email',
  csvUploadHeaderMisMatched:
    'Headers mismatched. Please upload file with correct header format. Correct headers: name, dial_code, phone, email',
  notEntriesFound: 'No Entries found',
  customerGroupSuccess: 'Customer group created successfully',
  SomeDataMissing: 'some data is missing in the uploaded file',
  uploadFileWithValidFormat: 'please upload file with the valid format of dial_code/phone',
  campaignNotExist: 'Campaign does not exist',
  campaignIdToBePresent: 'Campaign id should be present',
  billCalculateError: 'Unable to get cost details',
  campaignSuccessDeleteMsg: 'Marketing campaign deleted successfully.',
  campaignAlreadyDeleted: 'Marketing campaign already deleted.',
  campaignNotFound: 'Marketing campaign not found to delete',
  campaignExecutedMail:
    'Your marketing campaign was successfully executed. Campaign details are as follows',
  customerGroupIdToBeExist: 'Customer groups id should exist',
  atLeastOneCustomerGroupIdToBeExist: 'At least one customer_group_id should be there',
  smsToBePresent: 'Template should be present',
  unableToGetJson: 'Unable to get json from link.',
  campaignExecuted: 'Campaign successfully created',
  campaignNotCreated: 'Not able to create campaign please try again.',
  campaignName: 'Campaign Name',
  billId: 'Bill ID',
  name: 'Name',
  campaignCost: 'Campaign Cost',
  uniqueSmsNote: 'Note: Customers falling in multiple groups are sent only one SMS.',
  customerGroup: 'Customer Group',
  customersCount: 'No. of Customers',
  totalSms: 'Total SMS',
  freeSms: 'Free SMS',
  smsToPay: 'SMS to pay for',
  amountToBePaid: 'Amount to be paid',
  invoice: 'Invoice',
  marketingCampaign: 'Marketing campaign',
  campaignSuccessMsg: 'Campaign executed successfully',
  csvFileError: 'Csv Files are not in Exact shape',
  amountSMSConflict: 'Amount to be paid/free sms credits mismatched, try again!',
  finalAmount: 'Final Amount',
  marketingReportName: 'MARKETING CAMPAIGN UNPAID INVOICE REPORT',
  marketingCampaignSheetName: 'Marketing campaign bill',
  marketingCampaignXlsxSheetName: 'Marketing campaign unpaid bill.xlsx',
  couponNotFound: 'Coupon not found',
  deleteCouponCantUpdate: "You can't update a deleted coupon",
  nothingUpdated: 'Nothing was updated',
  alreadyExist: 'already exists',
  couponUpdatedSuccess: 'Coupon updated successfully',
  couponDeletedSuccess: 'Coupon deleted successfully',
  couponAlreadyDeleted: 'Coupon already deleted',
  headerCsvMismatchedVoucher:
    'Headers mismatched, please check header, correct header is voucher-codes and retry!',
  duplicateEntriesFor: 'duplicate entry for',
  atIndex: 'at index',
  voucherCodeNotAtRow: 'voucher code not available at row ',
  noRestHqFoundError: 'No Restaurant HQ Found',
  couponTitle: 'Coupon title',
  voucherNotCreated: 'Voucher not created',
  voucherCreatedSuccess: 'Voucher created successfully',
  orderDetailsNotFoundError: 'Order details not found',
  orderBillNotFoundError: 'Order bill details not found',
  voucherNotExist: 'Voucher does not exists.',
  voucherInvalidMoment: 'Voucher is invalid at the moment.',
  voucherInvalidToday: 'Voucher is invalid today.',
  voucherLimitExceed: 'Voucher limit exceeded.',
  voucherAppliedSuccessfully: 'Voucher applied successfully.',
  voucherItemQNotSatisfied: 'Voucher item quantity is not satisfied',
  voucherItemsRedeem:
    'Either voucher item/items is/are already redeemed Or no voucher item/items found to redeem.',
  voucherItemsNotFoundToRedeem: 'No voucher item/items found to redeem.',
  nothingWasDeleted: 'Nothing was deleted',
  voucherDeleteSuccess: 'voucher deleted successfully',
  voucherNotFound: 'Voucher not found',
  deletedVoucherCantUpdate: "You can't update a deleted voucher title",
  voucherItemAddedSuccess: 'Voucher item details added in order successfully',
  voucherItemAddedError: 'Voucher item details could not added in order',
  voucherRedeemQuantityUpdateSuccess: 'Voucher redeemed quantity updated in order successfully',
  voucherRedeemQuantityUpdateError: 'Voucher redeemed quantity could not updated in order',
  orderBillUpdateSuccess: 'Bill updated successfully',
  orderBillUpdateError: 'Bill not update',
  voucherNotAppliedIn: 'Voucher not applied in bill',
  voucherDetailsAddedOrderSuccess: 'Voucher details added in order successfully',
  voucherDetailsAddedOrderError: 'Voucher details could not added in order',
  voucherDetailsCouldNotBeUpdated: 'Voucher details could not be updated',
  voucherDetailsUpdatedSuccess: 'Voucher details updated successfully',
  voucherCantAppliedOn: "Voucher can't be applied on",
  minimumCartValueIs: 'Minimum cart value is',
  needToAddItemsWorth: 'You need to add items worth',
  moreToRedeemToCode: 'more to redeem this voucher code.',
  orderDetailsForOrder: 'Order Details for order id',
  orderBillForOrder: 'Order Bill  Details for order id',
  notFound: 'not found',
  notFoundInOrder: 'not found in order',
  voucherNotRemovedUsedVoucher: 'voucher is not remove from used-voucher',
  voucherRemovedSuccess: 'voucher remove successfully',
  voucherRemovedError: 'voucher not remove from order',
  templateNotFound: 'Template Not Found',
  priceCutCouponNotFound: 'Price cut coupon not found',
  deleteCouponCantBeUpdate: 'Deleted coupon can not be updated',
  itemAlreadyAddedPriceCut:
    'One or more items in your selection has already been used in price cut promotion. Promotion with the best offer on item would be applied automatically.',
  masterCard: 'MASTERCARD (MC)',
  visa: 'VISA (V)',
  amex: 'AMERICAN EXPRESS',
  eodReportHeader: 'EOD Report For ',
  sales: 'SALES',
  totalItemSales: 'TOTAL ITEM SALES (TIS)',
  topup: 'TOPUP (T)',
  promotions: 'PROMOTIONS (P)',
  platformCommission: 'PLATFORM COMMISSION (PC)',
  netSalesEOD: 'NET SALES (NS)',
  deliveryCharges: 'DELIVERY CHARGES (DC)',
  serviceChargesEOD: 'SERVICE CHARGES (SC)',
  packagingChargesEOD: 'PACKAGING CHARGES (PKC)',
  roundoffEOD: 'ROUND OFF (RO)',
  governmentTax: 'GOVERNMENT TAX (GT)',
  governmentTaxPercent: 'GOVERNMENT TAX (%)',
  totalCollection: 'TOTAL COLLECTION (TC)',
  orders: 'ORDERS',
  dineInEOD: 'DINE IN (DI)',
  ordersByCustomers: 'ORDERS BY CUSTOMERS',
  ordersByStaff: 'ORDERS BY STAFF',
  avgSalesOrder: 'AVERAGE SALES/ORDER',
  deliveryEOD: 'DELIVERY (DL)',
  pickup: 'PICK-UP (PU)',
  cancelledOrders: 'CANCELLED ORDERS (CO)',
  voidItems: 'VOID ITEMS (VI)',
  paymentDetails: 'PAYMENT DETAILS',
  paymentCollection: 'PAYMENT COLLECTION (PYC)',
  refund: 'REFUND (RF)',
  cashSales: 'CASH SALES (CS)',
  offlineInfo: 'OFFLINE = This means payment done by customer in-store (outside Easyeat App)',
  offlineCreditCard: 'OFFLINE CREDIT CARD (CCO)',
  offlineWallets: 'OFFLINE WALLETS (OW)',
  offlineFPX: 'OFFLINE FPX (OFPX)',
  easyEatCollection: 'EASYEAT COLLECTION (EEC)',
  wallet: 'WALLET (WA)',
  internetBanking: 'INTERNET BANKING (FPX)',
  promotionsAndCommissions: 'PROMOTIONS & COMMISSIONS',
  userAppPromotions: 'USER APP PROMOTIONS (UAP)',
  manual: 'MANUAL (OP)',
  avgSalesPAX: 'AVERAGE SALES/PAX',
  offline: 'OFFLINE',
  offlineMessage: 'This means payment done by customer in-store (outside Easyeat App)',
  invoice_no: 'Invoice No',
  no_of_items: 'NUMBER OF ITEMS',
  table: 'Table No',
  order_seq: 'Order No',
  payment_type: 'Payment Type',
  paid: 'Paid',
  unpaid: 'Unpaid',
  cashier: 'Cashier',
  customer_phone: 'CUSTOMER PHONE',
  customer_name: 'CUSTOMER NAME',
  staff_name: 'STAFF NAME',
  dine_in: 'Dine-In',
  takeaway: 'Takeaway',
  noOfItemsVoid: 'No of items voided',
  tableTransfer: 'Table Transfer',
  opening_cash_float: 'OPENING CASH FLOAT',
  total_cash_in: 'TOTAL CASH IN',
  cash_in_sales: 'CASH IN SALES',
  cash_in_others: 'CASH IN OTHERS',
  total_cash_out: 'TOTAL CASH OUT',
  net_cash_balance: 'NET CASH BALANCE',
  expected_cash_in_drawer: 'EXPECTED CASH IN DRAWER',
  actual_cash_in_drawer: 'ACTUAL CASH IN DRAWER',
  excess_short_cash: 'EXCESS/SHORT',
  close_cashier: 'CLOSE CASHIER',
  drawer_kick: 'Drawer Kick',
  open_cashier: 'Open Cashier',
  cash_in: 'Cash-In',
  cash_out: 'Cash-Out',
  powered_by: 'POWERED BY',
  old: 'OLD',
  new: 'NEW',
  notes: 'NOTES',
  addon: 'ADDON',
  variant: 'VARIANT',
  discount: 'Discount',
  delivery_fee: 'Delivery Fee',
  round_off: 'Round Off',
  total_amount: 'Total Amount',
  amount_paid: 'Amount Paid',
  cash_received: 'Cash Received',
  cash_returned: 'Cash Returned',
  txn_id: 'Txn Id',
  item_name: 'Item Name',
  balance: 'BALANCE',
  amount_to_be_paid: 'Amount to be Paid',
  amount_to_refund: 'Amount to Refund',
  bill_date: 'BILL DATE',
  picked_up_from: 'PICKED UP FROM',
  delivered_to: 'DELIVERED TO',
  receipt: 'Receipt',
  thanks_for_ordering: 'Thanks for ordering',
  your_receipt: "Here's your receipt for the",
  quantity: 'Quantity',
  price: 'Price',
  you_ordered_from: 'You ordered from',
  hi: 'Hi',
  greeting_from_EasyEat: 'greeting from EasyEat',
  please_find_attached_receipt: 'Please find the attached receipt for invoice',
  receipt_for_invoice: 'Receipt for Invoice',
  noVoucherInFiles: 'No voucher-codes in file',
  setAtLeastOne: 'Please set at least one limit option',
  invalidCouponLimit: 'Invalid coupon limit value',
  selectApplicableDiscountType: 'Please select applicable discount type',
  selectApplicableDiscountValue: 'Please select applicable discount value',
  'applicableCantBeMoreThan100 ': 'Applicable discount value cannot be greater than 100%',
  email_sent_successfully: 'Email Sent Successfully',
  cashier_closed_cash_in_error: 'Cashier is closed, to CASH-IN, open cashier first',
  cashier_closed_cash_out_error: 'Cashier is closed, to CASH-OUT, open cashier first',
  cashier_open_error: 'Cashier is already opened',
  cashier_closed_error: 'Cashier is already closed',
  please_provide_valid_amount: 'Please provide a valid amount to',
  cash_in_done_successfully: 'CASH-IN done successfully',
  done_successfully: 'done successfully',
  'cash-in': 'CASH-IN',
  'cash-out': 'CASH-OUT',
  'open-cashier': 'OPEN-CASHIER',
  'close-cashier': 'CLOSE-CASHIER',
  cash_in_hand: 'Cash in hand',
  add_cash_first: 'add Cash first to do',
  complete_active_orders_error:
    'Please complete or cancel all active orders before closing the cashier',
  drawer_opened_successfully: 'Drawer opened successfully',
  cash_management_system_not_found: 'No cash management system found',
  close_cashier_for_cashier_report: 'To obtain cashier report, close the cashier first',
  no_entries_found: 'No entries found',
  status: 'STATUS',
  no_reviews_found: 'No reviews found',
  rest_not_related_to_hq_error: 'The given restaurant_ids are not related to the current hq',
  outlet_name: 'OUTLET NAME',
  dial_code: 'DIAL CODE',
  phone_number: 'PHONE NUMBER',
  review: 'REVIEW',
  ratings: 'RATINGS',
  order_type: 'ORDER TYPE',
  restaurant: 'Restaurant',
  review_report_over_time: 'Review Report over Time',
  no_data_found: 'No Data Found',
  latest_date_of_purchase: 'Latest Date of Purchase',
  total_purchases_made: 'Total Purchases Made',
  whatsapp_link: 'Whatsapp Link',
  user_data_report_file_header: 'User Data For All Restaurants',
  user_data_sheet_name: 'Restaurants User Data',
  user_data_report_filename: 'Restaurants_User_Data',
  allergies: 'ALLERGIES',
  outermostIndex: 'In outermost array at index ',
  valueCanBeApplyArray: 'value can only be type array',
  inArrayAtIndex: 'in inner array at index',
  inInnerArrayAtIndex: 'in innermost array value at index',
  canOnlyBeNumber: 'can only be number',
  unmapped_item_text:
    'Go to Sections & Counters on EasyEat Partner App to map these items to counters',
  invalid_counter_text:
    'Counters set for these items are invalid & overriding the counters of their subcategories',
  master_counter_text:
    'These are new items added to this order by the customer. Refer to previous receipts to check older items.',
  canceled_items_text: 'This item is cancelled from this order',
  item_not_available_text: 'Item Not Available',
  items_not_available_text: 'Items Not Available',
  some_items_not_available_text: 'Some Items Not Available',
  order_declined_text: 'This order has been declined',
  items_declined_text: 'These items have been declined from this order',
  signed_by: 'SIGNED BY',
  master_docket: 'Master Docket',
  master_order_list: 'Master Order List',
  void_item: 'Void Item',
  cancel_item: 'Cancel Item',
  item_voided: 'Item Voided',
  declined_order: 'Declined Order',
  cash_not_tallied: 'Cash not tallied',
  'Packaging Charges': 'Packaging Charges',
  SST: 'SST',
  cancelled: 'Cancelled',
  waiting: 'Waiting',
  confirmed: 'Confirmed',
  in_progress: 'In Progress',
  more_items_added: 'More Items Added',
  user_cancelled: 'User Cancelled',
  restaurant_cancelled: 'Restaurant Cancelled',
  system_cancelled: 'System Cancelled',
  deleted: 'Deleted',
  scheduled: 'Scheduled',
  'scheduled_&_accepted': 'Scheduled & Accepted',
  unknown: 'Unknown',
  dateRangeCantExceed90Days: 'Date range cannot be greater than 90 days',
  pickupMain: 'Pickup',
  na: 'NA',
  card: 'CARD (CC)',
  order_no: 'ORDER NO',
  staff_details: 'Staff Details',
  day: 'DAY',
  designation: 'DESIGNATION',
  clock_in: 'CLOCK IN',
  clock_out: 'CLOCK OUT',
  duration_in_hours: 'DURATION (in Hours)',
  inventory_status_report: 'Inventory Status Report',
  report_no: 'REPORT N0',
  order_status: 'ORDER STATUS',
  'Restaurant Details': 'Restaurant Details',
  'Restaurant Charges': 'Restaurant Charges',
  'Offline Platform Details': 'Offline Platform Details',
  'Add Item': 'Add Item',
  'Void Item': 'Void Item',
  'Decline Order': 'Decline Order',
  'Delete Order': 'Delete Order',
  'Add Discount': 'Add Discount',
  'Table Transfer': 'Table Transfer',
  'Menu Item Settings': 'Menu Item Settings',
  'Item Visibility': 'Item Visibility',
  'Item Availability': 'Item Availability',
  Report: 'Report',
  'Generate EOD': 'Generate EOD',
  'Open Cashier': 'Open Cashier',
  'Close Cashier': 'Close Cashier',
  'Add Cash In': 'Add Cash In',
  'Add Cash Out': 'Add Cash Out',
  'Drawer Kick': 'Drawer Kick',
  'Section Settings': 'Section Settings',
  'Printer Settings': 'Printer Settings',
  'Loyalty Settings': 'Loyalty Settings',
  'Inventory List': 'Inventory List',
  'Promotion Settings': 'Promotion Settings',
  'Table Services': 'Table Services',
  'Restaurant Analytics': 'Restaurant Analytics',
  'EasyEat HQ': 'EasyEat HQ',
  'EasyEat Outlets': 'EasyEat Outlets',
  'Manage Staff': 'Manage Staff',
  'Download Data': 'Download Data',
  'Provide Other Employee Access To HQ': 'Provide Other Employee Access To HQ',
  'Provide Other Employee Access To POS': 'Provide Other Employee Access To POS',
  'Roles And Permission': 'Roles And Permission',
  'Table Settings': 'Table Settings',
  'Download Summary': 'Download Summary',
  Settlements: 'Settlements',
  counter_decline_text: 'This item is declined from this order',
  counter_cancel_text: 'This item is canceled from this order',
  voucherReportTitle: 'VOUCHER REPORT TITLE',
  'Restaurant Tax (PB1)': 'Restaurant Tax (PB1)',
  'Service Charge': 'Service Charge',
  table_changed: 'Table Changed',
  payment_mode: 'Payment Mode',
  dish_out_of_stock: 'dish out of stock',
  variant_out_of_stock: 'variant out Of stock',
  addon_out_of_stock: 'add on out of stock',
  'Restaurant Manager': 'Restaurant Manager',
  cannotUpdateServiceCharge: 'Cannot update service charge for this order type',
  serviceChargeNotApplicable: 'Service tax is not applicable on this restaurant',
  serviceChargeNotAdded: 'Service charge not added',
  serviceChargeAdded: 'Service charge added successfully',
  serviceChargeNotRemoved: 'Service charge not removed',
  serviceChargeRemoved: 'Service charge removed successfully',
  unableToUpdateServiceCharge: 'Unable to update Service Charge',
  gluten: 'gluten',
  fish: 'fish',
  nuts: 'nuts',
  'seafood and shellfish': 'seafood and shellfish',
  wheat: 'wheat',
  oats: 'oats',
  barley: 'barley',
  corn: 'corn',
  cashew: 'cashew',
  almonds: 'almonds',
  'fields.address_1 should not be empty': 'fields.address_1 should not be empty',
  'Restaurant details updated successfully': 'Restaurant details updated successfully',
  'Nothing was updated': 'Nothing was updated',
  'Restaurant tables not found': 'Restaurant tables not found',
  'floors not found on this restaurant': 'floors not found on this restaurant',
  floor_id: 'floor_id',
  "doesn't exists": "doesn't exists",
  "You can't add table in": "You can't add table in",
  floor: 'floor',
  'Table number': 'Table number',
  'already exists on': 'already exists on',
  'Table added successfully': 'Table added successfully',
  'Nothing added': 'Nothing added',
  'Table could not be added': 'Table could not be added',
  "You can't delete table from": "You can't delete table from",
  'Please complete or cancel all active orders before delete table details':
    'Please complete or cancel all active orders before delete table details',
  'Table deleted successfully': 'Table deleted successfully',
  'Nothing deleted': 'Nothing deleted',
  'Table could not be deleted': 'Table could not be deleted',
  "You can't update a table in": "You can't update a table in",
  table_id: 'table_id',
  'Please complete or cancel all active orders before update table details':
    'Please complete or cancel all active orders before update table details',
  'Table updated successfully': 'Table updated successfully',
  'Table could not be updated': 'Table could not be updated',
  'Offline platforms tables created for restaurant successfully':
    'Offline platforms tables created for restaurant successfully',
  'No offline platform found on this restaurant': 'No offline platform found on this restaurant',
  'Offline platforms tables created for all restaurants successfully':
    'Offline platforms tables created for all restaurants successfully',
  'Category name already exits': 'Category name already exits',
  'category added successfully': 'category added successfully',
  'category updated successfully': 'category updated successfully',
  'User is not authorized to perform this action': 'User is not authorized to perform this action',
  'User Authorized': 'User Authorized',
  'Please Upload The File First': 'Please Upload The File First',
  "Fields values (except sku,description,category,supplier,item_type) can't be empty.Check at sr. no.":
    "Fields values (except sku,description,category,supplier,item_type) can't be empty.Check at sr. no.",
  'duplicate entry for': 'duplicate entry for',
  'at index': 'at index',
  'Inventory not found': 'Inventory not found',
  'Product Not Found': 'Product Not Found',
  'Product Details For': 'Product Details For',
  'Product Updated Successfully': 'Product Updated Successfully',
  'Product Added Successfully': 'Product Added Successfully',
  'Could NOT Add Product': 'Could NOT Add Product',
  'Invalid Inventory': 'Invalid Inventory',
  'Email Sent Successfully': 'Email Sent Successfully',
  'Could NOT Send Email, Please Check Email Address':
    'Could NOT Send Email, Please Check Email Address',
  'Order Not Found': 'Order Not Found',
  'Order Details For': 'Order Details For',
  'Order Added Successfully': 'Order Added Successfully',
  'Could NOT Add Order': 'Could NOT Add Order',
  'Order Updated Successfully': 'Order Updated Successfully',
  'Orders Removed Successfully': 'Orders Removed Successfully',
  'Orders Not Found To Delete': 'Orders Not Found To Delete',
  'inventory details doest not exist for item': 'inventory details doest not exist for item',
  'Stock Update Not Found': 'Stock Update Not Found',
  'Stock Update Details For': 'Stock Update Details For',
  'Start Date Should Always Less Than End Date': 'Start Date Should Always Less Than End Date',
  'Stock_Update Added Successfully': 'Stock_Update Added Successfully',
  'Stock_Update Already In The Inventory': 'Stock_Update Already In The Inventory',
  'Either Products or Items is empty': 'Either Products or Items is empty',
  'Stock_Update Updated Successfully': 'Stock_Update Updated Successfully',
  'Stock Updates Removed Successfully': 'Stock Updates Removed Successfully',
  'Stock Updates Not Found To Delete': 'Stock Updates Not Found To Delete',
  'Supplier Not Found': 'Supplier Not Found',
  'Supplier Added Successfully': 'Supplier Added Successfully',
  'Supplier Already Added In Inventory': 'Supplier Already Added In Inventory',
  'Supplier Updated Successfully': 'Supplier Updated Successfully',
  'Suppliers Not Found To Delete': 'Suppliers Not Found To Delete',
  'Suppliers Removed Successfully': 'Suppliers Removed Successfully',
  nil: 'NIL',
  paymentDetailsUpdatedSuccess: 'Payment details updated successfully',
  nothingWasUpdated: 'Nothing was updated',
  paymentDetailsNotFound: 'Payment details not found',
  orderBillNotCreated: 'Order bill could not be created',
  orderBillNotUpdated: 'Order bill could not be updated',
  orderBillCreatedSuccess: 'Order bill created successfully',
  orderBillUpdatedSuccess: 'Order bill created successfully',
  unableToUpdateGuestBills: 'Unable to update guest bills',
  guestBillsNotUpdated: 'Guest bills not updated',
  guestBillsUpdated: 'Guest bills updated',
  discountNotApplied: 'Discount not applied',
  discountUpdatedSuccessfully: 'Discount updated successfully',
  'Hi there': 'Hi there',
  createHqEmail:
    'We are excited to have you on board! HQ makes it easy for you to view settlement reports daily for all the outlets. Using marketing for customer groups, you can launch SMS campaigns and increase repeat orders. There is so much more for you here.',
  'Your account has been created with email:': 'Your account has been created with email:',
  'and password': 'and password:',
  'You can reset your password as you like.': 'You can reset your password as you like.',
  'EXPLORE YOUR ACCOUNT': 'EXPLORE YOUR ACCOUNT',
  'With love,': 'With love,',
  'Easy Eat Team': 'Easy Eat Team',
  'Welcome to Easy Eat': 'Welcome to Easy Eat',
  hqCreateMsg:
    'HQ makes it easy for you to view settlement reports daily for all the outlets. Using marketing for customer groups, you can launch SMS campaigns and increase repeat orders. There is so much more for you here.',
  'click the link below to reset or update your password at':
    'click the link below to reset or update your password at',
  'in Easy Eat HQ app': 'in Easy Eat HQ app',
  'Welcome to the team': 'Welcome to the team',
  "It's time to take control over your restaurant with quicker service, increased profits, and simplified workflows":
    "It's time to take control over your restaurant with quicker service, increased profits, and simplified workflows",
  'You have been given employee access at': 'You have been given employee access at',
  'in Easy Eat HQ app! Click the link below to complete your registration':
    'in Easy Eat HQ app! Click the link below to complete your registration',
  'Reset Password': 'Reset Password',
  'Complete Registration': 'Complete Registration',
  "Let's change the food industry with technology":
    "Let's change the food industry with technology",
  'Thank you': 'Thank you',
  'Reset your password at': 'Reset your password at',
  "Welcome! You're now part of": "Welcome! You're now part of",
  'Hi, click the link to update your password at Easy Eat HQ':
    'Hi, click the link to update your password at Easy Eat HQ',
  'Hi, welcome to Easy Eat HQ! Click the link to complete your profile':
    'Hi, welcome to Easy Eat HQ! Click the link to complete your profile',
  'Please provide either user_id or login_email': 'Please provide either user_id or login_email',
  'User Not Found': 'User Not Found',
  'HQ access is not enabled for this staff': 'HQ access is not enabled for this staff',
  'Restaurant HQ Not Found': 'Restaurant HQ Not Found',
  'Unable to send password': 'Unable to send password',
  reset: 'reset',
  creation: 'creation',
  link: 'link',
  Password: 'Password',
  'email sent successfully': 'email sent successfully',
  'sms sent successfully': 'sms sent successfully',
  order: 'Order',
  DELIVERY: 'DELIVERY',
  DINING: 'DINING',
  TAKEAWAY: 'TAKEAWAY',
  'APPROVED BY': 'APPROVED BY',
  'Could not get addons as item_id and restaurant_id are null':
    'Could not get addons as item_id and restaurant_id are null',
  'Addons added successfully': 'Addons added successfully',
  'Failed to add addon': 'Failed to add addon',
  'Addon not found': 'Addon not found',
  'Updated addons for addon_id': 'Updated addons for addon_id',
  'Add-Ons Not updated': 'Add-Ons Not updated',
  'Unable to update Addon': 'Unable to update Addon',
  'Addon updated successfully': 'Addon updated successfully',
  'Category Not Found': 'Category Not Found',
  'Option group not found': 'Option group not found',
  'Following restaurant_ids are invalid': 'Following restaurant_ids are invalid',
  'Unable to add menu option group': 'Unable to add menu option group',
  'Menu option group added successfully': 'Menu option group added successfully',
  'Menu option group updated successfully': 'Menu option group updated successfully',
  'Unable to update menu option group': 'Unable to update menu option group',
  'Menu option group deleted successfully': 'Menu option group deleted successfully',
  'Inventory updated successfully': 'Inventory updated successfully',
  'Item Not Found': 'Item Not Found',
  'Item Deleted Successfully': 'Item Deleted Successfully',
  'Either Item not found! or Item already deleted':
    'Either Item not found! or Item already deleted',
  'No HQ found for this restaurant': 'No HQ found for this restaurant',
  "Set original price of item > 0 to define item's price for dine-in, delivery & takeaway":
    "Set original price of item > 0 to define item's price for dine-in, delivery & takeaway",
  'Category not found in restaurant': 'Category not found in restaurant',
  'Subcategory not found in restaurant': 'Subcategory not found in restaurant',
  'Item name': 'Item name',
  'already exists': 'already exists',
  'Item Code length cannot be greater than 5 characters':
    'Item Code length cannot be greater than 5 characters',
  'Item Code': 'Item Code',
  'You can enter a value upto 10000': 'You can enter a value upto 10000',
  'Either combo_items is not defined or it not an array':
    'Either combo_items is not defined or it not an array',
  'Item with id': 'Item with id',
  'Images deleted successfully': 'Images deleted successfully',
  'Some images failed to delete': 'Some images failed to delete',
  'Thumbnail Path Updated in DB': 'Thumbnail Path Updated in DB',
  'Thumbnail Path Not Updated in DB': 'Thumbnail Path Not Updated in DB',
  "Image To Be Set As Thumbnail Doesn't Exists in DB":
    "Image To Be Set As Thumbnail Doesn't Exists in DB",
  'Image Path Added in DB': 'Image Path Added in DB',
  'Image Path Not Added in DB': 'Image Path Not Added in DB',
  'Thumbnail Path Added in DB': 'Thumbnail Path Added in DB',
  'Thumbnail Path Not Added in DB': 'Thumbnail Path Not Added in DB',
  'Some images failed to upload, please check image type(jpeg,png) and size(<2MB)':
    'Some images failed to upload, please check image type(jpeg,png) and size(<2MB)',
  'Open items default sub_category not found': 'Open items default sub_category not found',
  'Open items default category not found': 'Open items default category not found',
  'Open items not enabled': 'Open items not enabled',
  'Mapping already exists': 'Mapping already exists',
  'Cannot add or update a child row: a foreign key constraint fails':
    'Cannot add or update a child row: a foreign key constraint fails',
  'No mapping Found': 'No mapping Found',
  'Mapping removed successfully': 'Mapping removed successfully',
  'No mapped items found associated with this item':
    'No mapped items found associated with this item',
  'Discount exceed actual price of the combo': 'Discount exceed actual price of the combo',
  'Role Not Found': 'Role Not Found',
  'Please select at least one restaurant': 'Please select at least one restaurant',
  'Role with name': 'Role with name',
  Role: 'Role',
  'Unable to create new role': 'Unable to create new role',
  'Role created successfully': 'Role created successfully',
  'Role name': 'Role name',
  'is reserved, please enter a different role name':
    'is reserved, please enter a different role name',
  'Role not updated': 'Role not updated',
  'Role updated successfully': 'Role updated successfully',
  'Role deleted successfully': 'Role deleted successfully',
  'Ready to clock-in': 'Ready to clock-in',
  'Ready to clock-out': 'Ready to clock-out',
  'Something went wrong': 'Something went wrong',
  'Clock-in Failed': 'Clock-in Failed',
  'Clock-in Successful': 'Clock-in Successful',
  'Staff Not Found': 'Staff Not Found',
  'Clock-out Successful': 'Clock-out Successful',
  'Clock-out Failed': 'Clock-out Failed',
  'Please provide either hq_id or restaurant_ids list':
    'Please provide either hq_id or restaurant_ids list',
  'Please enter at least one restaurant_id': 'Please enter at least one restaurant_id',
  'You are not authorised to perform this action': 'You are not authorised to perform this action',
  'Email ID cannot be empty': 'Email ID cannot be empty',
  'PIN cannot be empty': 'PIN cannot be empty',
  'This email is already taken': 'This email is already taken',
  'PIN already exists': 'PIN already exists',
  'your login PIN to access Easy Eat POS is': 'your login PIN to access Easy Eat POS is',
  "Please don't share this with anyone. Visit": "Please don't share this with anyone. Visit",
  'You are not authorised to provide role with HQ access':
    'You are not authorised to provide role with HQ access',
  'You are not authorised to provide role with POS access':
    'You are not authorised to provide role with POS access',
  'Unable to update staff details': 'Unable to update staff details',
  'Staff details updated successfully': 'Staff details updated successfully',
  'No image uploaded': 'No image uploaded',
  'user_id cannot be empty': 'user_id cannot be empty',
  'Unable to upload image': 'Unable to upload image',
  'Staff details deleted': 'Staff details deleted',
  'Item could not be deleted': 'Item could not be deleted',
  noCustomerExistInSelected: 'No customers exist in the selected customer group.',
  noGrabOrderCreated: 'No Grabfood order created',
  newOrderCreated: 'new order(s) created',
  unmappedItems: 'Unmapped items',
  foundIn: 'found in',
  createManually: 'order(s) not created. Please create the order(s) manually.',
  noNewGrabOrderFound: 'No new Grabfood orders found',
  'end_date cannot be less than start_date': 'end_date cannot be less than start_date',
  'Unable to update commissions': 'Unable to update commissions',
  'Commission structure updated successfully': 'Commission structure updated successfully',
  'Nothing to update': 'Nothing to update',
  'Restaurant with id': 'Restaurant with id',
  'Fee details for id': 'Fee details for id',
  'Tax/Charge added successfully': 'Tax/Charge added successfully',
  'Fee details updated successfully': 'Fee details updated successfully',
  'Fee details not found': 'Fee details not found',
  'Fee details removed successfully': 'Fee details removed successfully',
  'Fee details already deleted': 'Fee details already deleted',
  'Fee not found to delete': 'Fee not found to delete',
  'Platforms not found': 'Platforms not found',
  'Platform not exists on Easyeat': 'Platform not exists on Easyeat',
  'Platform Added successfully': 'Platform Added successfully',
  'Platform already added': 'Platform already added',
  'Platform Updated successfully': 'Platform Updated successfully',
  'Please complete or cancel all active orders on this platform before deletion':
    'Please complete or cancel all active orders on this platform before deletion',
  'Platform removed successfully': 'Platform removed successfully',
  'Platform already removed': 'Platform already removed',
  'Table not found': 'Table not found',
  'Restaurant tables  not found': 'Restaurant tables  not found',
  'Eod Update': 'Eod Update',
  'opening cash float': 'opening cash float',
  'cash float change': 'cash float change',
  'customer refund': 'customer refund',
  purchases: 'purchases',
  'paid to staff': 'paid to staff',
  'cancel order': 'cancel order',
  tip: 'tip',
  'sell non-menu items': 'sell non-menu items',
  'customer change request': 'customer change request',
  'drawer-kick': 'drawer-kick',
  easyEatAddress:
    'Easy Eat, Floor 38 Mercu 2, 3 Jalan Bangsar, KL Eco City, 59200 Kuala Lumpur, W.P Kuala Lumpur',
  tableNoUpdated: 'Table no updated successfully',
  nothingUpdatedTable: 'Nothing was updated',
  orderNotFoundTable: 'Order not found',
  tableNoCannotBeUpdated: "Table no can't be updated.",
  tableNotFound: 'Table not found',
  tableLiesIn: 'This table lies in',
  tableCantBeUpdated: "floor, so table can't be updated",
  'Section could not be added': 'Section could not be added',
  'Section added successfully': 'Section added successfully',
  'Floor name already exists': 'Floor name already exists',
  "This floor can't be deleted": "This floor can't be deleted",
  'Please complete or cancel all active orders before delete section details':
    'Please complete or cancel all active orders before delete section details',
  'Section deleted successfully': 'Section deleted successfully',
  'Section could not be deleted': 'Section could not be deleted',
  "This floor can't be updated": "This floor can't be updated",
  'does not exists': 'does not exists',
  'Please complete or cancel all active orders before update section details':
    'Please complete or cancel all active orders before update section details',
  'Section updated successfully': 'Section updated successfully',
  'Nothing updated': 'Nothing updated',
  'Section could not be updated': 'Section could not be updated',
  'Either row or column position for a table is out of floor rows and columns specification, or row and column values are negative':
    'Either row or column position for a table is out of floor rows and columns specification, or row and column values are negative',
  'Please complete or cancel all active orders before removing tables from layout':
    'Please complete or cancel all active orders before removing tables from layout',
  'both values of row and column values either can be only number or null':
    'both values of row and column values either can be only number or null',
  id: 'id',
  ids: 'ids',
  "doesn't": "doesn't",
  "don't": "don't",
  exists: 'exists',
  exist: 'exist',
  'Layout saved successfully': 'Layout saved successfully',
  'Nothing saved': 'Nothing saved',
  'Layout could not be saved': 'Layout could not be saved',
  'To delete': 'To delete',
  Table: 'table',
  'please contact Admin': 'please contact Admin',
  'Deletion setting is enable for': 'Deletion setting is enable for',
  'Settings updated successfully': 'Settings updated successfully',
  'Unable to update image': 'Unable to update image',
  'Image updated successfully': 'Image updated successfully',
  restaurant_ids_cannot_be_empty: 'restaurant_ids cannot be empty',
  invalid_restaurant: 'Invalid Restaurant',
  provide_both_start_and_end_date: 'Provide both start_date & end_date',
  invalid_start_date: 'Invalid start_date',
  invalid_end_date: 'Invalid end_date',
  settlement_history: 'Settlement History',
  settled_order_details: 'Settled Order Details',
  settled_adjustment_details: 'Settled Adjustment Details',
  no_parameters_specified: 'No parameters specified',
  settlement_not_found: 'Settlement Not Found',
  settlement_id: 'SETTLEMENT ID',
  restaurant_id: 'RESTAURANT ID',
  message: 'MESSAGE',
  date_and_time: 'DATE & TIME',
  transaction: 'TRANSACTION',
  transaction_amount: 'TRANSACTION AMOUNT',
  paid_by_customer: 'Paid by customer',
  paid_to_customer: 'Paid to customer',
  easyeat_collection: 'EASYEAT COLLECTION',
  easyeat_cashback: 'EASYEAT CASHBACK',
  restaurant_cashback: 'RESTAURANT CASHBACK',
  technology_charge: 'TECHNOLOGY CHARGE',
  payment_gateway_charge: 'PAYMENT GATEWAY CHARGE',
  amount_payable: 'AMOUNT PAYABLE',
  applicable_tech_charges: 'APPLICABLE TECH CHARGES',
  applicable_pg_charges: 'APPLICABLE PG CHARGES',
  adjustment: 'ADJUSTMENT',
  remarks: 'REMARKS',
  ID: 'ID',
  'Created On': 'Created On',
  'Finish At': 'Finish At',
  'Stock Update List Report': 'Stock Update List Report',
  'Stock Update Over Time': 'Stock Update Over Time',
  'Payment deleted successfully': 'Payment deleted successfully',
};

module.exports = { enKeys };
