const idKeys = {
  createdDate: 'TANGGAL DIBUAT',
  createdTime: 'WAKTU DIBUAT',
  serialNumber: 'SR NO.',
  invoiceNumber: 'TAGIHAN NO.',
  numItems: 'JUMLAH ITEM',
  pax: 'PAX',
  platform: 'PLATFORM',
  completedDate: 'TANGGAL SELESAI',
  completedTime: 'WAKTU SELESAI',
  amountPaid: 'JUMLAH LUNAS',
  itemTotal: 'TOTAL ITEM',
  billTotal: 'TOTAL TAGIHAN',
  refunds: 'REFUND',
  commission: 'KOMISI',
  promotion: 'PROMOSI',
  serviceCharges: 'BIAYA LAYANAN',
  packagingCharges: 'BIAYA KEMASAN',
  tax: 'PAJAK',
  deliveryFee: 'BIAYA PESAN ANTAR',
  roundOff: 'PEMBULATAN',
  paymentMode: 'MODE PEMBAYARAN',
  orderReportHeadingCaps: 'LAPORAN PESANAN SEIRING WAKTU',
  orderReportSheetName: 'Laporan Pesanan Seiring Waktu',
  orderReportFileName: 'Laporan_Pesanan_Seiring_Waktu',
  thanksReportFooter: 'Terima Kasih & Salam',
  contactReportFooter: 'Jika ada pertanyaan, hubungi: hello@easyeat.ai',
  greatDay: 'Semoga hari Anda menyenangkan!',
  dineIn: 'Makan di Tempat',
  delivery: 'Pesan Antar',
  takeAway: 'Take Away',
  itemCategory: 'KATEGORI',
  itemSubCategory: 'SUB-KATEGORI',
  itemCode: 'KODE ITEM',
  itemName: 'NAMA ITEM',
  variationsOptions: 'OPSI VARIASI',
  itemQuantity: 'KUANTITAS',
  averagePrice: 'HARGA RATA-RATA',
  total: 'TOTAL',
  availability: 'KETERSEDIAAN',
  dishReportHeadingCaps: 'LAPORAN HIDANGAN SEIRING WAKTU',
  dishReportSheetName: 'Laporan Hidangan Seiring Waktu',
  dishReportFileName: 'Laporan_Hidangan_Seiring_Waktu',
  available: 'Tersedia',
  unavailable: 'Tidak Tersedia',
  addOnName: 'NAMA ADD-ON',
  quantitySold: 'KUANTITAS TERJUAL',
  addOnReportHeadingCaps: 'LAPORAN ADD-ON SEIRING WAKTU',
  completed: 'Selesai',
  canceled: 'Dibatalkan',
  customerCancelled: 'Pelanggan Membatalkan',
  restaurantCancelled: 'Restoran Membatalkan',
  expired: 'Kedaluwarsa',
  date: 'TANGGAL',
  time: 'WAKTU',
  item: 'ITEM',
  category: 'KATEGORI',
  quantityVoided: 'JUMLAH DIBATALKAN',
  totalPrice: 'TOTAL HARGA',
  voidedBy: 'DIBATALKAN OLEH',
  reason: 'ALASAN',
  voidReportHeadingCaps: 'LAPORAN ITEM BATAL SEIRING WAKTU',
  couponCode: 'KODE-KUPON',
  title: 'JUDUL',
  channel: 'KANAL',
  appliedTimes: 'WAKTU DITERAPKAN',
  totalDiscounts: 'DISKON TOTAL',
  promotionReportHeadingCaps: 'LAPORAN PROMOSI SEIRING WAKTU',
  promotionReportSheetName: 'Laporan Promosi Berdasarkan Tanggal',
  promotionReportFileName: 'Laporan_Promosi_Seiring_Waktu',
  eeCustomerApp: 'Aplikasi Pelanggan EasyEat',
  pos: 'POS',
  manualTopUp: 'Top-up Manual',
  reasonNotMentioned: 'Alasan tidak disebutkan oleh staf',
  manualDiscount: 'Diskon Manual',
  restaurantNotFoundError: 'Restoran tidak ditemukan',
  dateFormatError: 'Tanggal harus dalam format YYYY-MM-DD',
  hqNotFound: 'HQ tidak ditemukan',
  voucherCode: 'KODE VOUCHER',
  availableQty: 'KUANTITAS TERSEDIA',
  unavailableQty: 'KUANTITAS TIDAK TERSEDIA',
  orderNumber: 'NOMOR PESANAN',
  orderDate: 'TANGGAL PEMESANAN',
  voucherReportHeadingCaps: 'JUDUL LAPORAN VOUCHER',
  voucherReportSheetName: 'Laporan Voucher',
  voucherReportFileName: 'Laporan_Voucher',
  eodReport: 'Laporan Akhir Hari',
  eodReportOverRange: 'Ringkasan Laporan EOD Selama Rentang Tanggal',
  eodReportFutureDateError: 'Anda tidak dapat mengunduh Laporan EOD untuk tanggal mendatang',
  eodReportActiveOrderError:
    'Harap selesaikan atau batalkan semua pesanan aktif sebelum membuat Laporan EOD.',
  couponNotUsed: 'KUPON TIDAK DIGUNAKAN',
  invalidStartDateFormatError: 'Tanggal_mulai atau format tanggal_mulai tidak valid',
  invalidEndDateFormatError: 'Tanggal akhir atau format tanggal akhir tidak valid',
  endDateLowerThanStartError: 'Tanggal Akhir tidak boleh lebih awal dari Tanggal Mulai',
  '90daysDateRangeError': 'Rentang tanggal harus berada di antara 90 hari',
  totalSales: 'TOTAL PENJUALAN',
  totalOrders: 'TOTAL PESANAN',
  govtTax: 'PAJAK PEMERINTAH',
  netSales: 'PENJUALAN NETO',
  avgSalesPerOrder: 'RATA-RATA PENJUALAN NETO PER PESANAN',
  avgNetSales: 'RATA-RATA PENJUALAN NETO',
  totalCustomers: 'TOTAL PELANGGAN',
  avgSalesPerCustomer: 'RATA-RATA PENJUALAN NETO PER PELANGGAN',
  salesOverTimeReportHeadingCaps: 'PENJUALAN SEIRING WAKTU',
  salesOverTimeReportSheetName: 'Penjualan Seiring Waktu',
  salesOverTimeReportFileName: 'Penjualan_Seiring_Waktu',
  totalSalesFooter: 'Total Penjualan, TS = Penjualan Bruto, Jumlah Total Tagihan semua Pesanan',
  totalOrdersFooter: 'Total Pesanan = Hitungan semua Pesanan Selesai dan Lunas pada hari tertentu',
  netSalesFooter:
    'Penjualan Neto (NS) = Total Penjualan (TS) - Biaya Pengiriman (DL) - Pajak Pemerintah (GT)',
  avgNetSalesPerOrderFooter:
    '(ANS perO = NS / TO) Rata-Rata Penjualan Neto per Pesanan = Penjualan Neto / Total Pesanan',
  avgNetSalesPerCustomerFooter:
    '(ANS perC = NS / TC) Rata-Rata Penjualan Neto per Pelanggan = Penjualan Neto / Total Pelanggan',
  totalCustomersFooter:
    'Total Pelanggan = Jumlah Pelanggan yang membuat dan membayar pesanan pada hari tertentu',
  salesReportPlatform: 'PLATFORM (A)',
  salesReportTotalSales: 'TOTAL PENJUALAN (B)',
  salesReportTotalOrders: 'TOTAL PESANAN (C)',
  salesReportCommission: 'KOMISI (D)',
  salesReportAllCharges: 'SEMUA BIAYA (E)',
  salesReportNetSales: 'PENJUALAN NETO (F=B-D-E)',
  salesReportAvgNetSales: 'RATA-RATA PENJUALAN NETO (G=F/C)',
  salesByPlatformReportHeadingCaps: 'PENJUALAN BERDASARKAN PLATFORM SEIRING WAKTU',
  salesByPlatformReportFileName: 'Penjualan_Berdasarkan_Platform_Seiring_Waktu',
  transactionChannel: 'KANAL TRANSAKSI',
  totalTransactions: 'TOTAL TRANSAKSI',
  salesByTransactionReportHeadingCaps: 'PENJUALAN BERDASARKAN KANAL TRANSAKSI',
  salesByTransactionReportSheetName: 'Penjualan Berdasarkan Transaksi',
  salesByTransactionReportFileName: 'Penjualan_Berdasarkan_Kanal_Transaksi',
  offlineFooter:
    'Offline = Termasuk semua transaksi di luar EasyEat App = Tunai, Grab Offline, dll.',
  onlineFooter:
    'Online = Termasuk semua transaksi di Aplikasi EasyEat = Online Banking, E-Wallet, dll.',
  avgNetSalesFooter:
    'ANS = NS / TT; Rata-Rata Penjualan Neto = Penjualan Neto / Total Transaksi pada hari tertentu',
  totalTransactionsFooter:
    'Total Transaksi = Hitungan semua transaksi untuk semua Pesanan Selesai dan Lunas pada hari tertentu (pesanan tunggal dapat mencakup beberapa transaksi)',
  paymentMethod: 'METODE PEMBAYARAN',
  paymentChannel: 'KANAL PEMBAYARAN',
  avgTransactionAmount: 'RATA-RATA JUMLAH TRANSAKSI',
  salesByPaymentReportHeadingCaps: 'PENJUALAN BERDASARKAN KANAL PEMBAYARAN',
  salesByPaymentReportSheetName: 'Penjualan Berdasarkan Pembayaran',
  salesByPaymentReportFileName: 'Penjualan_Berdasarkan_Kanal_Pembayaran',
  noOrderFoundError: 'Tidak Ada Pesanan Ditemukan',
  noBillsFoundError: 'Tagihan Tidak Ditemukan',
  transactionId: 'ID TRANSAKSI',
  amount: 'JUMLAH',
  reportOverTime: 'LAPORAN SEIRING WAKTU',
  paymentMethodReportSheetName: 'Laporan Metode Pembayaran',
  paymentMethodReportFileName: 'Laporan_Metode_Pembayaran_Seiring_Waktu',
  cashManagementNotFoundError: 'Sistem manajemen kas tidak ditemukan',
  txnEntryNotFoundError: 'Tidak ada entri transaksi yang ditemukan',
  staff: 'STAF',
  type: 'TIPE',
  cashTxn: 'Transaksi Tunai',
  cashTxnReportFileName: 'transaksi_tunai',
  avgTransactionAmountFormula: 'JUMLAH_RATARATA_TRANSAKSI = TOTAL_PENJUALAN / TOTAL_TRANSAKSI',
  endDataIsGrtThenStart: 'Tanggal Akhir harus lewat dari Tanggal Mulai',
  hqIdToBePresent: 'hq_id harus ada',
  hqIdNotSentError: 'Harap kirim hq id',
  hqNotExist: 'HQ tidak ada',
  uploadFile: 'Silakan unggah file!',
  userSegNotFound: 'Untuk HQ yang diberikan, Segmen Pengguna tidak ditemukan.',
  successfullyDeleted: 'Berhasil dihapus!',
  segmentAlreadyExist: 'Sudah ada dengan nama grup pelanggan yang sama',
  dialCode: 'kode_panggilan',
  phone: 'telepon',
  email: 'email',
  csvUploadHeaderMisMatched:
    "Header tidak cocok. Harap unggah file dengan format header yang benar. Header yang benar: 'nama', 'kode_panggilan', 'telepon', 'email'",
  notEntriesFound: 'Entri tidak ditemukan',
  customerGroupSuccess: 'Grup pelanggan berhasil dibuat',
  SomeDataMissing: 'beberapa data hilang dalam file yang diunggah',
  uploadFileWithValidFormat: 'silakan unggah file dengan format kode panggilan/telepon yang valid',
  campaignNotExist: 'Kampanye tidak ada',
  campaignIdToBePresent: 'ID kampanye harus ada',
  billCalculateError: 'Tidak bisa mendapatkan rincian biaya',
  campaignSuccessDeleteMsg: 'Kampanye marketing berhasil dihapus.',
  campaignAlreadyDeleted: 'Kampanye marketing sudah dihapus.',
  campaignNotFound: 'Kampanye marketing tidak ditemukan untuk dihapus',
  campaignExecutedMail:
    'Kampanye marketing Anda berhasil dijalankan. Detail kampanye sebagai berikut:',
  customerGroupIdToBeExist: 'ID grup pelanggan harus ada',
  atLeastOneCustomerGroupIdToBeExist: 'Setidaknya satu customer_group_id harus ada di sana',
  smsToBePresent: 'Template harus ada',
  unableToGetJson: 'Tidak dapat memperoleh json dari tautan.',
  campaignExecuted: 'Kampanye berhasil dibuat',
  campaignNotCreated: 'Tidak dapat membuat kampanye, harap coba lagi.',
  campaignName: 'Nama Kampanye',
  billId: 'ID Tagihan',
  name: 'Nama',
  campaignCost: 'Biaya Kampanye',
  uniqueSmsNote: 'Catatan: Pelanggan yang termasuk dalam beberapa grup hanya dikirimkan satu SMS.',
  customerGroup: 'Grup Pelanggan',
  customersCount: 'Jumlah Pelanggan',
  totalSms: 'Total SMS',
  freeSms: 'SMS Gratis',
  smsToPay: 'SMS untuk membayar',
  amountToBePaid: 'Jumlah yang Perlu Dibayar',
  invoice: 'Tagihan',
  marketingCampaign: 'Kampanye marketing',
  campaignSuccessMsg: 'Kampanye berhasil dijalankan',
  csvFileError: 'File CSV tidak dalam bentuk yang Tepat',
  amountSMSConflict: 'Jumlah yang harus dibayar/kredit SMS gratis tidak cocok, coba lagi!',
  finalAmount: 'Total Akhir',
  marketingReportName: 'LAPORAN TAGIHAN KAMPANYE MARKETING YANG BELUM LUNAS',
  marketingCampaignSheetName: 'Tagihan kampanye marketing',
  marketingCampaignXlsxSheetName: 'Tagihan Kampanye Marketing yang Belum Lunas.xlsx',
  couponNotFound: 'Kupon tidak ditemukan',
  deleteCouponCantUpdate: 'Anda tidak dapat memperbarui kupon yang telah dihapus',
  nothingUpdated: 'Tidak ada yang diperbarui',
  alreadyExist: 'sudah ada',
  couponUpdatedSuccess: 'Kupon berhasil diperbarui',
  couponDeletedSuccess: 'Kupon berhasil dihapus',
  couponAlreadyDeleted: 'Kupon sudah dihapus',
  headerCsvMismatchedVoucher:
    'Header tidak cocok, harap periksa header, header yang benar adalah kode-voucher, dan silakan coba lagi!',
  duplicateEntriesFor: 'entri duplikat untuk',
  atIndex: 'pada indeks',
  voucherCodeNotAtRow: 'kode voucher tidak tersedia pada baris',
  noRestHqFoundError: 'Tidak Ada HQ Restoran yang Ditemukan',
  couponTitle: 'Judul Kupon',
  voucherNotCreated: 'Voucher tidak dibuat',
  voucherCreatedSuccess: 'Voucher berhasil dibuat',
  orderDetailsNotFoundError: 'Detail pesanan tidak ditemukan',
  orderBillNotFoundError: 'Detail tagihan pesanan tidak ditemukan',
  voucherNotExist: 'Voucher tidak ada.',
  voucherInvalidMoment: 'Voucher tidak valid saat ini.',
  voucherInvalidToday: 'Voucher tidak valid hari ini.',
  voucherLimitExceed: 'Batas voucher terlampaui.',
  voucherAppliedSuccessfully: 'Voucher berhasil diterapkan.',
  voucherItemQNotSatisfied: 'Kuantitas item voucher tidak terpenuhi',
  voucherItemsRedeem:
    'Antara item/item voucher sudah ditukarkan atau item/item voucher tidak ditemukan untuk ditukarkan.',
  voucherItemsNotFoundToRedeem: 'Tidak ditemukan item/item voucher untuk ditukarkan.',
  nothingWasDeleted: 'Tidak ada yang dihapus',
  voucherDeleteSuccess: 'voucher berhasil dihapus',
  voucherNotFound: 'Voucher tidak ditemukan',
  deletedVoucherCantUpdate: 'Anda tidak dapat memperbarui judul voucher yang telah dihapus',
  voucherItemAddedSuccess: 'Detail item voucher berhasil ditambahkan ke pesanan',
  voucherItemAddedError: 'Detail item voucher tidak dapat ditambahkan ke pesanan',
  voucherRedeemQuantityUpdateSuccess:
    'Kuantitas voucher yang ditukarkan berhasil diperbarui pada pesanan',
  voucherRedeemQuantityUpdateError:
    'Kuantitas voucher yang ditukarkan tidak dapat diperbarui pada pesanan',
  orderBillUpdateSuccess: 'Tagihan berhasil diperbarui',
  orderBillUpdateError: 'Tagihan tidak diperbarui',
  voucherNotAppliedIn: 'Voucher tidak diterapkan di tagihan',
  voucherDetailsAddedOrderSuccess: 'Detail voucher berhasil ditambahkan ke pesanan',
  voucherDetailsAddedOrderError: 'Detail voucher tidak dapat ditambahkan ke pesanan',
  voucherDetailsCouldNotBeUpdated: 'Detail voucher tidak dapat diperbarui',
  voucherDetailsUpdatedSuccess: 'Detail voucher berhasil diperbarui',
  voucherCantAppliedOn: 'Voucher tidak dapat diterapkan pada',
  minimumCartValueIs: 'Nilai keranjang minimum adalah',
  needToAddItemsWorth: 'Tambah item senilai',
  moreToRedeemToCode: 'untuk menukarkan kode voucher ini.',
  orderDetailsForOrder: 'Detail Pesanan untuk ID Pesanan',
  orderBillForOrder: 'Detail Tagihan Pesanan untuk ID Pesanan',
  notFound: 'tidak ditemukan',
  notFoundInOrder: 'tidak ditemukan dalam pesanan',
  voucherNotRemovedUsedVoucher: 'voucher tidak dihapus dari voucher-terpakai',
  voucherRemovedSuccess: 'voucher berhasil dihapus',
  voucherRemovedError: 'voucher tidak dihapus dari pesanan',
  templateNotFound: 'Template Tidak Ditemukan',
  priceCutCouponNotFound: 'Kupon potongan harga tidak ditemukan',
  deleteCouponCantBeUpdate: 'Kupon yang dihapus tidak dapat diperbarui',
  itemAlreadyAddedPriceCut:
    'Satu atau lebih item dalam pilihan Anda telah digunakan dalam promosi potongan harga. Promosi penawaran terbaik pada item akan diterapkan secara otomatis.',
  masterCard: 'MASTERCARD (MC)',
  visa: 'VISA (V)',
  amex: 'AMERICAN EXPRESS',
  eodReportHeader: 'Laporan EOD untuk',
  sales: 'PENJUALAN',
  totalItemSales: 'TOTAL PENJUALAN ITEM (TIS)',
  topup: 'TOPUP (T)',
  promotions: 'PROMOSI (P)',
  platformCommission: 'KOMISI PLATFORM (PC)',
  netSalesEOD: 'PENJUALAN NETO (NS)',
  deliveryCharges: 'BIAYA PESAN ANTAR (DC)',
  serviceChargesEOD: 'BIAYA LAYANAN (SC)',
  packagingChargesEOD: 'BIAYA KEMASAN (PKC)',
  roundoffEOD: 'PEMBULATAN (RO)',
  governmentTax: 'PAJAK PEMERINTAH (GT)',
  governmentTaxPercent: 'PAJAK PEMERINTAH (%)',
  totalCollection: 'TOTAL KOLEKSI (TC)',
  orders: 'PESANAN',
  dineInEOD: 'MAKAN DI TEMPAT (DI)',
  ordersByCustomers: 'PESANAN OLEH PELANGGAN',
  ordersByStaff: 'PESANAN OLEH STAF',
  avgSalesOrder: 'RATA-RATA PENJUALAN/PESANAN',
  deliveryEOD: 'PESAN ANTAR (DL)',
  pickup: 'PICK UP (PU)',
  cancelledOrders: 'PESANAN BATAL (CO)',
  voidItems: 'ITEM BATAL (VI)',
  paymentDetails: 'DETAIL PEMBAYARAN',
  paymentCollection: 'KOLEKSI PEMBAYARAN (PYC)',
  refund: 'REFUND (RF)',
  cashSales: 'PENJUALAN TUNAI (CS)',
  offlineInfo:
    'OFFLINE = Pembayaran dilakukan oleh pelanggan di dalam outlet (di luar Aplikasi EasyEat)',
  offlineCreditCard: 'KARTU KREDIT OFFLINE (CCO)',
  offlineWallets: 'WALLET OFFLINE (OW)',
  offlineFPX: 'FPX OFFLINE (OFPX)',
  easyEatCollection: 'KOLEKSI EASYEAT (EEC)',
  wallet: 'WALLET ONLINE (WA)',
  internetBanking: 'INTERNET BANKING (FPX)',
  promotionsAndCommissions: 'PROMOSI & KOMISI',
  userAppPromotions: 'PROMOSI APLIKASI PENGGUNA (UAP)',
  manual: 'PROMOSI MANUAL (OP)',
  avgSalesPAX: 'RATA-RATA PENJUALAN/PAX',
  offline: 'OFFLINE',
  offlineMessage:
    'Artinya pembayaran dilakukan oleh pelanggan di dalam outlet (di luar Aplikasi EasyEat)',
  invoice_no: 'Tagihan No',
  no_of_items: 'JUMLAH ITEM',
  table: 'Meja No',
  order_seq: 'Pesanan No',
  payment_type: 'Tipe Pembayaran',
  paid: 'Lunas',
  unpaid: 'Belum Lunas',
  cashier: 'Kasir',
  customer_phone: 'TELEPON PELANGGAN',
  customer_name: 'NAMA PELANGGAN',
  staff_name: 'NAMA STAF',
  counter_name: 'NAMA KONTER',
  dine_in: 'Makan-di-Tempat',
  takeaway: 'Takeaway',
  noOfItemsVoid: 'Jumlah item batal',
  tableTransfer: 'Transfer Meja',
  opening_cash_float: 'CASH FLOAT PEMBUKA',
  total_cash_in: 'TOTAL TUNAI MASUK',
  cash_in_sales: 'PENJUALAN TUNAI MASUK',
  cash_in_others: 'TUNAI MASUK LAIN-LAIN',
  total_cash_out: 'TOTAL TUNAI KELUAR',
  net_cash_balance: 'SALDO KAS NETO',
  expected_cash_in_drawer: 'EKSPEKTASI TUNAI DI LACI',
  actual_cash_in_drawer: 'TUNAI AKTUAL DI LACI',
  excess_short_cash: 'KELEBIHAN/KEKURANGAN',
  close_cashier: 'TUTUP KASIR',
  drawer_kick: 'Buka Laci',
  open_cashier: 'Buka Kasir',
  cash_in: 'Tunai-Masuk',
  cash_out: 'Tunai-Keluar',
  powered_by: 'DIPERSEMBAHKAN OLEH',
  old: 'LAMA',
  new: 'BARU',
  notes: 'CATATAN',
  addon: 'ADD-ON',
  variant: 'VARIAN',
  discount: 'Diskon',
  delivery_fee: 'Biaya Pesan Antar',
  round_off: 'Pembulatan',
  total_amount: 'Jumlah Total',
  amount_paid: 'Jumlah Lunas',
  cash_received: 'Tunai Diterima',
  cash_returned: 'Tunai Dikembalikan',
  txn_id: 'Txn Id',
  item_name: 'Nama Item',
  balance: 'SALDO',
  amount_to_be_paid: 'Sisa Pembayaran',
  amount_to_refund: 'Pengembalian Dana',
  bill_date: 'TANGGAL TAGIHAN',
  picked_up_from: 'DIAMBIL DARI',
  delivered_to: 'TERKIRIM KE',
  receipt: 'Resi',
  thanks_for_ordering: 'Terima kasih sudah memesan',
  your_receipt: 'Berikut tanda terima Anda untuk',
  quantity: 'Kuantitas',
  price: 'Harga',
  you_ordered_from: 'Anda memesan dari',
  hi: 'Hai',
  greeting_from_EasyEat: 'salam dari EasyEat',
  please_find_attached_receipt: 'Berikut resi terlampir untuk tagihan',
  receipt_for_invoice: 'Resi untuk Tagihan',
  noVoucherInFiles: 'Tidak ada kode-voucher dalam file',
  setAtLeastOne: 'Harap tentukan setidaknya satu opsi limit',
  invalidCouponLimit: 'Nilai limit kupon tidak valid',
  selectApplicableDiscountType: 'Silakan pilih jenis diskon yang berlaku',
  selectApplicableDiscountValue: 'Silakan pilih nilai diskon yang berlaku',
  'applicableCantBeMoreThan100 ': 'Nilai diskon yang berlaku tidak boleh lebih besar dari 100%',
  email_sent_successfully: 'Email berhasil dikirim',
  cashier_closed_cash_in_error: 'Kasir tutup, untuk TUNAI-MASUK, buka kasir dulu',
  cashier_closed_cash_out_error: 'Kasir tutup, untuk TUNAI-KELUAR, buka kasir dulu',
  cashier_open_error: 'Kasir sudah dibuka',
  cashier_closed_error: 'Kasir sudah ditutup',
  please_provide_valid_amount: 'Silakan berikan jumlah yang valid untuk',
  cash_in_done_successfully: 'TUNAI-MASUK berhasil dilakukan',
  done_successfully: 'berhasil dilakukan',
  'cash-in': 'TUNAI-MASUK',
  'cash-out': 'TUNAI-KELUAR',
  'open-cashier': 'BUKA-KASIR',
  'close-cashier': 'TUTUP-KASIR',
  cash_in_hand: 'Tunai di Tangan',
  add_cash_first: 'tambahkan Uang Tunai terlebih dahulu untuk melakukan',
  complete_active_orders_error:
    'Harap selesaikan atau batalkan semua pesanan yang aktif sebelum menutup kasir',
  drawer_opened_successfully: 'Laci berhasil dibuka',
  cash_management_system_not_found: 'Sistem manajemen kas tidak ditemukan',
  close_cashier_for_cashier_report: 'Untuk mendapatkan laporan kasir, tutup kasir terlebih dahulu',
  no_entries_found: 'Tidak ada entri yang ditemukan',
  status: 'STATUS',
  no_reviews_found: 'Ulasan tidak ditemukan',
  rest_not_related_to_hq_error: 'Restaurant_id yang diberikan tidak terhubung dengan HQ saat ini',
  outlet_name: 'NAMA OUTLET',
  dial_code: 'KODE PANGGILAN',
  phone_number: 'NOMOR TELEPON',
  review: 'ULASAN',
  ratings: 'RATING',
  order_type: 'TIPE PESANAN',
  restaurant: 'Restoran',
  review_report_over_time: 'Laporan Ulasan Seiring Waktu',
  no_data_found: 'Data Tidak Ditemukan',
  latest_date_of_purchase: 'Tanggal Pembelian Terbaru',
  total_purchases_made: 'Total Pembelian yang Dilakukan',
  whatsapp_link: 'Tautan Whatsapp',
  user_data_report_file_header: 'Data Pengguna untuk Semua Restoran',
  user_data_sheet_name: 'Data Pengguna Restoran',
  user_data_report_filename: 'Data_Pengguna_Restoran',
  allergies: 'ALERGI',
  outermostIndex: 'dalam outermost array pada indeks',
  valueCanBeApplyArray: 'nilai hanya bisa type array',
  inArrayAtIndex: 'dalam inner array pada indeks',
  inInnerArrayAtIndex: 'dalam nilai innermost array pada indeks',
  canOnlyBeNumber: 'hanya bisa berupa angka',
  unmapped_item_text:
    'Silakan ke Bagian & Konter pada Aplikasi Partner EasyEat untuk memetakan item-item ini ke konter',
  invalid_counter_text:
    'Konter-konter yang ditetapkan untuk item-item ini tidak valid & menginterupsi konter dari subkategori di dalamnya',
  master_counter_text:
    'Berikut adalah item baru yang ditambahkan ke pesanan ini oleh pelanggan. Lihat resi sebelumnya untuk memeriksa item lama.',
  canceled_items_text: 'Item ini dibatalkan dari pesanan ini',
  item_not_available_text: 'Item Tidak Tersedia',
  items_not_available_text: 'Item Tidak Tersedia',
  some_items_not_available_text: 'Beberapa Item Tidak Tersedia',
  order_declined_text: 'Pesanan ini telah ditolak',
  items_declined_text: 'Item-item ini telah ditolak dari pesanan ini',
  signed_by: 'TERTANDA OLEH',
  master_docket: 'Doket Utama',
  master_order_list: 'Daftar Pesanan Utama',
  void_item: 'Item Batal',
  cancel_item: 'Batalkan Item',
  item_voided: 'Item Dibatalkan',
  declined_order: 'Pesanan Ditolak',
  cash_not_tallied: 'Tunai tidak sesuai hitungan',
  'Packaging Charges': 'Biaya Kemasan',
  SST: 'SST',
  cancelled: 'Dibatalkan',
  waiting: 'Menunggu',
  confirmed: 'Dikonfirmasi',
  in_progress: 'Dalam Progres',
  more_items_added: 'Lebih Banyak Item Ditambahkan',
  user_cancelled: 'Pengguna Membatalkan',
  restaurant_cancelled: 'Restoran Membatalkan',
  system_cancelled: 'Sistem Membatalkan',
  deleted: 'Dihapus',
  scheduled: 'Terjadwal',
  'scheduled_&_accepted': 'Dijadwalkan & Diterima',
  unknown: 'Tak Dikenal',
  dateRangeCantExceed90Days: 'Rentang tanggal tidak boleh lebih dari 90 hari',
  pickupMain: 'Pick Up',
  na: 'NA',
  card: 'KARTU KREDIT (CC)',
  order_no: 'PESANAN NO.',
  staff_details: 'Detail Staf',
  day: 'HARI',
  designation: 'JABATAN',
  clock_in: 'CATAT MASUK',
  clock_out: 'CATAT KELUAR',
  duration_in_hours: 'DURASI (dalam Jam)',
  inventory_status_report: 'Laporan Status Inventaris',
  report_no: 'LAPORAN NO.',
  order_status: 'STATUS PESANAN',
  'Restaurant Details': 'Detail Restoran',
  'Restaurant Charges': 'Biaya Restoran',
  'Offline Platform Details': 'Detail Platform Offline',
  'Add Item': 'Tambah Item',
  'Void Item': 'Batalkan Item',
  'Decline Order': 'Tolak Pesanan',
  'Delete Order': 'Hapus Pesanan',
  'Add Discount': 'Tambah Diskon',
  'Table Transfer': 'Transfer Meja',
  'Menu Item Settings': 'Pengaturan Item Menu',
  'Item Visibility': 'Visibilitas Item',
  'Item Availability': 'Ketersediaan Item',
  Report: 'Laporan',
  'Generate EOD': 'Hasilkan EOD',
  'Open Cashier': 'Buka Kasir',
  'Close Cashier': 'Tutup Kasir',
  'Add Cash In': 'Tambah Tunai Masuk',
  'Add Cash Out': 'Tambah Tunai Keluar',
  'Drawer Kick': 'Buka Laci',
  'Section Settings': 'Pengaturan Bagian',
  'Printer Settings': 'Pengaturan Printer',
  'Loyalty Settings': 'Pengaturan Loyalty',
  'Inventory List': 'Daftar Inventaris',
  'Promotion Settings': 'Pengaturan Promosi',
  'Table Services': 'Layanan Meja',
  'Restaurant Analytics': 'Analitik Restoran',
  'EasyEat HQ': 'HQ EasyEat',
  'EasyEat Outlets': 'Outlet EasyEat',
  'Manage Staff': 'Kelola Staf',
  'Download Data': 'Unduh Data',
  'Provide Other Employee Access To HQ': 'Berikan Akses Karyawan Lain Ke HQ',
  'Provide Other Employee Access To POS': 'Berikan Akses Karyawan Lain Ke POS',
  'Roles And Permission': 'Peran dan Izin',
  'Table Settings': 'Pengaturan Meja',
  'Download Summary': 'Unduh Ringkasan',
  Settlements: 'Settlement',
  counter_decline_text: 'Item ini ditolak dari pesanan ini',
  counter_cancel_text: 'Item ini dibatalkan dari pesanan ini',
  voucherReportTitle: 'JUDUL LAPORAN VOUCHER',
  'Restaurant Tax (PB1)': 'Pajak Restoran (PB1)',
  'Service Charge': 'Biaya Layanan',
  table_changed: 'Meja Berubah',
  payment_mode: 'Mode Pembayaran',
  dish_out_of_stock: 'Hidangan habis',
  variant_out_of_stock: 'Varian habis',
  addon_out_of_stock: 'Add-On habis',
  'Restaurant Manager': 'Manajer Restoran',
  cannotUpdateServiceCharge: 'Tidak dapat memperbarui biaya layanan untuk jenis pesanan ini',
  serviceChargeNotApplicable: 'Pajak layanan tidak berlaku di restoran ini',
  serviceChargeNotAdded: 'Biaya layanan tidak ditambahkan',
  serviceChargeAdded: 'Biaya layanan berhasil ditambahkan',
  serviceChargeNotRemoved: 'Biaya layanan tidak dihapus',
  serviceChargeRemoved: 'Biaya layanan berhasil dihapus',
  unableToUpdateServiceCharge: 'Tidak dapat memperbarui Biaya Layanan',
  gluten: 'Gluten',
  fish: 'Ikan',
  nuts: 'Kacang-Kacangan',
  'seafood and shellfish': 'Makanan Laut dan Kerang-Kerangan',
  wheat: 'Gandum',
  oats: 'Gandum',
  barley: 'Barley',
  corn: 'Jagung',
  cashew: 'Kacang Mete',
  almonds: 'Kacang Almond',
  'fields.address_1 should not be empty': 'field.address_1 wajib diisi',
  'Restaurant details updated successfully': 'Detail restoran berhasil diperbarui',
  'Nothing was updated': 'Tidak ada yang diperbarui',
  'Restaurant tables not found': 'Meja restoran tidak ditemukan',
  'floors not found on this restaurant': 'lantai tidak ditemukan di restoran ini',
  floor_id: 'id_lantai',
  "doesn't exists": 'tidak ada',
  "You can't add table in": 'Anda tidak dapat menambahkan meja di',
  floor: 'lantai',
  'Table number': 'Nomor Meja',
  'already exists on': 'sudah ada di',
  'Table added successfully': 'Meja berhasil ditambahkan',
  'Nothing added': 'Tidak ada yang ditambahkan',
  'Table could not be added': 'Meja tidak dapat ditambahkan',
  "You can't delete table from": 'Anda tidak dapat menghapus meja dari',
  'Please complete or cancel all active orders before delete table details':
    'Harap selesaikan atau batalkan semua pesanan yang aktif sebelum menghapus detail meja',
  'Table deleted successfully': 'Meja berhasil dihapus',
  'Nothing deleted': 'Tidak ada yang dihapus',
  'Table could not be deleted': 'Meja tidak dapat dihapus',
  "You can't update a table in": 'Anda tidak dapat memperbarui meja di',
  table_id: 'table_id',
  'Please complete or cancel all active orders before update table details':
    'Harap selesaikan atau batalkan semua pesanan aktif sebelum memperbarui detail meja',
  'Table updated successfully': 'Meja berhasil diperbarui',
  'Table could not be updated': 'Meja tidak dapat diperbarui',
  'Offline platforms tables created for restaurant successfully':
    'Table platform offline berhasil dibuat untuk restoran',
  'No offline platform found on this restaurant':
    'Tidak ada platform offline yang ditemukan di restoran ini',
  'Offline platforms tables created for all restaurants successfully':
    'Table platform offline berhasil dibuat untuk semua restoran',
  'Category name already exits': 'Nama kategori sudah ada',
  'category added successfully': 'kategori berhasil ditambahkan',
  'category updated successfully': 'kategori berhasil diperbarui',
  'User is not authorized to perform this action':
    'Pengguna tidak diizinkan untuk melakukan tindakan ini',
  'User Authorized': 'Pengguna Diizinkan',
  'Please Upload The File First': 'Silahkan Unggah File-nya Terlebih Dahulu',
  "Fields values (except sku,description,category,supplier,item_type) can't be empty.Check at sr. no.":
    'Nilai kolom (kecuali sku, deskripsi, kategori, pemasok, item_type) tidak boleh kosong. Periksa di Sr. No.',
  'duplicate entry for': 'entri duplikat untuk',
  'at index': 'pada indeks',
  'Inventory not found': 'Inventaris tidak ditemukan',
  'Product Not Found': 'Produk Tidak Ditemukan',
  'Product Details For': 'Detail Produk untuk',
  'Product Updated Successfully': 'Produk Berhasil Diperbarui',
  'Product Added Successfully': 'Produk Berhasil Ditambah',
  'Could NOT Add Product': 'TIDAK Dapat Menambahkan Produk',
  'Invalid Inventory': 'Inventaris Tidak Valid',
  'Email Sent Successfully': 'Email berhasil dikirim',
  'Could NOT Send Email, Please Check Email Address':
    'TIDAK Bisa Mengirim Email, Silakan Periksa Alamat Email',
  'Order Not Found': 'Pesanan Tidak Ditemukan',
  'Order Details For': 'Detail Pesanan untuk',
  'Order Added Successfully': 'Pesanan Berhasil Ditambah',
  'Could NOT Add Order': 'TIDAK Bisa Menambahkan Pesanan',
  'Order Updated Successfully': 'Pesanan Berhasil Diperbarui',
  'Orders Removed Successfully': 'Pesanan Berhasil Dihapus',
  'Orders Not Found To Delete': 'Pesanan Tidak Ditemukan Untuk Dihapus',
  'inventory details doest not exist for item': 'detail inventaris tidak ada untuk item',
  'Stock Update Not Found': 'Pembaruan Stok Tidak Ditemukan',
  'Stock Update Details For': 'Detail Pembaruan Stok untuk',
  'Start Date Should Always Less Than End Date':
    'Tanggal Mulai Harus Selalu Kurang Dari Tanggal Akhir',
  'Stock_Update Added Successfully': 'Pembaruan_Stok Berhasil Ditambah',
  'Stock_Update Already In The Inventory': 'Pembaruan_Stok Sudah dalam Inventaris',
  'Either Products or Items is empty': 'Produk atau Item kosong',
  'Stock_Update Updated Successfully': 'Pembaruan Stok Berhasil Diperbarui',
  'Stock Updates Removed Successfully': 'Pembaruan Stok Berhasil Dihapus',
  'Stock Updates Not Found To Delete': 'Pembaruan Stok Tidak Ditemukan untuk Dihapus',
  'Supplier Not Found': 'Pemasok Tidak Ditemukan',
  'Supplier Added Successfully': 'Pemasok Berhasil Ditambahkan',
  'Supplier Already Added In Inventory': 'Pemasok Sudah Ditambahkan dalam Inventaris',
  'Supplier Updated Successfully': 'Pemasok Berhasil Diperbarui',
  'Suppliers Not Found To Delete': 'Pemasok Tidak Ditemukan untuk Dihapus',
  'Suppliers Removed Successfully': 'Pemasok Berhasil Dihapus',
  nil: 'NOL',
  paymentDetailsUpdatedSuccess: 'Detail pembayaran berhasil diperbarui',
  nothingWasUpdated: 'Tidak ada yang diperbarui',
  paymentDetailsNotFound: 'Detail pembayaran tidak ditemukan',
  orderBillNotCreated: 'Tagihan pesanan tidak dapat dibuat',
  orderBillNotUpdated: 'Tagihan pesanan tidak dapat diperbarui',
  orderBillCreatedSuccess: 'Tagihan pesanan berhasil dibuat',
  orderBillUpdatedSuccess: 'Tagihan pesanan berhasil dibuat',
  unableToUpdateGuestBills: 'Tidak dapat memperbarui tagihan tamu',
  guestBillsNotUpdated: 'Tagihan tamu tidak diperbarui',
  guestBillsUpdated: 'Tagihan tamu diperbarui',
  discountNotApplied: 'Diskon tidak diterapkan',
  discountUpdatedSuccessfully: 'Diskon berhasil diperbarui',
  'Hi there': 'Hai',
  createHqEmail:
    'Kami senang Anda bergabung! HQ memudahkan Anda untuk melihat laporan settlement setiap hari untuk semua outlet. Dengan menggunakan marketing untuk grup pelanggan, Anda dapat meluncurkan kampanye SMS dan meningkatkan repeat order. Ada banyak lagi fitur untuk Anda di sini.',
  'Your account has been created with email:': 'Akun Anda telah dibuat dengan email:',
  'and password': 'dan kata sandi:',
  'You can reset your password as you like.': 'Anda dapat mereset kata sandi Anda sesuka Anda.',
  'EXPLORE YOUR ACCOUNT': 'JELAJAHI AKUN ANDA',
  'With love,': 'Salam kasih,',
  'Easy Eat Team': 'Tim EasyEat',
  'Welcome to Easy Eat': 'Selamat datang di EasyEat',
  hqCreateMsg:
    'HQ memudahkan Anda untuk melihat laporan settlement setiap hari untuk semua outlet. Dengan menggunakan marketing untuk grup pelanggan, Anda dapat meluncurkan kampanye SMS dan meningkatkan pesanan berulang. Ada banyak lagi untuk Anda di sini.',
  'click the link below to reset or update your password at':
    'klik tautan di bawah ini untuk mereset atau memperbarui kata sandi Anda di',
  'in Easy Eat HQ app': 'di aplikasi HQ EasyEat',
  'Welcome to the team': 'Selamat datang di tim',
  "It's time to take control over your restaurant with quicker service, increased profits, and simplified workflows":
    'Saatnya untuk mengambil kendali atas restoran Anda dengan layanan yang lebih cepat, peningkatan profit, dan alur kerja yang lebih sederhana',
  'You have been given employee access at': 'Anda telah diberikan akses staf di',
  'in Easy Eat HQ app! Click the link below to complete your registration':
    'di aplikasi HQ Easy Eat! Klik tautan di bawah ini untuk menyelesaikan pendaftaran Anda',
  'Reset Password': 'Reset Kata Sandi',
  'Complete Registration': 'Lengkapi Registrasi',
  "Let's change the food industry with technology": 'Mari ubah industri makanan dengan teknologi',
  'Thank you': 'Terima kasih',
  'Reset your password at': 'Reset kata sandi Anda di',
  "Welcome! You're now part of": 'Selamat datang! Anda sekarang bagian dari',
  'Hi, click the link to update your password at Easy Eat HQ':
    'Hai, klik tautan untuk memperbarui kata sandi Anda di HQ EasyEat',
  'Hi, welcome to Easy Eat HQ! Click the link to complete your profile':
    'Hai, selamat datang di HQ Easy Eat! Klik tautan untuk melengkapi profil Anda',
  'Please provide either user_id or login_email': 'Harap berikan user_id atau login_email',
  'User Not Found': 'Pengguna Tidak Ditemukan',
  'HQ access is not enabled for this staff': 'Akses HQ tidak diaktifkan untuk staf ini',
  'Restaurant HQ Not Found': 'HQ Restoran Tidak Ditemukan',
  'Unable to send password': 'Tidak dapat mengirim kata sandi',
  reset: 'reset',
  creation: 'pembuatan',
  link: 'tautan',
  Password: 'Kata Sandi',
  'email sent successfully': 'Email berhasil dikirim',
  'sms sent successfully': 'SMS berhasil dikirim',
  order: 'Pesanan',
  DELIVERY: 'PESAN ANTAR',
  DINING: 'DINING',
  TAKEAWAY: 'TAKEAWAY',
  'APPROVED BY': 'DISETUJUI OLEH',
  'Could not get addons as item_id and restaurant_id are null':
    'Tidak bisa mendapatkan add-on karena item_id dan restaurant_id adalah null',
  'Addons added successfully': 'Add-on berhasil ditambahkan',
  'Failed to add addon': 'Gagal menambahkan add-on',
  'Addon not found': 'Add-On tidak ditemukan',
  'Updated addons for addon_id': 'Add-On yang Diperbarui untuk addon_id',
  'Add-Ons Not updated': 'Add-On Tidak Diperbarui',
  'Unable to update Addon': 'Tidak dapat memperbarui Add-On',
  'Addon updated successfully': 'Add-On berhasil diperbarui',
  'Category Not Found': 'Kategori Tidak Ditemukan',
  'Option group not found': 'Grup opsi tidak ditemukan',
  'Following restaurant_ids are invalid': 'Restaurant_id berikut tidak valid',
  'Unable to add menu option group': 'Tidak dapat menambahkan grup opsi menu',
  'Menu option group added successfully': 'Grup opsi menu berhasil ditambahkan',
  'Menu option group updated successfully': 'Grup opsi menu berhasil diperbarui',
  'Unable to update menu option group': 'Tidak dapat memperbarui grup opsi menu',
  'Menu option group deleted successfully': 'Grup opsi menu berhasil dihapus',
  'Inventory updated successfully': 'Inventaris berhasil diperbarui',
  'Item Not Found': 'Item tidak ditemukan',
  'Item Deleted Successfully': 'Item Berhasil Dihapus',
  'Either Item not found! or Item already deleted': 'Item tidak ditemukan! atau Item sudah dihapus',
  'No HQ found for this restaurant': 'Tidak ditemukan HQ untuk restoran ini',
  "Set original price of item > 0 to define item's price for dine-in, delivery & takeaway":
    'Tetapkan harga asli item > 0 untuk menentukan harga item untuk makan-di-tempat, pesan antar & takeaway',
  'Category not found in restaurant': 'Kategori tidak ditemukan di restoran',
  'Subcategory not found in restaurant': 'Subkategori tidak ditemukan di restoran',
  'Item name': 'Nama Item',
  'already exists': 'sudah ada',
  'Item Code length cannot be greater than 5 characters':
    'Panjang Kode Item tidak boleh lebih dari 5 karakter',
  'Item Code': 'Kode Item',
  'You can enter a value upto 10000': 'Anda dapat memasukkan nilai hingga 10.000',
  'Either combo_items is not defined or it not an array':
    'Antara combo_items tidak didefinisikan atau bukan array',
  'Item with id': 'Item dengan id',
  'Images deleted successfully': 'Gambar berhasil dihapus',
  'Some images failed to delete': 'Beberapa gambar gagal dihapus',
  'Thumbnail Path Updated in DB': 'Jalur Thumbnail Diperbarui di DB',
  'Thumbnail Path Not Updated in DB': 'Jalur Thumbnail Tidak Diperbarui di DB',
  "Image To Be Set As Thumbnail Doesn't Exists in DB":
    'Gambar yang Akan Ditetapkan Sebagai Thumbnail Tidak Ada di DB',
  'Image Path Added in DB': 'Jalur Gambar Ditambahkan di DB',
  'Image Path Not Added in DB': 'Jalur Gambar Tidak Ditambahkan di DB',
  'Thumbnail Path Added in DB': 'Jalur Thumbnail Ditambahkan di DB',
  'Thumbnail Path Not Added in DB': 'Jalur Thumbnail Tidak Ditambahkan di DB',
  'Some images failed to upload, please check image type(jpeg,png) and size(<2MB)':
    'Beberapa gambar gagal diunggah, harap cek jenis gambar (jpeg, png) dan ukuran ( < 2 MB)',
  'Open items default sub_category not found': 'Sub_kategori default Item Terbuka tidak ditemukan',
  'Open items default category not found': 'Kategori default Item Terbuka tidak ditemukan',
  'Open items not enabled': 'Item Terbuka tidak diaktifkan',
  'Mapping already exists': 'Pemetaan sudah ada',
  'Cannot add or update a child row: a foreign key constraint fails':
    'Tidak dapat menambah atau memperbarui child row: foreign key constraint gagal',
  'No mapping Found': 'Pemetaan Tidak Ditemukan',
  'Mapping removed successfully': 'Pemetaan berhasil dihapus',
  'No mapped items found associated with this item':
    'Item yang dipetakan tidak ditemukan terkait dengan item ini',
  'Discount exceed actual price of the combo': 'Diskon melebihi harga asli dari kombo',
  'Role Not Found': 'Peran Tidak Ditemukan',
  'Please select at least one restaurant': 'Silakan pilih setidaknya satu restoran',
  'Role with name': 'Peran dengan nama',
  Role: 'Peran',
  'Unable to create new role': 'Tidak dapat membuat peran baru',
  'Role created successfully': 'Peran berhasil dibuat',
  'Role name': 'Nama Peran',
  'is reserved, please enter a different role name':
    'sudah tersimpan, silakan masukkan nama peran yang berbeda',
  'Role not updated': 'Peran tidak diperbarui',
  'Role updated successfully': 'Peran berhasil diperbarui',
  'Role deleted successfully': 'Peran berhasil dihapus',
  'Ready to clock-in': 'Siap untuk pencatatan datang',
  'Ready to clock-out': 'Siap untuk pencatatan pulang',
  'Something went wrong': 'Terjadi Kesalahan',
  'Clock-in Failed': 'Pencatatan Datang Gagal',
  'Clock-in Successful': 'Pencatatan Datang Berhasil',
  'Staff Not Found': 'Staf Tidak Ditemukan',
  'Clock-out Successful': 'Pencatatan Pulang Berhasil',
  'Clock-out Failed': 'Pencatatan Pulang Gagal',
  'Please provide either hq_id or restaurant_ids list':
    'Harap berikan daftar hq_id atau restaurant_ids',
  'Please enter at least one restaurant_id': 'Harap masukkan setidaknya satu restaurant_id',
  'You are not authorised to perform this action':
    'Anda tidak diizinkan untuk melakukan tindakan ini',
  'Email ID cannot be empty': 'ID Email tidak boleh kosong',
  'PIN cannot be empty': 'PIN tidak boleh kosong',
  'This email is already taken': 'Email ini sudah digunakan',
  'PIN already exists': 'PIN sudah ada',
  'your login PIN to access Easy Eat POS is': 'PIN login Anda untuk mengakses POS Easy Eat adalah',
  "Please don't share this with anyone. Visit":
    'Tolong jangan bagikan ini dengan siapa pun. Kunjungi',
  'You are not authorised to provide role with HQ access':
    'Anda tidak berwenang untuk memberikan peran dengan akses HQ',
  'You are not authorised to provide role with POS access':
    'Anda tidak diizinkan untuk memberikan peran dengan akses POS',
  'Unable to update staff details': 'Tidak dapat memperbarui detail staf',
  'Staff details updated successfully': 'Detail staf berhasil diperbarui',
  'No image uploaded': 'Tidak ada gambar yang diunggah',
  'user_id cannot be empty': 'user_id tidak boleh kosong',
  'Unable to upload image': 'Tidak dapat mengunggah gambar',
  'Staff details deleted': 'Detail staf dihapus',
  'Item could not be deleted': 'Item tidak dapat dihapus',
  noCustomerExistInSelected: 'Tidak ada pelanggan dalam grup pelanggan yang dipilih.',
  noGrabOrderCreated: 'Tidak ada pesanan Grabfood yang dibuat',
  newOrderCreated: 'pesanan baru dibuat',
  unmappedItems: 'Item yang Belum Dipetakan',
  foundIn: 'ditemukan di',
  createManually: 'pesanan tidak dibuat. Harap buat pesanan secara manual.',
  noNewGrabOrderFound: 'Tidak ada pesanan Grabfood baru yang ditemukan',
  'end_date cannot be less than start_date': 'tanggal_akhir tidak boleh kurang dari tanggal_mulai',
  'Unable to update commissions': 'Tidak dapat memperbarui komisi',
  'Commission structure updated successfully': 'Struktur komisi berhasil diperbarui',
  'Nothing to update': 'Tidak ada yang perlu diperbarui',
  'Restaurant with id': 'Restoran dengan id',
  'Fee details for id': 'Rincian biaya untuk id',
  'Tax/Charge added successfully': 'Pajak/Biaya berhasil ditambahkan',
  'Fee details updated successfully': 'Detail biaya berhasil diperbarui',
  'Fee details not found': 'Detail biaya tidak ditemukan',
  'Fee details removed successfully': 'Detail biaya berhasil dihapus',
  'Fee details already deleted': 'Detail biaya sudah dihapus',
  'Fee not found to delete': 'Biaya tidak ditemukan untuk dihapus',
  'Platforms not found': 'Platform tidak ditemukan',
  'Platform not exists on Easyeat': 'Platform tidak ada di EasyEat',
  'Platform Added successfully': 'Platform berhasil Ditambahkan',
  'Platform already added': 'Platform sudah ditambahkan',
  'Platform Updated successfully': 'Platform berhasil Diperbarui',
  'Please complete or cancel all active orders on this platform before deletion':
    'Harap selesaikan atau batalkan semua pesanan aktif di platform ini sebelum penghapusan',
  'Platform removed successfully': 'Platform berhasil dihapus',
  'Platform already removed': 'Platform sudah dihapus',
  'Table not found': 'Meja Tidak Ditemukan',
  'Restaurant tables  not found': 'Meja restoran tidak ditemukan',
  'Eod Update': 'Pembaruan EOD',
  'opening cash float': 'Cash Float Pembuka',
  'cash float change': 'Perubahan Cash Float',
  'customer refund': 'refund dana pelanggan',
  purchases: 'Pembelian',
  'paid to staff': 'dibayarkan ke staf',
  'cancel order': 'Batalkan pesanan',
  tip: 'tip',
  'sell non-menu items': 'Jual item non-menu',
  'customer change request': 'permintaan kembalian pelanggan',
  'drawer-kick': 'buka-laci',
  easyEatAddress:
    'Easy Eat, Lantai 38 Mercu 2, 3 Jalan Bangsar, KL Eco City, 59200 Kuala Lumpur, W.P. Kuala Lumpur',
  tableNoUpdated: 'Nomor Meja berhasil diperbarui',
  nothingUpdatedTable: 'Tidak ada yang diperbarui',
  orderNotFoundTable: 'Pesanan tidak ditemukan',
  tableNoCannotBeUpdated: 'Nomor Meja tidak dapat diperbarui.',
  tableNotFound: 'Meja Tidak Ditemukan',
  tableLiesIn: 'Meja ini terletak di',
  tableCantBeUpdated: 'lantai, sehingga meja tidak dapat diperbarui',
  'Section could not be added': 'Bagian tidak dapat ditambahkan',
  'Section added successfully': 'Bagian berhasil ditambahkan',
  'Floor name already exists': 'Nama lantai sudah ada',
  "This floor can't be deleted": 'Lantai ini tidak dapat dihapus',
  'Please complete or cancel all active orders before delete section details':
    'Harap selesaikan atau batalkan semua pesanan aktif sebelum menghapus detail bagian',
  'Section deleted successfully': 'Bagian berhasil dihapus',
  'Section could not be deleted': 'Bagian tidak dapat dihapus',
  "This floor can't be updated": 'Lantai ini tidak dapat diperbarui',
  'does not exists': 'tidak ada',
  'Please complete or cancel all active orders before update section details':
    'Harap selesaikan atau batalkan semua pesanan aktif sebelum memperbarui detail bagian',
  'Section updated successfully': 'Bagian berhasil diperbarui',
  'Nothing updated': 'Tidak ada yang diperbarui',
  'Section could not be updated': 'Bagian tidak dapat diperbarui',
  'Either row or column position for a table is out of floor rows and columns specification, or row and column values are negative':
    'Posisi baris atau kolom untuk meja di luar spesifikasi baris dan kolom lantai, atau nilai baris dan kolom negatif',
  'Please complete or cancel all active orders before removing tables from layout':
    'Harap selesaikan atau batalkan semua pesanan aktif sebelum menghapus meja dari tata letak',
  'both values of row and column values either can be only number or null':
    'baik nilai baris dan nilai kolom hanya bisa berupa angka atau nol',
  id: 'id',
  ids: 'id',
  "doesn't": 'tidak',
  "don't": 'jangan',
  exists: 'ada',
  exist: 'ada',
  'Layout saved successfully': 'Tata letak berhasil disimpan',
  'Nothing saved': 'Tidak ada yang disimpan',
  'Layout could not be saved': 'Tata letak tidak dapat disimpan',
  'To delete': 'Untuk menghapus',
  Table: 'meja',
  'please contact Admin': 'Silakan hubungi Admin',
  'Deletion setting is enable for': 'Pengaturan penghapusan diaktifkan untuk',
  'Settings updated successfully': 'Pengaturan berhasil diperbarui',
  'Unable to update image': 'Tidak dapat memperbarui gambar',
  'Image updated successfully': 'Gambar berhasil diperbarui',
  restaurant_ids_cannot_be_empty: 'restaurant_ids tidak boleh kosong',
  invalid_restaurant: 'Restoran Tidak Valid',
  provide_both_start_and_end_date: 'Berikan tanggal_mulai & tanggal_akhir',
  invalid_start_date: 'Tanggal_mulai tidak valid',
  invalid_end_date: 'Tanggal_akhir tidak valid',
  settlement_history: 'Riwayat Settlement',
  settled_order_details: 'Detail Pesanan Selesai',
  settled_adjustment_details: 'Detail Penyesuaian yang Diselesaikan',
  no_parameters_specified: 'Tidak ada parameter yang ditentukan',
  settlement_not_found: 'Settlement Tidak Ditemukan',
  settlement_id: 'ID SETTLEMENT',
  restaurant_id: 'ID RESTORAN',
  message: 'PESAN',
  date_and_time: 'TANGGAL & WAKTU',
  transaction: 'TRANSAKSI',
  transaction_amount: 'JUMLAH TRANSAKSI',
  paid_by_customer: 'Dibayar oleh pelanggan',
  paid_to_customer: 'Dibayar ke pelanggan',
  easyeat_collection: 'KOLEKSI EASYEAT',
  easyeat_cashback: 'CASHBACK EASYEAT',
  restaurant_cashback: 'CASHBACK RESTORAN',
  technology_charge: 'BIAYA TEKNOLOGI',
  payment_gateway_charge: 'BIAYA PAYMENT GATEWAY',
  amount_payable: 'JUMLAH YANG HARUS DIBAYAR',
  applicable_tech_charges: 'BIAYA TEKNOLOGI YANG BERLAKU',
  applicable_pg_charges: 'BIAYA PG YANG BERLAKU',
  adjustment: 'PENYESUAIAN',
  remarks: 'CATATAN',
  ID: 'PENGENAL',
  'Created On': 'Dibuat pada',
  'Finish At': 'Selesai Pada',
  'Stock Update List Report': 'Laporan Daftar Pembaruan Stok',
  'Stock Update Over Time': 'Pembaruan Stok Seiring Waktu',
  'Payment deleted successfully': 'Pembayaran berhasil dihapus',
};

module.exports = { idKeys };
